### ISSUE TITLE
C3D compilation error

### ISSUE THREAD

**Issue by Michael-Guo** [facebook/C3D#10]
I have successfully installed the Caffe with mkl and CUDA 7.0 and cuDNN. But when I install the C3D, I use command :make in the directory of C3D-master. Then I have two errors as follow.

src/caffe/util/math_functions.cu(140): error: calling a __host__ function("std::signbit<float> ") from a __global__ function("caffe::sgnbit_kernel<float> ") is not allowed

src/caffe/util/math_functions.cu(140): error: calling a __host__ function("std::signbit<double> ") from a __global__ function("caffe::sgnbit_kernel<double> ") is not allowed

2 errors detected in the compilation of "/tmp/tmpxft_0000342d_00000000-13_math_functions.compute_35.cpp1.ii".
make: *** [build/src/caffe/util/math_functions.cuo] error 2

What can I do for this, thank you very much!

**Comment by dutran** [comment]
I think you got similar issue to this (https://github.com/facebook/C3D/issues/2) which comes from different version of CUDA. Simply make the following change

In caffe/include/caffe/util/math_functions.hpp, change

using std::signbit;
DEFINE_CAFFE_CPU_UNARY_FUNC(sgnbit, y[i] = signbit(x[i])); 

to

// using std::signbit;
DEFINE_CAFFE_CPU_UNARY_FUNC(sgnbit, y[i] = std::signbit(x[i]));

**Comment by Michael-Guo** [comment]
Thank you very much! I compile successfully with your help. But I think the path should be /C3D-master/include/include/caffe/util/math_functions.hpp

**Comment by dutran** [comment]
glad to hear it works for you.
