### ISSUE TITLE
A problem for feature_extraction

### ISSUE THREAD

**Issue by tzczsq** [facebook/C3D#102]
Hi, we have fine_tuned your model on our dataset. Now I use the fine_tuned model for feature extraction tasks on our dataset.
For instance, we have a testing data set 426 video clips, when batch_size =50,  the parameter: the number of mini_batch should be set to be 9 for all video clips. However, I can successfully implement it with mini_batch =1, but when mini_batch is more than 1, an error exists, as described below.

GLOG_logtosterr=1 ../../build/tools/extract_image_features.bin prototxt/c3d_sport1m_feature_extractor_frm_RML.prototxt c3d_ucf101_finetune_whole_iter_600 1 50 2 /home/sqzhang/RML_Video_16frames_3DCNN/output_list/RML_list1.txt fc7-1

1) mini_batch=2;
E0403 14:23:01.521628 23578 extract_image_features.cpp:72] Extracting features for 2 batches
E0403 14:23:02.853245 23578 extract_image_features.cpp:108] Extracted features of 50 images.
F0403 14:23:03.348901 23614 video_data_layer.cpp:123] Check failed: read_status Testing must not miss any example

2)mini_batch=9;
E0403 14:30:53.872324 24782 extract_image_features.cpp:72] Extracting features for 9 batches
E0403 14:30:55.273228 24782 extract_image_features.cpp:108] Extracted features of 50 images.
F0403 14:30:55.804211 24819 video_data_layer.cpp:123] Check failed: read_status Testing must not miss any example

3)mini_batch=1;
E0403 14:31:46.732774 24929 extract_image_features.cpp:72] Extracting features for 1 batches
E0403 14:31:48.042979 24929 extract_image_features.cpp:108] Extracted features of 50 images.
E0403 14:31:48.043027 24929 extract_image_features.cpp:112] Successfully extracted 50 features!

When using mini_batch=1, feature extraction is successfully performed and produce 122 features from 122 clips, rather than 50 clips or 426 clips. 
I am confused with this situation, why?

**Comment by dutran** [comment]
@tzczsq there are many input clips are not available to read.
There are one check at https://github.com/facebook/C3D/blob/master/src/caffe/layers/video_data_layer.cpp#L123 to make sure testing/extracting feature will not miss any example. 

If there is any missing input clip, then the clip list will be no longer aligned with the prefix-list, thus the computed features are no longer correct (mismatch which feature file comes from which input clip).

You just check carefully which clips from your input clip cannot be read by adding to image_io.cpp at line
https://github.com/facebook/C3D/blob/master/src/caffe/util/image_io.cpp#L135
(just before this line) to insert a print out (e.g. LOG(INFO) <<
filename << " " << start_frm) the information of the clip.
