### ISSUE TITLE
HDF5 format

### ISSUE THREAD

**Issue by visionresearcher** [facebook/C3D#103]
Hi,

I'm working to use C3D on volumes which are in HDF5 format. I want to know how should data and labels should be formatted:

I made train_01.lst like this:

input/data/Image000001.h5
input/data/Image000002.h5
input/data/Image000003.h5

where Image000001.h5 consists of data and label where data is [number of frames,1,width,height] and labels is a 1D vector. However it is not able to read the files and stating "Number of files:0"

Thanks

**Comment by dutran** [comment]
@visionresearcher HDF5 is currently not supported in this version. You can implement a new layer for that if needed.
