### ISSUE TITLE
The trained C3D model from Sports1M ported to Keras

### ISSUE THREAD

**Issue by albertomontesg** [facebook/C3D#104]
Hi,

First of all, thank you very much for the contribution with this software for videos dataset. I have found very interesting working with 3D convolution layers.

Currently I am working with Keras and I successfully ported the trained C3D model from Sports1M to the Keras framework. I invite you to take a look to the [gist](https://gist.github.com/albertomontesg/d8b21a179c1e6cca0480ebdf292c34d2) with all the process to achieve it and the link to download the model's weights.

Please feel free to share on your website and promote on your contacts.
Thank you very much,

Alberto

**Comment by dutran** [comment]
@albertomontesg Thank you for your contribution. I think it will be useful for many Keras users.

**Comment by chuckcho** [comment]
Just a note that I have documentation and scripts for C3D for Keras + **Tensorflow** backend at https://github.com/chuckcho/c3d-keras, in the spirit of what @albertomontesg has done for Theano. Thanks to both @albertomontesg and @dutran
