### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by rohitqut** [facebook/C3D#106]
Hi Du,
After frame extraction, I tried to run video file and the first hurdle I faced is "Permission Denied" error. To look into the cause, I found this list.

rohit@rohit-VirtualBox:~/C3D-master/examples/c3d_feature_extraction$ ls
c3d_feature_extraction                   conv3d_deepnetA_sport1m_iter_1900000  output     script
c3d_sport1m_feature_extraction_frm.sh    fb_train16_128_mean.binaryproto       prototxt   sport1m_train16_128_mean.binaryproto
c3d_sport1m_feature_extraction_video.sh  input                                 readme.md

rohit@rohit-VirtualBox:~/C3D-master/examples/c3d_feature_extraction$ ./c3d_sport1m_feature_extraction_video.sh 

prototxt/c3d_sport1m_feature_extractor_video.prototxt: line 1: name:: command not found
prototxt/c3d_sport1m_feature_extractor_video.prototxt: line 2: layers: command not found
prototxt/c3d_sport1m_feature_extractor_video.prototxt: line 3: name:: command not found
prototxt/c3d_sport1m_feature_extractor_video.prototxt: line 4: type:: command not found
prototxt/c3d_sport1m_feature_extractor_video.prototxt: line 5: top:: command not found
prototxt/c3d_sport1m_feature_extractor_video.prototxt: line 6: top:: command not found
prototxt/c3d_sport1m_feature_extractor_video.prototxt: line 7: image_data_param: command not found
prototxt/c3d_sport1m_feature_extractor_video.prototxt: line 8: source:: command not found
prototxt/c3d_sport1m_feature_extractor_video.prototxt: line 9: use_image:: command not found
prototxt/c3d_sport1m_feature_extractor_video.prototxt: line 10: mean_file:: command not found
prototxt/c3d_sport1m_feature_extractor_video.prototxt: line 11: batch_size:: command not found
prototxt/c3d_sport1m_feature_extractor_video.prototxt: line 12: crop_size:: command not found
prototxt/c3d_sport1m_feature_extractor_video.prototxt: line 13: mirror:: command not found
prototxt/c3d_sport1m_feature_extractor_video.prototxt: line 14: show_data:: command not found
prototxt/c3d_sport1m_feature_extractor_video.prototxt: line 15: new_height:: command not found
prototxt/c3d_sport1m_feature_extractor_video.prototxt: line 16: new_width:: command not found
prototxt/c3d_sport1m_feature_extractor_video.prototxt: line 17: new_length:: command not found
prototxt/c3d_sport1m_feature_extractor_video.prototxt: line 18: shuffle:: command not found
prototxt/c3d_sport1m_feature_extractor_video.prototxt: line 19: syntax error near unexpected token `}'
prototxt/c3d_sport1m_feature_extractor_video.prototxt: line 19: `  }'

Kindly suggest!

**Comment by dutran** [comment]
Your prototxt/c3d_sport1m_feature_extractor_video.prototxt has syntax error, look at line 19, you may find some hints. Probably, you modified something and broke the syntax.

**Comment by rohitqut** [comment]
I just changed the GPU = -1 instead of 0 in both 'frm.sh' and 'video.sh'. No other modification done after that. It worked fine for extracting features but next there is "Permission Denied" error showing, once put the video.sh command.

**Comment by rohitqut** [comment]
I just changed the GPU = -1 instead of 0 in both 'frm.sh' and 'video.sh'. No other modification done after that. It worked fine for extracting frames but then"Permission Denied" error showing, after giving the 'sh c3d_sport1m_feature_extraction_video.sh' command.

**Comment by dutran** [comment]
Is this the full log? I don't see anywhere indicates "Permission Denied" except for the title of this post.

**Comment by rohitqut** [comment]
It was there in starting, but now each time showing syntax error which I mentioned before. OK I try to fix this up. Apart from this, from the C3D user guide I was trying to find any information related to 'how we can read the output file and see where the feature extraction using C3D has been done exactly'. 
Do you get it my query?

**Comment by dutran** [comment]
In the user guide, at the end of that section, there is "After extracted C3D features, you can use the provided MATLAB script (read_binary_blob.m ) to read the features for further analysis."

**Comment by rohitqut** [comment]
Thank You!
