### ISSUE TITLE
Warning: the use of 'tmpnam' is dangerous, better use 'mkstemp'

### ISSUE THREAD

**Issue by Michael-Guo** [facebook/C3D#11]
When I execute make test, I get a warning message as follow:

test_data_layer.cpp:(.text._ZN5caffe13DataLayerTestIfEC2Ev[_ZN5caffe13DataLayerTestIfEC5Ev]+0x21): warnning： the use of `tmpnam' is dangerous, better use `mkstemp'

Does it make any bad effects?

**Comment by dutran** [comment]
@Michael-Guo: you can try to compile again with modified math_functions.hpp to see if this is gone.

**Comment by Michael-Guo** [comment]
I try to compile again with the modified math_functions.hpp, but the warning is still extant. So sad! PS: my CUDA is 7.0, my GPU is NVIDIA Quadro K600

**Comment by dutran** [comment]
This is from a test and will not affect the main functions of caffe/C3D. So you can ignore it.

**Comment by Michael-Guo** [comment]
When make runtest, I have 2 disabled tests. 

[----------] Global test environment tear-down
[==========] 397 tests from 70 test cases ran. (395557 ms total)
[  PASSED  ] 397 tests.

  YOU HAVE 2 DISABLED TESTS
Is this normal?

**Comment by dutran** [comment]
This is normal. Good luck with your experiment.
