### ISSUE TITLE
Question about the caffe_pretty_print.proto

### ISSUE THREAD

**Issue by DavieHR** [facebook/C3D#110]
Hi I want to compile the C3D in Windows VS2013, however, when I compile the caffe_pretty_print.proto.I encountered the problem: caffe.proto can not find. Please Do me a favor THX!

**Comment by dutran** [comment]
@DavieHR I haven't compiled C3D or Caffe on Windows, so I am not very sure about your issue. Your error log seems indicating that caffe.proto was not found. It is located in the same directory: https://github.com/facebook/C3D/tree/master/src/caffe/proto

**Comment by DavieHR** [comment]
OK I have done it following your suggestion. THX.
