### ISSUE TITLE
A problem of training

### ISSUE THREAD

**Issue by huashuimu** [facebook/C3D#112]
Excuse me, I got an error when I run the train_ucf101.sh, using the video as the input. And then I got the information below. Do you know what is wrong with it?
![20160426213825](https://cloud.githubusercontent.com/assets/18329056/14820001/3714b46a-0bf7-11e6-879c-174af65ac28e.png)
My input list is like this：
![20160407203414](https://cloud.githubusercontent.com/assets/18329056/14820069/7df4fd0e-0bf7-11e6-9e8e-41972a9cfcbd.png)

**Comment by chuckcho** [comment]
It seems you didn't have `ucf101_train_mean.binaryproto` ready. Check the documentation (https://docs.google.com/document/d/1-QqZ3JHd76JfimY4QKqOojcEaf5g3JS0lNh-FHTxLag/edit) to generate the mean cube, or download it from [my repo](https://github.com/chuckcho/C3D/raw/master/examples/c3d_train_ucf101/ucf101_train_mean.binaryproto).

**Comment by huashuimu** [comment]
@chuckcho thanks, it works now.

**Comment by dutran** [comment]
@chuckcho thanks for your helps. @huashuimu glad to hear it works for you now.
