### ISSUE TITLE
different testing results for test.sh and extracted feautures

### ISSUE THREAD

**Issue by ycliu5037** [facebook/C3D#115]
Hi, 

I used the test.sh to predict my own test data and the clip accuracy is 0.47.

I extracted the features in last fully-connected layer and softmax layer with the same model which test.sh used and the prototxt file for feature extracting is same as in testing.

I saved the features in HDF5 format and used python function numpy.argmax which finds the index of maximum value in the vector.

But the clip accuracy is only 0.0288. Theoretically, the two results should be same.

I have checked that the order of output prefix file is same as the input list and the flag "shuffle" is set  false. The labels in input list file are the original.

Do there possibly exist bugs in the above steps?

Thank you!

**Comment by dutran** [comment]
@ycliu5037 which scripts you used to save the features. The provided tool allows to save features in only binary files. Are you writing some other scripts?

**Comment by ycliu5037** [comment]
@dutran 

My script which extracted features is

GLOG_logtosterr=1 ../../build/tools/extract_image_features.bin extract_feature.prototxt path/to/model 0 1 7999 path/to/output_prefix  prob

After save the features, I use MATLAB to transfer them to HDF5 format. The main part of the script is

data = read_binary_blob(feature_name);
h5create(output/to/path, '/prob');
h5write(output/to/path, data);

read_binary_blob.m is the provided script.

I use python to read the hdf5 data and classify.

f = h5py.File(data, 'r')
d_arr = numpy.array(f['prob'])
if (numpy.argmax(d_arr) == label)

**Comment by dutran** [comment]
If you are sure that shuffle in the data layer is set to false then the last thing you may want to check is make sure the two list (input & prefix) are well aligned.
