### ISSUE TITLE
C3D make error 

### ISSUE THREAD

**Issue by STZhang** [facebook/C3D#116]
Got a make error 

/usr/bin/g++ build/tools/compute_volume_mean_from_list.o build/lib/libcaffe.a -o build/tools/compute_volume_mean_from_list.bin -pthread -fPIC -DNDEBUG -O2 -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -Ibuild/src -I./src -I./include -I/usr/local/cuda/include -I/scail/scratch/u/zhangst/coaction/install/OpenBLAS_lib/include/ -L/usr/local/lib -L/usr/local/lib -L/usr/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -L/scail/scratch/u/zhangst/coaction/install/OpenBLAS_lib/lib -lcudart -lcublas -lcurand -lpthread -lglog -lprotobuf -lleveldb -lsnappy -lboost_system -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lopenblas -Wall
/usr/bin/ld: /usr/local/lib/libhdf5.a(H5PL.c.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [build/tools/compute_volume_mean_from_list.bin] Error 1

Any idea what may caused it? Appreciate the help :)

**Comment by dutran** [comment]
Do you have hdf5 installed? It seens you are missing that.

**Comment by STZhang** [comment]
I've tried to uninstall and reinstall it and still got this error TT.

**Comment by dutran** [comment]
hdf5?

**Comment by STZhang** [comment]
Yep.

**Comment by dutran** [comment]
give anaconda a try.

**Comment by STZhang** [comment]
I'm currently using anaconda now, and tried to reinstall hdf5 by conda install hdf5....

**Comment by dutran** [comment]
which gcc you used. dlclose@@GLIBC_2.2.5 is related to glibc

**Comment by STZhang** [comment]
That's my gcc -v

Using built-in specs.

COLLECT_GCC=gcc

COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper

Target: x86_64-linux-gnu

Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu

Thread model: posix

gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1)

**Comment by dutran** [comment]
Looks fine to me

**Comment by STZhang** [comment]
Any other suggestion for this error?

**Comment by dutran** [comment]
Googling and found these: http://stackoverflow.com/questions/33747874/glfw3-error-dso-missing-from-command-line and http://askubuntu.com/questions/334884/while-compiling-truecrypt-i-get-undefined-reference-to-symbol-dlcloseglibc

Seems you miss libdl

**Comment by STZhang** [comment]
Thank you so much for your help and time!
Found them too, but didn't work on me. I would try to work on checking libdl.
Would update if I fix this

**Comment by STZhang** [comment]
Suggestion.... change a machine to work on.... 
Should be something about libdl.

**Comment by dutran** [comment]
good to hear!
