### ISSUE TITLE
Failed to download c3d_ucf101_finetune_whole_iter_20000 from Dropbox

### ISSUE THREAD

**Issue by futurely** [facebook/C3D#119]
Google Drive might be more stable.

**Comment by dutran** [comment]
@futurely here it is https://drive.google.com/file/d/0Bx-2rTokRAt1bWVqd0kxc2JFa1k/view?usp=sharing let me know when your download is done.

**Comment by futurely** [comment]
The test accuracy is 0.772956 which is similar to the result reported in https://github.com/facebook/C3D/issues/118. It would be simpler to be able to verify the file with md5.
