### ISSUE TITLE
File not found: conv3d_ucf101_test.prototxt

### ISSUE THREAD

**Issue by dungqut** [facebook/C3D#122]
Hi @dutran ,
I am trying to modify ucf101 example and run my own database, but when I run train_ucf101.sh, I am still facing problems like  Check failed: fd != -1 (-1 vs. -1) File not found: conv3d_ucf101_test.prototxt. When I remove three likes in conv3d_ucf101_solver.prototxt:
test_net: "conv3d_ucf101_test.prototxt"
test_iter: 100
test_interval: 1000
It seems to run properly. 

I have 2 questions: 
1. Can I remove three above lines in training phase?
2. How can I put validation in conv3d_ucf101_train.prototxt?
I am really looking for ward to receiving your comments
Regards
Dung

**Comment by dutran** [comment]
I am assuming you trying this examples: https://github.com/facebook/C3D/tree/master/examples/c3d_train_ucf101

If so, the https://github.com/facebook/C3D/blob/master/examples/c3d_train_ucf101/conv3d_ucf101_test.prototxt is provided.

Removing those lines mean you are training only, no testing-on-the-fly.

**Comment by dungqut** [comment]
SO, I understand that it doesnot matter if I remove those lines, when already finishing for training  I will run for test right?
How about second question??
I would like to thank you very much

**Comment by dutran** [comment]
I have answered this question in https://github.com/facebook/C3D/issues/113

**Comment by dungqut** [comment]
@dutran I am sorry, I havenot understand your answer about second question: How can I put validation in conv3d_ucf101_train.prototxt? I did not see you put validation in train net.
I really look forward your answer here??
Thanks you so much

**Comment by dutran** [comment]
1) You need to have a prototxt for it, e.g. conv3d_ucf101_val.prototxt
2) You replace this in the solver file (so it will test on the fly)
3) The test prototxt is used for final evaluation (using test_net).

**Comment by dungqut** [comment]
Thanks @dutran so much
