### ISSUE TITLE
visuliaztion about C3D features?

### ISSUE THREAD

**Issue by Thompshon** [facebook/C3D#123]
Hi, I meet a problem. We know you use the method from visuslizing and understanding convolutional networks to achieve the visualization of C3D models. Now, I don't exzactly understand how to visualize the 3D models using  the method. I only can use the method achieve the visualization about picture. Could you tell me  how to modify the source code realize the visualization of C3D models.

**Comment by dutran** [comment]
This implementation of C3D does not support visualization yet. We may support this int he future version.

**Comment by Thompshon** [comment]
![image](https://cloud.githubusercontent.com/assets/19423412/15632419/1ff888ac-25c3-11e6-9009-27158bc532f4.png)
In the paper that Learning Spatiotemporal Features with 3D Convolutional Networks, we find the Figure4 that visualization of C3D model. Could you tell me how to get the similiar figure4.

**Comment by jiang2764** [comment]
@dutran can you provide some hints/ideas about how to visualize the learned C3D model? I thought you have implemented the deconv3d layer and unpooling3d layer. Can you share ideas/code? I think this is good for us to understand your approach. Thanks.
