### ISSUE TITLE
NAN value of extracted features

### ISSUE THREAD

**Issue by afsanehghasemi** [facebook/C3D#125]
Hi,
I have created C3D model and trying to extract features from the model.
The test phase also was alright, however, when I have extracted features of the first fully connected layer, all the values are NaN.
Here is the log,
extract_image_features.cpp:72] Extracting features for 7 batches
extract_image_features.cpp:108] Extracted features of 50 images.
extract_image_features.cpp:112] Successfully extracted 323 features!

It seems features are extracted properly, but I do not know why all values are NaN!
I have checked the input and prefix file, everything seems fine for me. 

Regards
Afsaneh

**Comment by dutran** [comment]
You may want to turn show_data: 1 to see what your data look like. May be you input all zeros values.
