### ISSUE TITLE
change in ".lst" file

### ISSUE THREAD

**Issue by fahimeh62** [facebook/C3D#126]
@dutran Hi 

I am working on finetuning my new data with C3D. I formed my "lst" file different from you. I mean instead of having sth like this:

/home/user/Documents/output_train_data/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01.avi/ 1 0
/home/user/Documents/output_train_data/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01.avi/ 17 0
/home/user/Documents/output_train_data/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01.avi/ 33 0
/home/user/Documents/output_train_data/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01.avi/ 49 0
/home/user/Documents/output_train_data/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01.avi/ 65 0
/home/user/Documents/output_train_data/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01.avi/ 81 0
/home/user/Documents/output_train_data/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01.avi/ 97 0
**/home/user/Documents/output_train_data/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c02.avi/ 1 0
/home/user/Documents/output_train_data/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c02.avi/ 17 0**

I have sth like this:

/home/user/Documents/train/ 1 0
/home/user/Documents/train/ 17 0
/home/user/Documents/train/ 33 0
/home/user/Documents/train/ 49 0
/home/user/Documents/train/ 65 0
/home/user/Documents/train/ 81 0
/home/user/Documents/train/ 97 0
**/home/user/Documents/train/ 113 0
/home/user/Documents/train/ 129 0
/home/user/Documents/train/ 145 0
/home/user/Documents/train/ 161 0
/home/user/Documents/train/ 177 0**

Could you please tell me if it is alright and does not make any fault?
Thanks a lot.

Fahimeh

**Comment by dutran** [comment]
@fahimeh62 If you choose to use frame inputs, you need to modify the option use_image in your data layer to true.
