### ISSUE TITLE
Script for training on Sports-1M dataset

### ISSUE THREAD

**Issue by mzolfaghari** [facebook/C3D#127]
Hi,

I'm working on extended version of your network and need to train the network on Sports-1M dataset (to get trained model of this dataset on new caffe). 
Could you please provide your script for training on Sports-1M dataset? 

Best,
Mohammadreza Zolfaghari

**Comment by ajdroid** [comment]
Use [this](http://vra.github.io/2016/03/03/c3d-use/) as a helper. Adapt list files etc for sports-1M instead of UCF-101. Do not forget to update fc-8 for Sports-1M classes.

**Comment by mzolfaghari** [comment]
Hi @ajdroid 
Thanks for your reply but problem with Sports-1M dataset is that we should provide a script to download videos online from youtube and feed it to network . It's not possible to download 1 million videos to hard disk and then giving list of videos to network!
That's why I'm requesting help for Sports-1M dataset.
Best,
Mohammadreza Zolfaghari

**Comment by ajdroid** [comment]
@mzolfaghari , training the same architecture on the new caffe will not change parameters (it's just faster because of CUDNN). You should be fine using the pre-trained model.
If however you are planning to train it on a different architecture, you could try using the same convolutional filters and just re train the fully connected layers on a subset of Sports 1M. 
There is some advice [here](http://cs.stanford.edu/people/karpathy/deepvideo/) on how to deal with such a large dataset.

**Comment by mzolfaghari** [comment]
@ajdroid new Caffe has more functionality and performance in term of running time and memory usage, that's why I switched to new Caffe.
I can not load old caffe model into new caffe, therefore I should use the dataset to train network from scratch. To train the network on Sports-1M, it's not feasible to download the dataset to hard disk. 
What's your suggestion to deal with this problem?

**Comment by ajdroid** [comment]
Are you working with [this](https://github.com/chuckcho/video-caffe) version of Caffe?
If you have a couple TB of HDD space, you can download and train the data in splits. Make sure to resize all the frames to your requisite size (`128x171`) and then store.

**Comment by mzolfaghari** [comment]
Yeah, I'm working on [this](https://github.com/chuckcho/video-caffe) version. Do you have Sports-1M trained model for new Caffe?

**Comment by dutran** [comment]
@mzolfaghari We used https://rg3.github.io/youtube-dl/ to download Sports-1M.

**Comment by jiang2764** [comment]
@mzolfaghari have you got the Sports-1M trained model for new Caffe? Can you share it with me? Thanks.

**Comment by mzolfaghari** [comment]
@jiang2764 Yes, I got it. Finally, I converted the old trained model to new Caffe model. In the coming weeks, after submitting the paper on arXiv, I will make the models and code online.

Best,
