### ISSUE TITLE
Permission denied when running make runtest

### ISSUE THREAD

**Issue by angelsrates** [facebook/C3D#128]
Hi all,
I am able to run make all and make test, but when I execute make runtest I get this error:
build/test/test_all.testbin 0 --gtest_shuffle
make: execvp: build/test/test_all.testbin: Permission denied
make: *** [runtest] Error 127

I previously installed Caffe, so I just when for the dependencies.
Could somebody please advise me on that?
I am already executing the commands on sudo su and I tried also:
sudo chmod a+x /build/test/test_all.testbin

Thank you all very much,

**Comment by dutran** [comment]
@angelsrates It looks like the issue came from your local machine settings. It could help if you can remove all and install from scratch.

**Comment by angelsrates** [comment]
Hi @dutran !
Yes, I installed it again on another path and it worked.

Thank you very much!

**Comment by doris1996** [comment]
@angelsrates  I met the same issue today, may I ask some details in your solution?  you mean you install caffe again?

**Comment by angelsrates** [comment]
@doris1996 this was a long time ago, but I think so!
