### ISSUE TITLE
C3D Compilation error while make

### ISSUE THREAD

**Issue by parag24** [facebook/C3D#131]
/usr/bin/g++ build/tools/net_speed_benchmark.o build/lib/libcaffe.a -o build/tools/net_speed_benchmark.bin -pthread -fPIC -DNDEBUG -O2 -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -Ibuild/src -I./src -I./include -I/usr/local/cuda/include -L/usr/local/lib -L/usr/local/lib -L/usr/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -lcudart -lcublas -lcurand -lpthread -lglog -lprotobuf -lleveldb -lsnappy -lboost_system -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lcblas -latlas -Wall
build/lib/libcaffe.a(video_data_layer.o): In function `void* caffe::VideoDataLayerPrefetch<float>(void*)':
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_]+0x8b4): undefined reference to `cv::String::allocate(unsigned long)'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_]+0x8d1): undefined reference to `cv::namedWindow(cv::String const&, int)'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_]+0x8db): undefined reference to `cv::String::deallocate()'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_]+0x961): undefined reference to `cv::String::allocate(unsigned long)'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_]+0x981): undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_]+0x989): undefined reference to `cv::String::deallocate()'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_]+0xdfc): undefined reference to `cv::String::deallocate()'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_]+0xeb7): undefined reference to `cv::String::deallocate()'
build/lib/libcaffe.a(video_data_layer.o): In function `void* caffe::VideoDataLayerPrefetch<double>(void*)':
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_]+0x8ec): undefined reference to `cv::String::allocate(unsigned long)'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_]+0x909): undefined reference to `cv::namedWindow(cv::String const&, int)'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_]+0x913): undefined reference to `cv::String::deallocate()'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_]+0x999): undefined reference to `cv::String::allocate(unsigned long)'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_]+0x9b9): undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_]+0x9c1): undefined reference to `cv::String::deallocate()'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_]+0xe45): undefined reference to `cv::String::deallocate()'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_]+0xf00): undefined reference to `cv::String::deallocate()'
build/lib/libcaffe.a(volume_data_layer.o): In function `void* caffe::VolumeDataLayerPrefetch<float>(void*)':
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_]+0x6ee): undefined reference to `cv::String::allocate(unsigned long)'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_]+0x70b): undefined reference to `cv::namedWindow(cv::String const&, int)'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_]+0x715): undefined reference to `cv::String::deallocate()'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_]+0x79b): undefined reference to `cv::String::allocate(unsigned long)'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_]+0x7bb): undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_]+0x7c3): undefined reference to `cv::String::deallocate()'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_]+0x9b6): undefined reference to `cv::String::deallocate()'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_]+0xa88): undefined reference to `cv::String::deallocate()'
build/lib/libcaffe.a(volume_data_layer.o): In function `void* caffe::VolumeDataLayerPrefetch<double>(void*)':
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_]+0x6ee): undefined reference to `cv::String::allocate(unsigned long)'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_]+0x70b): undefined reference to `cv::namedWindow(cv::String const&, int)'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_]+0x715): undefined reference to `cv::String::deallocate()'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_]+0x79b): undefined reference to `cv::String::allocate(unsigned long)'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_]+0x7bb): undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_]+0x7c3): undefined reference to `cv::String::deallocate()'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_]+0x9b6): undefined reference to `cv::String::deallocate()'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_]+0xa88): undefined reference to `cv::String::deallocate()'
build/lib/libcaffe.a(window_data_layer.o): In function `void* caffe::WindowDataLayerPrefetch<float>(void*)':
window_data_layer.cpp:(.text._ZN5caffe23WindowDataLayerPrefetchIfEEPvS1_[_ZN5caffe23WindowDataLayerPrefetchIfEEPvS1_]+0x359): undefined reference to `cv::imread(cv::String const&, int)'
window_data_layer.cpp:(.text._ZN5caffe23WindowDataLayerPrefetchIfEEPvS1_[_ZN5caffe23WindowDataLayerPrefetchIfEEPvS1_]+0x361): undefined reference to `cv::String::deallocate()'
window_data_layer.cpp:(.text._ZN5caffe23WindowDataLayerPrefetchIfEEPvS1_[_ZN5caffe23WindowDataLayerPrefetchIfEEPvS1_]+0xae6): undefined reference to `cv::String::allocate(unsigned long)'
window_data_layer.cpp:(.text._ZN5caffe23WindowDataLayerPrefetchIfEEPvS1_[_ZN5caffe23WindowDataLayerPrefetchIfEEPvS1_]+0x113f): undefined reference to `cv::String::deallocate()'
build/lib/libcaffe.a(window_data_layer.o): In function `void* caffe::WindowDataLayerPrefetch<double>(void*)':
window_data_layer.cpp:(.text._ZN5caffe23WindowDataLayerPrefetchIdEEPvS1_[_ZN5caffe23WindowDataLayerPrefetchIdEEPvS1_]+0x36e): undefined reference to `cv::imread(cv::String const&, int)'
window_data_layer.cpp:(.text._ZN5caffe23WindowDataLayerPrefetchIdEEPvS1_[_ZN5caffe23WindowDataLayerPrefetchIdEEPvS1_]+0x376): undefined reference to `cv::String::deallocate()'
window_data_layer.cpp:(.text._ZN5caffe23WindowDataLayerPrefetchIdEEPvS1_[_ZN5caffe23WindowDataLayerPrefetchIdEEPvS1_]+0xb26): undefined reference to `cv::String::allocate(unsigned long)'
window_data_layer.cpp:(.text._ZN5caffe23WindowDataLayerPrefetchIdEEPvS1_[_ZN5caffe23WindowDataLayerPrefetchIdEEPvS1_]+0x10c6): undefined reference to `cv::String::deallocate()'
build/lib/libcaffe.a(io.o): In function `caffe::ReadImageToDatum(std::string const&, int, int, int, caffe::Datum*)':
io.cpp:(.text+0x5ac): undefined reference to `cv::imread(cv::String const&, int)'
io.cpp:(.text+0x7b8): undefined reference to `cv::String::deallocate()'
io.cpp:(.text+0xa1d): undefined reference to `cv::imread(cv::String const&, int)'
io.cpp:(.text+0xa25): undefined reference to `cv::String::deallocate()'
io.cpp:(.text+0xbc7): undefined reference to `cv::String::allocate(unsigned long)'
io.cpp:(.text+0xbe5): undefined reference to `cv::String::allocate(unsigned long)'
io.cpp:(.text+0xd53): undefined reference to `cv::String::deallocate()'
io.cpp:(.text+0xd70): undefined reference to `cv::String::deallocate()'
build/lib/libcaffe.a(image_io.o): In function `caffe::ReadImageSequenceToVolumeDatum(char const*, int, int, int, int, int, int, caffe::VolumeDatum*)':
image_io.cpp:(.text+0x674): undefined reference to `cv::String::allocate(unsigned long)'
image_io.cpp:(.text+0x694): undefined reference to `cv::imread(cv::String const&, int)'
image_io.cpp:(.text+0x8a6): undefined reference to `cv::String::deallocate()'
image_io.cpp:(.text+0xae7): undefined reference to `cv::String::allocate(unsigned long)'
image_io.cpp:(.text+0xb07): undefined reference to `cv::imread(cv::String const&, int)'
image_io.cpp:(.text+0xd16): undefined reference to `cv::String::deallocate()'
image_io.cpp:(.text+0x1090): undefined reference to `cv::String::deallocate()'
image_io.cpp:(.text+0x10b1): undefined reference to `cv::String::deallocate()'
build/lib/libcaffe.a(image_io.o): In function `caffe::ReadVideoToVolumeDatum(char const*, int, int, int, int, int, int, caffe::VolumeDatum*)':
image_io.cpp:(.text+0x1aa1): undefined reference to `cv::String::allocate(unsigned long)'
image_io.cpp:(.text+0x1abe): undefined reference to `cv::VideoCapture::open(cv::String const&)'
image_io.cpp:(.text+0x1ac6): undefined reference to `cv::String::deallocate()'
image_io.cpp:(.text+0x1d22): undefined reference to `cv::VideoCapture::get(int) const'
image_io.cpp:(.text+0x1e35): undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
image_io.cpp:(.text+0x1fc3): undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
image_io.cpp:(.text+0x23bb): undefined reference to `cv::String::deallocate()'
collect2: error: ld returned 1 exit status
make: *** [build/tools/net_speed_benchmark.bin] Error 1
user@user-pc:~/C3D-master$ LIBS=-ldl make
/usr/bin/g++ build/tools/net_speed_benchmark.o build/lib/libcaffe.a -o build/tools/net_speed_benchmark.bin -pthread -fPIC -DNDEBUG -O2 -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -Ibuild/src -I./src -I./include -I/usr/local/cuda/include -L/usr/local/lib -L/usr/local/lib -L/usr/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -lcudart -lcublas -lcurand -lpthread -lglog -lprotobuf -lleveldb -lsnappy -lboost_system -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lcblas -latlas -Wall
build/lib/libcaffe.a(video_data_layer.o): In function `void* caffe::VideoDataLayerPrefetch<float>(void*)':
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_]+0x8b4): undefined reference to `cv::String::allocate(unsigned long)'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_]+0x8d1): undefined reference to `cv::namedWindow(cv::String const&, int)'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_]+0x8db): undefined reference to `cv::String::deallocate()'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_]+0x961): undefined reference to `cv::String::allocate(unsigned long)'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_]+0x981): undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_]+0x989): undefined reference to `cv::String::deallocate()'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_]+0xdfc): undefined reference to `cv::String::deallocate()'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIfEEPvS1_]+0xeb7): undefined reference to `cv::String::deallocate()'
build/lib/libcaffe.a(video_data_layer.o): In function `void* caffe::VideoDataLayerPrefetch<double>(void*)':
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_]+0x8ec): undefined reference to `cv::String::allocate(unsigned long)'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_]+0x909): undefined reference to `cv::namedWindow(cv::String const&, int)'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_]+0x913): undefined reference to `cv::String::deallocate()'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_]+0x999): undefined reference to `cv::String::allocate(unsigned long)'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_]+0x9b9): undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_]+0x9c1): undefined reference to `cv::String::deallocate()'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_]+0xe45): undefined reference to `cv::String::deallocate()'
video_data_layer.cpp:(.text._ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_[_ZN5caffe22VideoDataLayerPrefetchIdEEPvS1_]+0xf00): undefined reference to `cv::String::deallocate()'
build/lib/libcaffe.a(volume_data_layer.o): In function `void* caffe::VolumeDataLayerPrefetch<float>(void*)':
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_]+0x6ee): undefined reference to `cv::String::allocate(unsigned long)'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_]+0x70b): undefined reference to `cv::namedWindow(cv::String const&, int)'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_]+0x715): undefined reference to `cv::String::deallocate()'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_]+0x79b): undefined reference to `cv::String::allocate(unsigned long)'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_]+0x7bb): undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_]+0x7c3): undefined reference to `cv::String::deallocate()'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_]+0x9b6): undefined reference to `cv::String::deallocate()'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIfEEPvS1_]+0xa88): undefined reference to `cv::String::deallocate()'
build/lib/libcaffe.a(volume_data_layer.o): In function `void* caffe::VolumeDataLayerPrefetch<double>(void*)':
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_]+0x6ee): undefined reference to `cv::String::allocate(unsigned long)'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_]+0x70b): undefined reference to `cv::namedWindow(cv::String const&, int)'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_]+0x715): undefined reference to `cv::String::deallocate()'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_]+0x79b): undefined reference to `cv::String::allocate(unsigned long)'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_]+0x7bb): undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_]+0x7c3): undefined reference to `cv::String::deallocate()'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_]+0x9b6): undefined reference to `cv::String::deallocate()'
volume_data_layer.cpp:(.text._ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_[_ZN5caffe23VolumeDataLayerPrefetchIdEEPvS1_]+0xa88): undefined reference to `cv::String::deallocate()'
build/lib/libcaffe.a(window_data_layer.o): In function `void* caffe::WindowDataLayerPrefetch<float>(void*)':
window_data_layer.cpp:(.text._ZN5caffe23WindowDataLayerPrefetchIfEEPvS1_[_ZN5caffe23WindowDataLayerPrefetchIfEEPvS1_]+0x359): undefined reference to `cv::imread(cv::String const&, int)'
window_data_layer.cpp:(.text._ZN5caffe23WindowDataLayerPrefetchIfEEPvS1_[_ZN5caffe23WindowDataLayerPrefetchIfEEPvS1_]+0x361): undefined reference to `cv::String::deallocate()'
window_data_layer.cpp:(.text._ZN5caffe23WindowDataLayerPrefetchIfEEPvS1_[_ZN5caffe23WindowDataLayerPrefetchIfEEPvS1_]+0xae6): undefined reference to `cv::String::allocate(unsigned long)'
window_data_layer.cpp:(.text._ZN5caffe23WindowDataLayerPrefetchIfEEPvS1_[_ZN5caffe23WindowDataLayerPrefetchIfEEPvS1_]+0x113f): undefined reference to `cv::String::deallocate()'
build/lib/libcaffe.a(window_data_layer.o): In function `void* caffe::WindowDataLayerPrefetch<double>(void*)':
window_data_layer.cpp:(.text._ZN5caffe23WindowDataLayerPrefetchIdEEPvS1_[_ZN5caffe23WindowDataLayerPrefetchIdEEPvS1_]+0x36e): undefined reference to `cv::imread(cv::String const&, int)'
window_data_layer.cpp:(.text._ZN5caffe23WindowDataLayerPrefetchIdEEPvS1_[_ZN5caffe23WindowDataLayerPrefetchIdEEPvS1_]+0x376): undefined reference to `cv::String::deallocate()'
window_data_layer.cpp:(.text._ZN5caffe23WindowDataLayerPrefetchIdEEPvS1_[_ZN5caffe23WindowDataLayerPrefetchIdEEPvS1_]+0xb26): undefined reference to `cv::String::allocate(unsigned long)'
window_data_layer.cpp:(.text._ZN5caffe23WindowDataLayerPrefetchIdEEPvS1_[_ZN5caffe23WindowDataLayerPrefetchIdEEPvS1_]+0x10c6): undefined reference to `cv::String::deallocate()'
build/lib/libcaffe.a(io.o): In function `caffe::ReadImageToDatum(std::string const&, int, int, int, caffe::Datum*)':
io.cpp:(.text+0x5ac): undefined reference to `cv::imread(cv::String const&, int)'
io.cpp:(.text+0x7b8): undefined reference to `cv::String::deallocate()'
io.cpp:(.text+0xa1d): undefined reference to `cv::imread(cv::String const&, int)'
io.cpp:(.text+0xa25): undefined reference to `cv::String::deallocate()'
io.cpp:(.text+0xbc7): undefined reference to `cv::String::allocate(unsigned long)'
io.cpp:(.text+0xbe5): undefined reference to `cv::String::allocate(unsigned long)'
io.cpp:(.text+0xd53): undefined reference to `cv::String::deallocate()'
io.cpp:(.text+0xd70): undefined reference to `cv::String::deallocate()'
build/lib/libcaffe.a(image_io.o): In function `caffe::ReadImageSequenceToVolumeDatum(char const*, int, int, int, int, int, int, caffe::VolumeDatum*)':
image_io.cpp:(.text+0x674): undefined reference to `cv::String::allocate(unsigned long)'
image_io.cpp:(.text+0x694): undefined reference to `cv::imread(cv::String const&, int)'
image_io.cpp:(.text+0x8a6): undefined reference to `cv::String::deallocate()'
image_io.cpp:(.text+0xae7): undefined reference to `cv::String::allocate(unsigned long)'
image_io.cpp:(.text+0xb07): undefined reference to `cv::imread(cv::String const&, int)'
image_io.cpp:(.text+0xd16): undefined reference to `cv::String::deallocate()'
image_io.cpp:(.text+0x1090): undefined reference to `cv::String::deallocate()'
image_io.cpp:(.text+0x10b1): undefined reference to `cv::String::deallocate()'
build/lib/libcaffe.a(image_io.o): In function `caffe::ReadVideoToVolumeDatum(char const*, int, int, int, int, int, int, caffe::VolumeDatum*)':
image_io.cpp:(.text+0x1aa1): undefined reference to `cv::String::allocate(unsigned long)'
image_io.cpp:(.text+0x1abe): undefined reference to `cv::VideoCapture::open(cv::String const&)'
image_io.cpp:(.text+0x1ac6): undefined reference to `cv::String::deallocate()'
image_io.cpp:(.text+0x1d22): undefined reference to `cv::VideoCapture::get(int) const'
image_io.cpp:(.text+0x1e35): undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
image_io.cpp:(.text+0x1fc3): undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
image_io.cpp:(.text+0x23bb): undefined reference to `cv::String::deallocate()'
collect2: error: ld returned 1 exit status
make: *** [build/tools/net_speed_benchmark.bin] Error 1

i have all dependencies but then also it is giving this error. Any help please

**Comment by dutran** [comment]
It looks like you have linking problems with OpenCV

**Comment by dutran** [comment]
Have you got your issue solved, @parag24 ?

**Comment by alidiba67** [comment]
@parag24 you can fix it by adding "opencv_videoio" to LIBRARIES in the Makefile.

**Comment by dutran** [comment]
seems opencv dependencies issue.
