### ISSUE TITLE
 C3D Feature Extraction: Error with frame based model #43 

### ISSUE THREAD

**Issue by rohitqut** [facebook/C3D#132]
Hello,
I have the exact same issue even after all the images are saved in "%06d.jpg".

Here the error looks like
F0622 11:35:55.689235 24543 video_data_layer.cpp:346] Check failed: ReadImageSequenceToVolumeDatum(file_list_[id].c_str(), start_frm_list_[id], label_list_[id], new_length, new_height, new_width, sampling_rate, &datum)

Kindly assist!

**Comment by rohitqut** [comment]
The above mentioned error comes up when I run sh c3d_sport1m_feature_extraction_frm.sh

**Comment by rohitqut** [comment]
Actually, this problem occurs when its reading frames from input/frm/ like below

I0622 11:35:55.688977 24543 video_data_layer.cpp:344] read video from input/frm/Dataset/Train/Train01
F0622 11:35:55.689235 24543 video_data_layer.cpp:346] Check failed: ReadImageSequenceToVolumeDatum(file_list_[id].c_str(), start_frm_list_[id], label_list_[id], new_length, new_height, new_width, sampling_rate, &datum)

**Comment by proact** [comment]
Hi rohitqut!
I'm running into the same issue while finetuning UCF101.
Gonna try finetuning on my dataset, maybe the error will disappear.

**Comment by rohitqut** [comment]
Hi @proact 
Thank you for the response! According to the Du Tran's C3D user guide, we can possibly get the features extracted before going into the finetuning part. That is exactly I am trying to do and came across with this error. Kindly post your suggestion if able to find something!

**Comment by dutran** [comment]
What do you get if you do "ls input/frm/Dataset/Train/Train01"?

**Comment by rohitqut** [comment]
@dutran All images are stored there as '%06d.jpg'. Anyway, that problem is resolved. Please help me with a problem related to mini batch size and number of mini batches inside c3d_sport1m_feature_extraction_frm.sh. While extracting features for my own dataset I set mini batch size as 150 and number of mini batch size as 100 in order to extract about 15000 features, I get error as
Check Failed: read_status Testing must not miss any example. 

If I reverse both data, that is put mini batch size as 100 and number of mini batches as 150, then I could able to extract nearly about 10,000 features only. I could not understand the concept of managing mini batch size and its number properly. 
P.S. (fc6-1,fc7-1, .prob) for each image I am considering as 1 feature.

**Comment by ParitoshParmar** [comment]
@rohitqut : It seems that your batch size of 150 larger as compared to your GPU memory, that's why it's not able to fit. I am not sure why you are getting features for only around 10k images. Please double check the input list and output no.

Concept of managing mini batch no: set batch size according to your available memory and set no. of mini batch so as to meet input nos.

**Comment by dutran** [comment]
@rohitqut I think there is another parameter in the command line where you need to specify you want to extract 150 mini-batches. I saw you only extract 100 mini-batches of 100 clips. I expect when you set the correct number of mini batches. The old problem will come back as there are some clips missing from your data.

Another question for you, how much memory on your GPU, I am curious because K40 with ~12GB can put up to a mini batch of 80 clips, but could not make it to 100.

**Comment by rohitqut** [comment]
@dutran I am using CPU, of memory 6.5 GiB available. I double checked the clips. All clips are available. You have extracted the features for v_applyEyeMakeup_g01_c01 and v_BaseballPitch_g01_c01 only from the whole UCF101 dataset. So, please let me know if you will be extracting features for whole UCF101 dataset at once, what mini batch size and number of mini batches you would be giving?

I have provided the details same as @ParitoshParmar is mentioning but ending up with the same error. "read_status - Testing must not miss any example"

**Comment by dutran** [comment]
@rohitqut in the example, I just provide simple extraction of 2 videos. As far as I know, that error mean data layer cannot read a clip from the list provided.

**Comment by ParitoshParmar** [comment]
@rohitqut I am not sure, but I guess there might be a mismatch between the frame rates used to extract frames using ffmpeg, because of which the feature extractor is not able to find some frames. Are you using the correct frame rates ?
Your problem seems to be similar to solved issue #133

**Comment by rohitqut** [comment]
@dutran Yes, I also thought that the error is arising because of the same reason you mentioned. This problem is not only with training data, its occurring with test data as well where frames are much lesser than the training. I will follow what you suggested in #133 and check the extractions.

@ParitoshParmar No issue with frame rates. Error turns up with smaller number of frames too when I am extracting features for test data.

**Comment by dutran** [comment]
solved in #133
