### ISSUE TITLE
Error in c3d_sport1m_feature_extraction_frm.sh with patch of an image

### ISSUE THREAD

**Issue by rohitqut** [facebook/C3D#133]
Hello,
If I run sh c3d_sport1m_feature_extraction_frm.sh with following details
 batch_size: 10
 crop_size: 18
 mirror: false
 show_data: 0
 new_height: 20
 new_width: 20
 new_length: 16
 shuffle: false

Error is - F0623 11:28:12.422502   546 net.cpp:329] Check failed: target_blobs[j]->num() == source_layer.blobs(j).num() (512 vs. 256) 

And if I change to batch_size:11

Error is - F0623 11:37:21.927311   579 video_data_layer.cpp:123] Check failed: read_status Testing must not miss any example

How to incorporate the batch_size for the patch having size, height:20, width:20?

**Comment by rohitqut** [comment]
Solved by reducing batch size!! Thanks anyway.

**Comment by dutran** [comment]
@rohitqut I think you set new height and new width to 20 and crop size to 18 is weird. Is there any reason to do that? C3D default setting is height=128, width=171, crop=112.

**Comment by rohitqut** [comment]
@dutran I was trying to extract features from very small  input image of size say 20X20. Yes later I realized crop_size is weird. What is your suggestion? Is there any crop_size required for such smaller input images or if so, then approximately what number it could be?

**Comment by dutran** [comment]
Given that you want to extract features for image with 20x20, then you may want to set
new_height: 112
new_width: 112
crop_size: 0

which means you first scale your images from 20x20 to 112x112 (quite aggressive), then use it directly input to C3D network without using center crop because your images are already small (cropping will hurt, rather than help).

**Comment by rohitqut** [comment]
@dutran If I change new_height and new_width from 20 to 112 each, then following error comes up

check failed: data_mean_.height() == datum_height_(20 vs. 112)

**Comment by dutran** [comment]
@rohitqut you need to re-compute your volume mean with 122x122 instead of the old one (e.g. 20 x20)

**Comment by dutran** [comment]
Supposed re-computing mean will solve the issue.
