### ISSUE TITLE
clip-based accuracy or video-based accuracy?

### ISSUE THREAD

**Issue by ruizhaogit** [facebook/C3D#136]
Hi,

for clip-based accuracy, is one clip 16 frames or 1 clip of the ucf 101 video?

I mean in ucf 101, they divided the videos into clips and groups, right?

So, I am little confused now, what does the clip-based accuracy mean?

I finetuned the model on ucf 101, and got this:

E0706 10:09:17.363905 14350 test_net.cpp:51] Batch 836, accuracy: 0.74
E0706 10:09:18.275758 14350 test_net.cpp:51] Batch 837, accuracy: 0.88
E0706 10:09:18.275777 14350 test_net.cpp:54] Test accuracy: 0.799332

Is this 79.93% the accuracy of classification of ucf 101 video clips (like: v_ApplyEyeMakeup_g01_c01.avi) or classificaton of 16 frames clips (like: /UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01/ 17)?

Is there any python script avaliable to calculate the averaged video-based accuracy?

thank you!

best,
Rui

**Comment by dutran** [comment]
This is the clip-based (aka /UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01/ 17)
