### ISSUE TITLE
What should I do to get the labels of the test videos?

### ISSUE THREAD

**Issue by icbcbicc** [facebook/C3D#138]
In order to classify some videos after training, I use ./build/examples/cpp_classification/classification.bin, but it seems that it only supports image input. What should I do to get the labels using videos? 
What's more, I used to use python to do the classification task in the original caffe. Does C3D supports the python interface?
Thanks.

**Comment by dutran** [comment]
C3D does not support classify the whole video yet, but you can use feature extraction to extract "prob" for clips then aggregate clip predictions to make video predictions. It is supposed to be easily implemented by python or matlab.
