### ISSUE TITLE
How to use C3D features

### ISSUE THREAD

**Issue by Michael-Guo** [facebook/C3D#14]
Dear dutran
I have successfully run the c3d_feature_extraction examle, so I get some output files such as 000001.fc6-1 000001.fc7-1 and 000001.prob. How can I read features from these files. I couldn't open these files directly with double click.
Thanks!

**Comment by dutran** [comment]
@Michael-Guo you can use the provided MATLAB script (https://github.com/facebook/C3D/blob/master/examples/c3d_feature_extraction/script/read_binary_blob.m) to read the feature files.
