### ISSUE TITLE
How to provide 2 input files to VideoData layer for a siamese network ?

### ISSUE THREAD

**Issue by ParitoshParmar** [facebook/C3D#140]
I want to implement a siamese network but with VideoData. So, how can I specify the pair of input clips in the input_list.txt ?

**Comment by dutran** [comment]
You are supposed to write another data layer and a triplet loss layer.

**Comment by ParitoshParmar** [comment]
@dutran For faster prototyping, do you suggest that I use multiple data layers but Shuffle set to OFF ?
