### ISSUE TITLE
Computing Mean Volume

### ISSUE THREAD

**Issue by ParitoshParmar** [facebook/C3D#141]
I am trying to compute mean volume. I have tried with both video list as input and image list as input. It says that it has processed all the files but the output is only 10 bytes compared to 4.2MB of the reference mean_volume. So, clearly, it is not computing the mean volume. 

In #30, it is mentioned that the issue might be stemming from OpenCV or relative path. But I can extract features using the same list.

So, what could be the potential problem ?

Thank you

**Comment by dutran** [comment]
What the command line you used to generate the mean file. May be you did not specify the arguments correctly.

**Comment by ParitoshParmar** [comment]
Commandline used by me (arguments on separate lines just for better viewing):
build/tools/compute_volume_mean_from_list.bin 
/home/paritosh/Folder/vc/examples/c3d_ucf101/mean_vol.txt 
16 
128 
171 
1 
/home/paritosh/Folder/vc/examples/c3d_ucf101/mean_new.binaryproto 

It says:
E0803 11:47:15.270251 12379 compute_volume_mean_from_list.cpp:106] Processed 10000 files.
E0803 11:47:15.339315 12379 compute_volume_mean_from_list.cpp:112] Processed 16599 files.

But the output is just 10 bytes. Am I doing something wrong ?

**Comment by ParitoshParmar** [comment]
@dutran Can you please tell me if I need to use some particular image naming convention ? I think image loader may not be able to load images because of my wrong naming convention.

**Comment by ParitoshParmar** [comment]
Yes, you are using following format: %06d.jpg and I was using image_%04d.jpg, which is why it was not able to load images.
