### ISSUE TITLE
volume data layer .cpp

### ISSUE THREAD

**Issue by yufengwhy** [facebook/C3D#142]
hi,

how to generate 4D lmdb/levedb for input of volume data layer .cpp?

i have 3D volume data with width, height, length, (channel=1), what is a better way to use C3D with    volume data layer .cpp?

best wishes

rookie

**Comment by dutran** [comment]
Yes, you suppose to use this layer (https://github.com/facebook/C3D/blob/master/src/caffe/layers/volume_data_layer.cpp), you can refer to this example (https://github.com/facebook/C3D/blob/master/examples/cifar10/convert_cifar_data.cpp) to write your converting function. There are some different between Datum vs. VolumeDatum, but the rest is almost the same.

**Comment by yufengwhy** [comment]
hi,

i may not make myself clear. 

i want use 3D CNN with 3D volume data with width, height, length, (channel=1), so i choose the layer (https://github.com/facebook/C3D/blob/master/src/caffe/layers/volume_data_layer.cpp). But this layer require inputs of 4D lmdb/levedb. 

i know how to generate  3D  lmdb/levedb, but it seems trouble to generate 4D  lmdb/levedb for constraints of googleblob.

Could this layer be degenerated to receive a 3D inputs with width, height, length, (channel=1) and how to change others correspondingly? 

best wishes

rookie
