### ISSUE TITLE
Library 'gflags' missing in Makefile

### ISSUE THREAD

**Issue by PENGUINLIONG** [facebook/C3D#143]
In `Makefile`, I've got:
```
LIBRARIES := cudart cublas curand \
	pthread \
	glog protobuf leveldb snappy \
	boost_system \
	hdf5_hl hdf5 \
	opencv_core opencv_highgui opencv_imgproc#\
	#mat mx
```

When I run make to build the project, I got many such error:
```
logging.cc:(.text+0x6944): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
```

The original caffe also depends on gflags, so I consider that `gflags` should be added. And actually the build passed after the addition.

**Comment by dutran** [comment]
May be there some different version setting. Makefile runs fine on my machine.
