### ISSUE TITLE
Check failed: ReadImageSequenceToVolumeDatum(file_list_[id].c_str(), start_frm_list_[id], label_list_[id], new_length, new_height, new_width, sampling_rate, &datum)

### ISSUE THREAD

**Issue by moyans** [facebook/C3D#145]
When I tried to run_ucf101.sh, I got an error message below.Anyone could be so kind to help me ? @daaku 
log:
I0811 18:14:12.801676 10132 video_data_layer.cpp:283] Opening file ../c3d_finetuning/train_01.lst
I0811 18:14:12.903743 10132 video_data_layer.cpp:312] Shuffling data
I0811 18:14:13.252450 10132 video_data_layer.cpp:317] A total of 107258 video chunks.
I0811 18:14:13.252504 10132 video_data_layer.cpp:344] read video from /media/moyan/c0d34b51-8a78-4364-bc19-35003bf01885/DataSet/UCF-101/JumpingJack/v_JumpingJack_g25_c05.avi
F0811 18:14:13.252557 10132 video_data_layer.cpp:346] Check failed: ReadImageSequenceToVolumeDatum(file_list_[id].c_str(), start_frm_list_[id], label_list_[id], new_length, new_height, new_width, sampling_rate, &datum) 
*** Check failure stack trace: ***
    @     0x7f863b8e09fd  google::LogMessage::Fail()
    @     0x7f863b8e289d  google::LogMessage::SendToLog()
    @     0x7f863b8e05ec  google::LogMessage::Flush()
    @     0x7f863b8e31be  google::LogMessageFatal::~LogMessageFatal()
    @           0x4bca03  caffe::VideoDataLayer<>::SetUp()
    @           0x4578e5  caffe::Net<>::Init()
    @           0x458b95  caffe::Net<>::Net()
    @           0x433adf  caffe::Solver<>::Init()
    @           0x4371eb  caffe::Solver<>::Solver()
    @           0x40b416  main
    @     0x7f8637471f45  (unknown)
    @           0x40e10e  (unknown)
Aborted (core dumped)
and I run:
moyan@moyans:/media/moyan/c0d34b51-8a78-4364-bc19-35003bf01885/moyan_caffe/C3D/examples/c3d_train_ucf101$ ls  /media/moyan/c0d34b51-8a78-4364-bc19-35003bf01885/DataSet/UCF-101/JumpingJack/v_JumpingJack_g25_c05.avi
/media/moyan/c0d34b51-8a78-4364-bc19-35003bf01885/DataSet/UCF-101/JumpingJack/v_JumpingJack_g25_c05.avi

Could you please help?
Best

**Comment by ParitoshParmar** [comment]
@moyans If I understand correctly, then you are giving in video file instead of images, aren't you ?

**Comment by dutran** [comment]
@moyans you used video, then the option in video_data layer use_image should set to false.

**Comment by deepaksharma36** [comment]
I am trying to train it with videos and in C3D/src/caffe/layers/video_data_layer.cpp I set: 
(line 66)	  const bool use_image = false;//layer->layer_param_.image_data_param().use_image();
Then I also did make clean , make all and make test.
But I am still getting  the same error. 
Did I make the required change in a wrong file ??

**Comment by sophiazy** [comment]
@moyans I encounter the same question with you ,have you solve the problem?

**Comment by egg347** [comment]
@sophiazy Me too! What did you do to solve it?

**Comment by egg347** [comment]
@ParitoshParmar @dutran  I used images as input and encountered the same problem ,could you please help me to fix it? Should I adjust input layer's layer type to "ImageData" and adjust the list file in *.prototxt as I do on other normal caffe programs?
