### ISSUE TITLE
Generating data for V2V examples

### ISSUE THREAD

**Issue by ltnghia** [facebook/C3D#146]
Hello,

I try to run examples for V2V but I don't know how to create data for VIDEO_SEGMENTATION_DATA and VIDEO_WITH_VOXEL_TRUTH_DATA. Can you show me how to generate binary data as in "C3D/examples/v2v/video_segmentation_gatech/cross_validation_bin_list_scaled.txt"?

Thank you in advance.

**Comment by dutran** [comment]
@ltnghia you can try this https://www.dropbox.com/s/wjwgihcqhcq9zkn/do_prepare_gatech_segmentation_binary.m?dl=0
