### ISSUE TITLE
test_01.lst for finetuning C3D with frames

### ISSUE THREAD

**Issue by achalddave** [facebook/C3D#148]
Hi,

I downloaded the UCF101 videos, and I'm finding that some videos have fewer frames than expected by the [test_01.lst](https://github.com/facebook/C3D/blob/249ab8453be4b213e1068412e290b355997b68d2/examples/c3d_finetuning/test_01.lst).

For example, `v_ApplyLipstick_g02_c01.avi` has 127 frames according to ffprobe:

```
ffprobe -v error -count_frames -select_streams v:0 -show_entries stream=nb_read_frames /data/all/UCF101/v_ApplyLipstick_g02_c01.avi </dev/null
[STREAM]
nb_read_frames=127
[/STREAM]
```

But `test_01.lst` attempts to access 16 frames starting at `113` (line 529 [here](https://raw.githubusercontent.com/facebook/C3D/249ab8453be4b213e1068412e290b355997b68d2/examples/c3d_finetuning/test_01.lst)), which would require frame `128 (= 113 + 15)` to be a valid frame.

I can fix this by just removing the offending lines in `test_01.lst`, but I want to make sure I'm not missing anything, or making any mistakes.

Thanks!

**Comment by achalddave** [comment]
Here's a diff of the lines I removed: https://gist.github.com/achalddave/6085c84be479246cf382d468dca3c3c0

**Comment by dutran** [comment]
@achalddave different decoders can give lightly difference in term of number of frames, so that is expected.
