### ISSUE TITLE
feature dimensions on fc6

### ISSUE THREAD

**Issue by LiliMeng** [facebook/C3D#150]
Hi,
 
     Thanks a lot for providing the good paper and code! The code could compile successfully!

     After extracting the video descriptor, the dimension in fc6 is 16404, but the paper said that it shall be 4096. 

     Any suggestions? 
     Highly appreciate your time and help!

**Comment by qinhaifangpku** [comment]
hi~i want to know how you install it, and look at the other issue, if you have use the latest version of caffe?

**Comment by dutran** [comment]
@LiliMeng this does not seem right.
@qinhaifangpku can you follow the User Guide, that should work

**Comment by qinhaifangpku** [comment]
@dutran  thank you for your concern~  i have followed the guide and it work. 
and i want to know that if i should use the latest version caffe as issue #87 mentioned, i am new to caffe, and did not know the differences of it. and i looked at the #87 that someone have merged your work into new version caffe, but in its issue it may have many problems when install it. so i did not use it. i install the one you have down. and i found that it work in your examples.

**Comment by qinhaifangpku** [comment]
@dutran  hi~ i also want to know the data type you support to load is what? because i am working on voxel data now, it is not a video, i wonder what type should i prepare for the training and testing.

**Comment by qinhaifangpku** [comment]
@dutran thank you in advance!

**Comment by dutran** [comment]
@qinhaifangpku i did not test #87, so I am not sure if it is equivalent.
We supports a couple of data layers, for you voxel data layers, you can refer to our V2V model.
