### ISSUE TITLE
"C3D User Guide" not find

### ISSUE THREAD

**Issue by QinZiwen** [facebook/C3D#151]
I want visit the C3D User Guide(https://goo.gl/k2SnLY), but the page not find. There have another address for user, tell me please, thank you!

**Comment by dutran** [comment]
https://docs.google.com/document/d/1-QqZ3JHd76JfimY4QKqOojcEaf5g3JS0lNh-FHTxLag

**Comment by QinZiwen** [comment]
@dutran Thank you very much!
