### ISSUE TITLE
run "sh c3d_sport1m_feature_extraction_frm.sh"

### ISSUE THREAD

**Issue by weizhou-geek** [facebook/C3D#153]
line 7: ../../build/tools/extract_image_features.bin: No such file or director

**Comment by dutran** [comment]
@weizhou-geek look likes you haven't compiled C3D successfully.

**Comment by weizhou-geek** [comment]
hi, I just follow the user guide in the first step "Run sh c3d_sport1m_feature_extraction_frm.sh". But it seems like that the file extract_image_feature.bin doesn't exist?
