### ISSUE TITLE
Test failure in MathFunctionsTest (TestSgnbitCPU)

### ISSUE THREAD

**Issue by ltnghia** [facebook/C3D#154]
Thanks a lot for sharing the code. I managed to compile the code on my PC with GeForce GTX1080 GPU with Ubuntu 16.04 and CUDA 8.0. However, make runtest produced a test failure in MathFunctionsTest (TestSgnbitCPU):

```
src/caffe/test/test_math_functions.cpp:146: Failure
Value of: x[i] < 0 ? 1 : 0
Actual: 1
Expected: signbits[i]
Which is: -2.14748e+09
[  FAILED  ] MathFunctionsTest/0.TestSgnbitCPU, where TypeParam = float (1107 ms)
```
---

```
[----------] Global test environment tear-down
[==========] 427 tests from 76 test cases ran. (6997050 ms total)
[  PASSED  ] 426 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] MathFunctionsTest/0.TestSgnbitCPU, where TypeParam = float
```

Can you help me with this problem?
Thank you in advance.

**Comment by dutran** [comment]
Your issue looks like #152 where I think mainly due to the GPU.

**Comment by nborkar45** [comment]
I'm having this same problem, any solutions?
I couldn't make out which solution in #152  to follow. Could you be more specific?

**Comment by dutran** [comment]
I run it on CUDA 7.5. Here what I get
./build/test/test_math_functions.testbin
Cuda number of devices: 2
Current device id: 0
[==========] Running 28 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 14 tests from MathFunctionsTest/0, where TypeParam = float
[ RUN      ] MathFunctionsTest/0.TestNothing
[       OK ] MathFunctionsTest/0.TestNothing (535 ms)
[ RUN      ] MathFunctionsTest/0.TestHammingDistanceCPU
[       OK ] MathFunctionsTest/0.TestHammingDistanceCPU (9 ms)
[ RUN      ] MathFunctionsTest/0.TestAsumCPU
[       OK ] MathFunctionsTest/0.TestAsumCPU (8 ms)
[ RUN      ] MathFunctionsTest/0.TestAsumGPU
[       OK ] MathFunctionsTest/0.TestAsumGPU (16 ms)
[ RUN      ] MathFunctionsTest/0.TestSignCPU
[       OK ] MathFunctionsTest/0.TestSignCPU (8 ms)
[ RUN      ] MathFunctionsTest/0.TestSignGPU
[       OK ] MathFunctionsTest/0.TestSignGPU (10 ms)
[ RUN      ] MathFunctionsTest/0.TestSgnbitCPU
[       OK ] MathFunctionsTest/0.TestSgnbitCPU (8 ms)
[ RUN      ] MathFunctionsTest/0.TestSgnbitGPU
[       OK ] MathFunctionsTest/0.TestSgnbitGPU (9 ms)
[ RUN      ] MathFunctionsTest/0.TestFabsCPU
[       OK ] MathFunctionsTest/0.TestFabsCPU (8 ms)
[ RUN      ] MathFunctionsTest/0.TestFabsGPU
[       OK ] MathFunctionsTest/0.TestFabsGPU (12 ms)
[ RUN      ] MathFunctionsTest/0.TestScaleCPU
[       OK ] MathFunctionsTest/0.TestScaleCPU (8 ms)
[ RUN      ] MathFunctionsTest/0.TestScaleGPU
[       OK ] MathFunctionsTest/0.TestScaleGPU (10 ms)
[ RUN      ] MathFunctionsTest/0.TestCopyCPU
[       OK ] MathFunctionsTest/0.TestCopyCPU (7 ms)
[ RUN      ] MathFunctionsTest/0.TestCopyGPU
[       OK ] MathFunctionsTest/0.TestCopyGPU (10 ms)
[----------] 14 tests from MathFunctionsTest/0 (658 ms total)

[----------] 14 tests from MathFunctionsTest/1, where TypeParam = double
[ RUN      ] MathFunctionsTest/1.TestNothing
[       OK ] MathFunctionsTest/1.TestNothing (12 ms)
[ RUN      ] MathFunctionsTest/1.TestHammingDistanceCPU
[       OK ] MathFunctionsTest/1.TestHammingDistanceCPU (14 ms)
[ RUN      ] MathFunctionsTest/1.TestAsumCPU
[       OK ] MathFunctionsTest/1.TestAsumCPU (11 ms)
[ RUN      ] MathFunctionsTest/1.TestAsumGPU
[       OK ] MathFunctionsTest/1.TestAsumGPU (13 ms)
[ RUN      ] MathFunctionsTest/1.TestSignCPU
[       OK ] MathFunctionsTest/1.TestSignCPU (13 ms)
[ RUN      ] MathFunctionsTest/1.TestSignGPU
[       OK ] MathFunctionsTest/1.TestSignGPU (15 ms)
[ RUN      ] MathFunctionsTest/1.TestSgnbitCPU
[       OK ] MathFunctionsTest/1.TestSgnbitCPU (12 ms)
[ RUN      ] MathFunctionsTest/1.TestSgnbitGPU
[       OK ] MathFunctionsTest/1.TestSgnbitGPU (16 ms)
[ RUN      ] MathFunctionsTest/1.TestFabsCPU
[       OK ] MathFunctionsTest/1.TestFabsCPU (12 ms)
[ RUN      ] MathFunctionsTest/1.TestFabsGPU
[       OK ] MathFunctionsTest/1.TestFabsGPU (15 ms)
[ RUN      ] MathFunctionsTest/1.TestScaleCPU
[       OK ] MathFunctionsTest/1.TestScaleCPU (12 ms)
[ RUN      ] MathFunctionsTest/1.TestScaleGPU
[       OK ] MathFunctionsTest/1.TestScaleGPU (15 ms)
[ RUN      ] MathFunctionsTest/1.TestCopyCPU
[       OK ] MathFunctionsTest/1.TestCopyCPU (12 ms)
[ RUN      ] MathFunctionsTest/1.TestCopyGPU
[       OK ] MathFunctionsTest/1.TestCopyGPU (15 ms)
[----------] 14 tests from MathFunctionsTest/1 (187 ms total)

[----------] Global test environment tear-down
[==========] 28 tests from 2 test cases ran. (845 ms total)
[  PASSED  ] 28 tests.

  YOU HAVE 2 DISABLED TESTS

It looks like more like GPU architecture/CUDA issue.

**Comment by nborkar45** [comment]
I'll try to run on cuda 7.5 and let you know about the results

**Comment by deepaksharma36** [comment]
nborkar45, Did you manage to run tests on CUDA8 ?

**Comment by nborkar45** [comment]
No, actually the machine I was working on wasn't mine, and so wasn't allowed to remove any previously installed softwares.
Though I suggest you try https://github.com/chuckcho/video-caffe this for installing cuda.
And if your problem concerns classification on video input you could try using keras library on python.

**Comment by deepaksharma36** [comment]
Thanks nborkar for the suggestion. Actually, I have installed both but right now both are not passing their respective tests. Video caffe has issues with cudnn 5.

**Comment by nborkar45** [comment]
@deepaksharma36 I suggest you take a look at https://www.youtube.com/watch?v=ecbeIRVqD7g , this method to apply convolution neural network on videos
