### ISSUE TITLE
make C3D failure

### ISSUE THREAD

**Issue by weizhou-geek** [facebook/C3D#155]
Hi,
I excuted the following commands but got some errors.

cp Makefile.config.example Makefile.config
make all

/usr/bin/g++ build/tools/convert_imageset.o build/lib/libcaffe.a -o build/tools/convert_imageset.bin -pthread -fPIC -DNDEBUG -O2 -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -Ibuild/src -I./src -I./include -I/usr/local/cuda/include -L/usr/local/lib -L/usr/local/lib -L/usr/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -lcudart -lcublas -lcurand -lpthread -lglog -lprotobuf -lleveldb -lsnappy -lboost_system -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lcblas -latlas -Wall
build/lib/libcaffe.a(image_io.o): In function `caffe::ReadImageSequenceToVolumeDatum(char const*, int, int, int, int, int, int, caffe::VolumeDatum*)':
image_io.cpp:(.text+0x694): undefined reference to `cv::imread(cv::String const&, int)'
image_io.cpp:(.text+0xb07): undefined reference to `cv::imread(cv::String const&, int)'
build/lib/libcaffe.a(image_io.o): In function `caffe::ReadVideoToVolumeDatum(char const*, int, int, int, int, int, int, caffe::VolumeDatum*)':
image_io.cpp:(.text+0x1905): undefined reference to `cv::VideoCapture::VideoCapture()'
image_io.cpp:(.text+0x1abe): undefined reference to `cv::VideoCapture::open(cv::String const&)'
image_io.cpp:(.text+0x1ace): undefined reference to `cv::VideoCapture::isOpened() const'
image_io.cpp:(.text+0x1c91): undefined reference to `cv::VideoCapture::~VideoCapture()'
image_io.cpp:(.text+0x1d22): undefined reference to `cv::VideoCapture::get(int) const'
image_io.cpp:(.text+0x1d6d): undefined reference to `cv::VideoCapture::set(int, double)'
image_io.cpp:(.text+0x1de1): undefined reference to `cv::VideoCapture::set(int, double)'
image_io.cpp:(.text+0x1e35): undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
image_io.cpp:(.text+0x1f7e): undefined reference to `cv::VideoCapture::release()'
image_io.cpp:(.text+0x1fc3): undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
image_io.cpp:(.text+0x22e9): undefined reference to `cv::VideoCapture::~VideoCapture()'
build/lib/libcaffe.a(io.o): In function `caffe::ReadImageToDatum(std::string const&, int, int, int, caffe::Datum*)':
io.cpp:(.text+0x5ac): undefined reference to `cv::imread(cv::String const&, int)'
io.cpp:(.text+0xa1d): undefined reference to `cv::imread(cv::String const&, int)'
collect2: error: ld returned 1 exit status
make: *** [build/tools/compute_volume_mean_from_list.bin] Error 1
make: *** Waiting for unfinished jobs....
build/lib/libcaffe.a(io.o): In function `caffe::ReadImageToDatum(std::string const&, int, int, int, caffe::Datum*)':
io.cpp:(.text+0x5ac): undefined reference to `cv::imread(cv::String const&, int)'
io.cpp:(.text+0xa1d): undefined reference to `cv::imread(cv::String const&, int)'
collect2: error: ld returned 1 exit status
make: *** [build/tools/compute_volume_mean.bin] Error 1
build/lib/libcaffe.a(image_io.o): In function `caffe::ReadImageSequenceToVolumeDatum(char const*, int, int, int, int, int, int, caffe::VolumeDatum*)':
image_io.cpp:(.text+0x694): undefined reference to `cv::imread(cv::String const&, int)'
image_io.cpp:(.text+0xb07): undefined reference to `cv::imread(cv::String const&, int)'
build/lib/libcaffe.a(image_io.o): In function `caffe::ReadVideoToVolumeDatum(char const*, int, int, int, int, int, int, caffe::VolumeDatum*)':
image_io.cpp:(.text+0x1905): undefined reference to `cv::VideoCapture::VideoCapture()'
image_io.cpp:(.text+0x1abe): undefined reference to `cv::VideoCapture::open(cv::String const&)'
image_io.cpp:(.text+0x1ace): undefined reference to `cv::VideoCapture::isOpened() const'
image_io.cpp:(.text+0x1c91): undefined reference to `cv::VideoCapture::~VideoCapture()'
image_io.cpp:(.text+0x1d22): undefined reference to `cv::VideoCapture::get(int) const'
image_io.cpp:(.text+0x1d6d): undefined reference to `cv::VideoCapture::set(int, double)'
image_io.cpp:(.text+0x1de1): undefined reference to `cv::VideoCapture::set(int, double)'
image_io.cpp:(.text+0x1e35): undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
image_io.cpp:(.text+0x1f7e): undefined reference to `cv::VideoCapture::release()'
image_io.cpp:(.text+0x1fc3): undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
image_io.cpp:(.text+0x22e9): undefined reference to `cv::VideoCapture::~VideoCapture()'
build/lib/libcaffe.a(io.o): In function `caffe::ReadImageToDatum(std::string const&, int, int, int, caffe::Datum*)':
io.cpp:(.text+0x5ac): undefined reference to `cv::imread(cv::String const&, int)'
io.cpp:(.text+0xa1d): undefined reference to `cv::imread(cv::String const&, int)'
collect2: error: ld returned 1 exit status
make: *** [build/tools/blob_proto_to_blob_binary.bin] Error 1
build/lib/libcaffe.a(io.o): In function `caffe::ReadImageToDatum(std::string const&, int, int, int, caffe::Datum*)':
io.cpp:(.text+0x5ac): undefined reference to `cv::imread(cv::String const&, int)'
io.cpp:(.text+0xa1d): undefined reference to `cv::imread(cv::String const&, int)'
collect2: error: ld returned 1 exit status
make: *** [build/tools/compute_image_mean.bin] Error 1
build/lib/libcaffe.a(io.o): In function `caffe::ReadImageToDatum(std::string const&, int, int, int, caffe::Datum*)':
io.cpp:(.text+0x5ac): undefined reference to `cv::imread(cv::String const&, int)'
io.cpp:(.text+0xa1d): undefined reference to `cv::imread(cv::String const&, int)'
collect2: error: ld returned 1 exit status
build/lib/libcaffe.a(io.o): In function `caffe::ReadImageToDatum(std::string const&, int, int, int, caffe::Datum*)':
io.cpp:(.text+0x5ac): undefined reference to `cv::imread(cvmake: ::String const&, int)'
*** [build/tools/compute_image_mean_from_list.bin] Error 1io.cpp:(.text+0xa1d
): undefined reference to `cv::imread(cv::String const&, int)'
collect2: error: ld returned 1 exit status
make: *** [build/tools/convert_imageset.bin] Error 1
build/lib/libcaffe.a(image_io.o): In function `caffe::ReadImageSequenceToVolumeDatum(char const*, int, int, int, int, int, int, caffe::VolumeDatum*)':
image_io.cpp:(.text+0x694): undefined reference to `cv::imread(cv::String const&, int)'
image_io.cpp:(.text+0xb07): undefined reference to `cv::imread(cv::String const&, int)'
build/lib/libcaffe.a(image_io.o): In function `caffe::ReadVideoToVolumeDatum(char const*, int, int, int, int, int, int, caffe::VolumeDatum*)':
image_io.cpp:(.text+0x1905): undefined reference to `cv::VideoCapture::VideoCapture()'
image_io.cpp:(.text+0x1abe): undefined reference to `cv::VideoCapture::open(cv::String const&)'
image_io.cpp:(.text+0x1ace): undefined reference to `cv::VideoCapture::isOpened() const'
image_io.cpp:(.text+0x1c91): undefined reference to `cv::VideoCapture::~VideoCapture()'
image_io.cpp:(.text+0x1d22): undefined reference to `cv::VideoCapture::get(int) const'
image_io.cpp:(.text+0x1d6d): undefined reference to `cv::VideoCapture::set(int, double)'
image_io.cpp:(.text+0x1de1): undefined reference to `cv::VideoCapture::set(int, double)'
image_io.cpp:(.text+0x1e35): undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
image_io.cpp:(.text+0x1f7e): undefined reference to `cv::VideoCapture::release()'
image_io.cpp:(.text+0x1fc3): undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
image_io.cpp:(.text+0x22e9): undefined reference to `cv::VideoCapture::~VideoCapture()'
build/lib/libcaffe.a(io.o): In function `caffe::ReadImageToDatum(std::string const&, int, int, int, caffe::Datum*)':
io.cpp:(.text+0x5ac): undefined reference to `cv::imread(cv::String const&, int)'
io.cpp:(.text+0xa1d): undefined reference to `cv::imread(cv::String const&, int)'
collect2: error: ld returned 1 exit status
make: *** [build/tools/compute_volume_mean_from_list_videos.bin] Error 1

**Comment by abuccts** [comment]
What's your system environment and opencv version?
May be you can refer to caffe issue [#2348](https://github.com/BVLC/caffe/issues/2348) and [#1276](https://github.com/BVLC/caffe/issues/1276).

**Comment by dutran** [comment]
It seems you don't have opencv properly installed.

**Comment by weizhou-geek** [comment]
@abuccts , my system is Ubuntu 14.04.2 LTS \n \l, and the opencv version is 3.1.0

**Comment by weizhou-geek** [comment]
@dutran , does the opencv 3.1 have any issues to the C3D compile?

**Comment by abuccts** [comment]
@weizhou-geek 

You can
- add `opencv_imgcodecs` and `opencv_videoio` to the end of following line in your Makefile.
```
LIBRARIES := cudart cublas curand \
	pthread \
	glog protobuf leveldb snappy \
	boost_system \
	hdf5_hl hdf5 \
	opencv_core opencv_highgui opencv_imgproc
```
or
- try to re-install opencv2.4.

Then `make clean` and `make all` again.

**Comment by weizhou-geek** [comment]
@abuccts @dutran  Now it works well. Thanks very much!

**Comment by abuccts** [comment]
@weizhou-geek  How did you solve it? Is it an opencv3 problem?

**Comment by weizhou-geek** [comment]
@abuccts  According to your method, I just add the opencv_imgcodecs and opencv_videoio to the Makefile and then it works.

**Comment by dutran** [comment]
good to hear you got your issue solved. Cheers.
