### ISSUE TITLE
recognition result of C3D(1 net)+linear SVM on UCF101

### ISSUE THREAD

**Issue by erichouyi** [facebook/C3D#156]
Hi, dutran!
Recently, i conduct experiment on UCF101 using fc6+linear SVM. My results are 82.45%(Split 1), 89.39%(Split 2)  and  90.67%(Split 3) respectively, so the average result is 87.50%. However, your result of C3D(1 net)+linear SVM on UCF101 is 82.3% in paper,  is there something wrong with my result?

**Comment by erichouyi** [comment]
I have found the problem, because i use the c3d_ucf101_finetune_whole_iter_20000 to  extract fc6 feature. And in your paper, conv3d_deepnetA_sport1m_iter_1900000 is used. So when i conduct experiment on UCF101, can i use c3d_ucf101_finetune_whole_iter_20000 to extract fc6 feature for good recognition result?

**Comment by dutran** [comment]
@erichouyi  That makes sense, because c3d_ucf101_finetune_whole_iter_20000 was fine-tuned on train_split 1, thus only test result on split 1 is valid which is 82.45. While the test numbers on split 2 and 3 are not valid as some test videos are included in train_split 1 and used in fine-tuning.

**Comment by erichouyi** [comment]
@dutran ,thank you! I use  conv3d_deepnetA_sport1m_iter_1900000 to extract fc6 feature, the results are 83.14% (split 1), 79.75% (split 2), and 82.52% (split 3) respectively, the average result is 81.8%, and your result is 82.3% by C3D(1 net)+linear SVM, so the difference is 0.5%. is it normal?

**Comment by dutran** [comment]
There are a couple things that you may want to check.
1. If you did L2-normalized your averaged fc6 features (of clips from the same video)
2. Did you cross-validate the best C-parameter in your linear SVM. Assumed you did L2-normalize your features, then C=1 should be OK

**Comment by erichouyi** [comment]
@dutran , thank you! I will try it.

**Comment by thomhert** [comment]
@erichouyi @dutran Did you mean split 1, 2, and 3 refer to Test Splits for Action Recognition downloaded [here](http://crcv.ucf.edu/data/UCF101.php)?
I want to conduct experiment on C3D+ linear SVM as well, so now I am preparing input_list_video/frm and output_list_prefix. Would you mind to share your txt files? It would be so much helpful for me. Thank you.

**Comment by dutran** [comment]
@thomhert it's right.
