### ISSUE TITLE
How to use the extracted feature

### ISSUE THREAD

**Issue by weizhou-geek** [facebook/C3D#159]
Hi,

After I extract the features in the output file, I can get the .fc6-1, .fc7-1 and .prob files. But how do I further use these features? 

Thanks!

**Comment by dutran** [comment]
@weizhou-geek use these scripts (https://github.com/facebook/C3D/tree/master/examples/c3d_feature_extraction/script) to read the feature files.

**Comment by weizhou-geek** [comment]
@dutran . Thank you very much!
