### ISSUE TITLE
How to use C3D finetuning with videos not frames

### ISSUE THREAD

**Issue by Michael-Guo** [facebook/C3D#16]
I want to finetune C3D pre-trained model on UCF101, the example uses frames. But I want to use videos, how to modify list files and prototxt files, and different videos have different frames. How to determine frame number in list files. Thank you!

**Comment by dutran** [comment]
@Michael-Guo the setting is similar to C3D feature extraction part. You can refer to the feature extraction part for the list file format. You can use ffmpeg, matlab, or opencv to read your video files headers to get those info. Hope this helps!
