### ISSUE TITLE
How to extract the learned filters？

### ISSUE THREAD

**Issue by lishanlu136** [facebook/C3D#160]
Hi, thank you for sharing such good code. I successfully run the C3D, but I want to extract the learned filters, how should I do? I know there is a file named “extract_learned_filters" in the tools folder. It needs to enter four parameters, the last parameter is the file that holds the learned filters. Could you tell me what the format of this file is？

**Comment by dutran** [comment]
You can read this https://docs.google.com/document/d/1-QqZ3JHd76JfimY4QKqOojcEaf5g3JS0lNh-FHTxLag/edit and also this https://github.com/facebook/C3D/tree/master/examples/c3d_feature_extraction

**Comment by lishanlu136** [comment]
Thank you for the proposal, I have seen this document. Only extract features, training and fine-tuning examples. There is no description on how to extract the learned filters.

**Comment by dutran** [comment]
Oh, I miss-read your question. Yes, you can use this https://github.com/facebook/C3D/blob/master/tools/extract_learned_filters.cpp to extract the learned filters.

**Comment by lishanlu136** [comment]
Yes, i read that document. However, I do not know what is the argv[4] format.

**Comment by dutran** [comment]
argv[1]: your prototxt file (string)
argv[2]: your pre-trained model (string)
argv[3]: your layer name (string), e.g. conv1a
argv[4]: output file name (string), where you want to write out your learned filters

**Comment by lishanlu136** [comment]
Sorry, i do not know what is the argv[4] format. For example: txt, binaryproto or other.
