### ISSUE TITLE
issue loading 3D data while starting training

### ISSUE THREAD

**Issue by omair18** [facebook/C3D#161]
I have a 3D dataset stored in HDF5 file, where dimensions are 32x32x32 and chunk size is 10. When I try to load this data using HDF5 data layer, caffe's log prints that It has loaded 10x32x1x1x32. Whereas it should have loaded 10x32x32x32 in a single batch (screen-shots attached). 
Can someone please guide me about this issue? 

![Protoxt File](https://cloud.githubusercontent.com/assets/1974232/19922205/756c1112-a103-11e6-9721-8b9096cb8282.png)
![LOG output](https://cloud.githubusercontent.com/assets/1974232/19922206/75715ca8-a103-11e6-94c7-b758e42cbcfe.png)

![selection_004](https://cloud.githubusercontent.com/assets/1974232/19922291/d2c728c4-a103-11e6-842a-fa4b5980460a.png)

**Comment by dutran** [comment]
@omair18 it looks like to need to modify your hdf5 data layer reshape to 5D tensor, e.g. num x channel x length x height x width. In your case, 10 x 1 x 32 x 32 x 32

**Comment by omair18** [comment]
I have tried to load a 5D tensor( 10x1x32x32x32) , but now the data layer loads data of shape 10x1x1x32x32. 
Is there some issue with the HDF5 layer's source code? How can I edit the source code for my specific usage?

**Comment by dutran** [comment]
By looking at your hdf5 https://cloud.githubusercontent.com/assets/1974232/19922291/d2c728c4-a103-11e6-842a-fa4b5980460a.png, it seems:
1) you haven't modified you script to create hdf5 file. So that it is 4D tensor (instead of 5D)
2) you haven't modified https://github.com/facebook/C3D/blob/master/src/caffe/layers/hdf5_data_layer.cpp and https://github.com/facebook/C3D/blob/master/src/caffe/layers/hdf5_data_layer.cu to handle 5D tensor as well.

**Comment by omair18** [comment]
I have modified my script to generate a 5D tensor ( screenshot attached). I'll look into the source files which you mentioned above and will update you accordingly. Thank you 

![image](https://cloud.githubusercontent.com/assets/1974232/19994360/3c894eb0-a26f-11e6-9f77-163190c82d2c.png)

**Comment by dutran** [comment]
have commit a minor modification, you can try again

**Comment by omair18** [comment]
Thank you the commit. Data layer now loads 5D data but i'm getting core dump in Inner Product layer. A bit of debugging source code shows that segmentation fault occurs at line 38 of inner_product_layer.cpp  while filling the weights for this layer. Can you help me regarding this issue? What possibly wrong i'm doing here?

![selection_005](https://cloud.githubusercontent.com/assets/1974232/20003191/08c9bbe0-a2a7-11e6-8a7b-d5d8af745adb.png)

**Comment by dutran** [comment]
You supposed to use pool3d layer instead of pool2d. I saw your switch from 5D tensor to 4D after pooling

**Comment by omair18** [comment]
I am actually using POOL3D layer in my network. I'm not sure if there will be any change in Inner Product layer ( 2D or 3D). 
![selection_006](https://cloud.githubusercontent.com/assets/1974232/20014336/7087ac84-a2d8-11e6-9913-5865e164a070.png)

**Comment by dutran** [comment]
Oh, you are right. Your pooling is OK, but your fully connected layer consume a lot of memory. Output of your conv2a = 800 x 16 x 8 x 8 = 819200. The #parameters in ip1 = 819200 x number of output which cause seg fault. Normally you need to do a couple more conv/pool to get smaller signal before fc layers.

**Comment by omair18** [comment]
Thanks alot @dutran . I added a couple more conv3/pooling3 layers and training is going well now :)

**Comment by dutran** [comment]
glad to hear it works for you.
