### ISSUE TITLE
Possible overflowing integer numbers in ReadImageSequenceToVolumeDatum function.

### ISSUE THREAD

**Issue by antran89** [facebook/C3D#162]
Hi,
I have not encounter this problem. Just a hypothesis. I met another problem, then I thought there are a overflowing integer number because of integral multiplication operations in function `ReadImageSequenceToVolumeDatum`. In [line 180](https://github.com/facebook/C3D/blob/master/src/caffe/util/image_io.cpp#L180), all variables are `int`, but all multiplication operations in [line 210-212](https://github.com/facebook/C3D/blob/master/src/caffe/util/image_io.cpp#L210-212) seems to be larger than integer numbers. I do not know exactly how compiler and system handle these numbers. There might be overflowing numbers in theoretical sense. For example, if the volume size `(3, 16, 128, 171)`, then:
`image_size=128*171=21888, channel_size=16*128*171=350208, data_size=3*16*128*171=1050624`. 
These numbers are larger than traditional maximum defined values of an `int`. However, in practice, I use the code without any problems with this function to read the images into video volume.
With recent techniques with [longer temporal convolution](https://arxiv.org/abs/1604.04494), it seems that we need a larger variable to hold these values.

**Comment by dutran** [comment]
@antran89 Thanks for bring up the issue. I don't know why it did not make any issue yet. But literately it should be long. Do you want to make a PR? That would be great!

**Comment by antran89** [comment]
@dutran I will.
