### ISSUE TITLE
Testing 3D trained model using Python Script & Deploy file

### ISSUE THREAD

**Issue by omair18** [facebook/C3D#163]
I was successful in training my 3D dataset by giving 5D tensor ( 10x1x32x32x32) to the network. Now I'm using python script to load the trained model and deploy.prototxt and giving the input test dataset in the form of 5D tensor ( 10x1x32x32x32)  but caffe outputs a ValueError saying "could not broadcast input array from shape (10,1,32,32,32) into shape (10,1,32,32). 
Isn't it the right way to do? why my model is expecting a 10,1,32,32 shape? 
![image](https://cloud.githubusercontent.com/assets/1974232/20029949/99e72164-a37c-11e6-9ac1-b83efd4809c5.png)

**Comment by dutran** [comment]
need to modify HDF5data_output as well, please wait for another minor commit.

**Comment by dutran** [comment]
@omair18 please try again.

**Comment by omair18** [comment]
@dutran  I can't see any change in the output, getting the very same error. 
I have pulled the update and did make all, make pycaffe. 
Secondly, I'm using caffe.Classifier( deploy, trainedfile) in my python script. Any suggestions?

**Comment by dutran** [comment]
Try this instead https://github.com/facebook/C3D/pull/59.

**Comment by omair18** [comment]
I'm slightly confused with the usage of above mentioned script for my specific case. Can you please guide me how to test a single 3D object? Object dimensions are 32x32x32 ( length x width x height) and i'm making a 5D tensor with dimensions  batchsize x channels x length x width x height.

**Comment by dutran** [comment]
Is you problem is just simply classification? If so, you don't need to use python wrapper. Just use test_net to test (for final accuracy). If you prefer to use some intermediate output, use extract_image_features to extract them and further process them if needed.

**Comment by omair18** [comment]
My problem is somewhat related to scene classification. I want to crop a 3D piece from a scene and classify it with the help of my trained network. test_net won't help me in this case i guess.

**Comment by omair18** [comment]
@dutran  I'm trying to look into this python wrapper ( pycaffe.py). If you get any success, do let me know please.

**Comment by omair18** [comment]
@dutran It seems like, changing Class CaffeBlobWrap in caffe.cpp solved the issue. I increased the dimensions in object_get_data() function from 4 to 5 and the ValueError is gone. 
Also there was a check in pycaffe.py  _Net_forward() function, I changed it from 4 to 5.

**Comment by dutran** [comment]
@omair18 can you send in a PR? Thanks

**Comment by dutran** [comment]
Glad to hear it works for you.

**Comment by omair18** [comment]
@dutran  I'm rather new on github and unable to figure out how to send my modified project in a PR. Can you guide me a bit? 
I've forked this project on my profile and committing changes into it.
