### ISSUE TITLE
Does pycaffe work?

### ISSUE THREAD

**Issue by lynetcha** [facebook/C3D#167]
I get the following error when trying to run     caffe.set_mode_gpu()
AttributeError: 'module' object has no attribute 'set_mode_gpu'

**Comment by omair18** [comment]
@lynetcha  you should first initialize your net using caffe.Net(deploy, trainednetwork)  or caffe.Classifier() and then set net.set_mode_gpu().

**Comment by lynetcha** [comment]
Ok. I guess what I meant is that the interface is quite minimal. It doesn't seem to be possible to reshape blobs from Caffe for example if I want to provide input directly, as is done in other caffe interfaces that use an "Input" layer.

**Comment by dutran** [comment]
There is one PR, not merged yet, but supposed to work.
