### ISSUE TITLE
Softmax Layer is still in 2D?

### ISSUE THREAD

**Issue by lynetcha** [facebook/C3D#170]
I just checked the code for the Softmax layer , and looking at the SetUp function, it seems like it's mainly appropriate for 2D Inputs. (bottom[0]->length() is ignored). I was wondering which of the layers available fully  support 3D?

**Comment by dutran** [comment]
previously worked fine because softmax normally followed an fc layer which assumed to have length=1. But you can try now for various blob length. Thanks.
