### ISSUE TITLE
error in compilation

### ISSUE THREAD

**Issue by kazulittlefox** [facebook/C3D#172]
Hi.
I have tried compiling this library, but i have failed.
Error message indicated in console is like:

> nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/usr/local/pyenv/versions/anaconda2-4.1.1/include/boost/config/suffix.hpp(510): error: identifier "__float128" is undefined
>
>/usr/local/pyenv/versions/anaconda2-4.1.1/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(75): warning: variable "tmp" was set but never used
>
>1 error detected in the compilation of "/tmp/tmpxft_00007d1d_00000000-11_vol2col.compute_35.cpp1.ii".
>make: *** [build/src/caffe/util/vol2col.cuo] error 2

If you don't mind, I need more informations for solving this problem.
And I also need about information about compiling tool scripts separately
(to tell the truth, if it doesn't work, I will use other ML library, and only needed is tools for making 
3D convolution mean-data, converting caffe-style data,or so...)

Thanks.

**Comment by abuccts** [comment]
What's your `gcc`, `nvcc` and `boost` version?
If you are using `boost 1.60`,
try to
- remove `boost 1.60` and install another version like `1.61`

or
- fix it referring to [this patch](https://svn.boost.org/trac/boost/ticket/11852)

**Comment by kazulittlefox** [comment]
Thanks, I'm appliciate for your reply.

**Comment by abuccts** [comment]
glad to hear it works.
