### ISSUE TITLE
Problem about feature extraction

### ISSUE THREAD

**Issue by JinjunWhite** [facebook/C3D#174]
Hi, I successfully used the svm to classify some handgesture by reading
http://vra.github.io/2016/03/03/c3d-use/  "Classify C3D feature using SVM"
I extract  features of batches  videos as input of svm  to predcit them. The accuracy is 95%, and output label is satisfied.
But when I try to extract single video features to classify by using svm, and i try to predict several videos by single testing, the result always be wrong.
What I want to know is that  weather the features extracted by  single video is same as the features extracted by one of batches.

**Comment by dutran** [comment]
I would like to help but I cannot understand your message/issue.

**Comment by JinjunWhite** [comment]
Thanks for your attention.
I mean that, for example, I extract 100 videos' features at first time, and take 70 videos' features to train a svm model. Then I try to use the svm model to classify remaining 30 videos'feature, and the output labels are almost right. So the 70 videos are train-dataset and the 30 videos are test-dataset.
At second time, I choose a video randomly from the test-dataset. Then I extract this video's feature, and classify it with the svm model trained at first time.I failed to classify the video.

So, as for the same video, why the feature extracted in first time is different from the feature extracted in second time.
![problem](https://cloud.githubusercontent.com/assets/23622473/20950680/19717144-bc5c-11e6-9d4b-e82eb01adbb6.png)

**Comment by dutran** [comment]
It looks like you have shuffle=true, thus extracting features at different times give you different features.

**Comment by JinjunWhite** [comment]
Ah...actually, I set shuffle=false all the time. It was still wrong. Is there any other reason?

**Comment by dutran** [comment]
@JinjunWhite have you got your issue resolved?

**Comment by JinjunWhite** [comment]
@dutran not yet, I wonder why the feature extracted in first time different from second time. I cannot use a trained svm model to predict new video unless extract features of training video and new video together.
