### ISSUE TITLE
How to switch off dropout while extracting features (from fc layers)

### ISSUE THREAD

**Issue by dasabir** [facebook/C3D#175]
Hi,
Is there a way to switch off the dropout while extracting features from a fc layer? For example, say, I'm using - prototxt/c3d_sport1m_feature_extractor_frm.prototxt and am trying to extract the activations after the ReLU layer of 'fc7-1' (but before the dropout layer). As a test, I'm checking the probability values given out by the network. I've trying the following 3 options.
1. Setting "dropout_ratio: 0.0" for all the dropout layers
2. Setting "dropout_ratio: 1.0" for all the dropout layers
3. Deleting all the dropout layers completely from the prototxt

For all these options I'm getting different results (I'm checking the 'prob' layer values) in different runs on the same videos. As a precaution, I have set 'shuffle = false' too. I have also checked that the conv layers are giving me constant values in each run (which is expected as no dropout is used before them).

**Comment by dutran** [comment]
You can just remove the dropout layer. I was assumed dropout is not used in test phrase, but only in training.
