### ISSUE TITLE
about the result

### ISSUE THREAD

**Issue by bitwangdan** [facebook/C3D#177]
I run the code successfully ,but i can't find the result . Here is my code result:

I1130 23:56:59.709164  6212 blocking_queue.cpp:50] Data layer prefetch queue empty
E1130 23:57:06.510202  6212 predict.cpp:91] Extracted features of 50050 images.
E1201 00:08:08.135692  6212 predict.cpp:91] Extracted features of 55050 images.
E1201 00:19:08.217056  6212 predict.cpp:91] Extracted features of 60050 images.
E1201 00:30:04.988960  6212 predict.cpp:91] Extracted features of 65050 images.
E1201 00:40:55.206074  6212 predict.cpp:91] Extracted features of 70050 images.
E1201 00:51:44.407023  6212 predict.cpp:91] Extracted features of 75050 images.
E1201 01:02:30.867449  6212 predict.cpp:91] Extracted features of 80050 images.
E1201 01:13:08.661902  6212 predict.cpp:91] Extracted features of 85050 images.
E1201 01:23:44.307425  6212 predict.cpp:91] Extracted features of 90050 images.
E1201 01:34:21.501793  6212 predict.cpp:91] Extracted features of 95050 images.
W1201 01:44:55.197635  6212 net.cpp:580] DEPRECATED: Forward(bottom, loss) will be removed in a future version. Use Forward(loss).
I1201 01:44:55.197652  6212 blocking_queue.cpp:50] Data layer prefetch queue empty
E1201 01:45:01.580234  6212 predict.cpp:91] Extracted features of 100050 images.
E1201 01:55:37.596647  6212 predict.cpp:91] Extracted features of 105050 images.
E1201 02:06:13.707980  6212 predict.cpp:91] Extracted features of 110050 images.
E1201 02:16:49.959573  6212 predict.cpp:91] Extracted features of 115050 images.
E1201 02:27:58.752323  6212 predict.cpp:91] Extracted features of 120050 images.
E1201 02:38:45.378820  6212 predict.cpp:91] Extracted features of 125050 images.
E1201 02:49:38.695917  6212 predict.cpp:91] Extracted features of 130050 images.
E1201 03:00:29.163555  6212 predict.cpp:91] Extracted features of 135050 images.
E1201 03:11:20.792975  6212 predict.cpp:91] Extracted features of 140050 images.
E1201 03:22:12.542882  6212 predict.cpp:91] Extracted features of 145050 images.

this is my output_prefix.txt:

output/c3d/video1900/000209
output/c3d/video1900/000225
output/c3d/video1900/000241
output/c3d/video1900/000257
output/c3d/video1900/000273
output/c3d/video1900/000289
output/c3d/video1900/000305
output/c3d/video1900/000321
output/c3d/video1900/000337
output/c3d/video1900/000353
output/c3d/video1900/000369
output/c3d/video1900/000385
output/c3d/video1900/000401
output/c3d/video1900/000417
output/c3d/video1900/000433
output/c3d/video1900/000449
output/c3d/video1900/000465
output/c3d/video1900/000481

but i can't find the the features extracted by the code .can you help me?

**Comment by dutran** [comment]
this will save to "your current directory"/output/c3d/video1900/ however, you need to create the directory before running it.
