### ISSUE TITLE
about the result

### ISSUE THREAD

**Issue by bitwangdan** [facebook/C3D#178]
I'm sorry to bother you again . 
I run sh examples/c3d_ucf101/feature_extraction/extract_c3d_features .sh
so my current directory is video-caffe-master/
my output_prefix.txt is like this:
output/c3d/v_ApplyEyeMakeup_g01_c01/ 000001
output/c3d/v_ApplyEyeMakeup_g01_c01/ 000017
output/c3d/v_ApplyEyeMakeup_g01_c01/ 000033
output/c3d/v_ApplyEyeMakeup_g01_c01/ 000049
output/c3d/v_ApplyEyeMakeup_g01_c01/ 000065
output/c3d/v_ApplyEyeMakeup_g01_c01/ 000081
output/c3d/v_ApplyEyeMakeup_g01_c01/ 000097
output/c3d/v_ApplyEyeMakeup_g01_c01/ 000113
output/c3d/v_ApplyEyeMakeup_g01_c01/ 000129
output/c3d/v_ApplyEyeMakeup_g01_c01/ 000145

so the result should be saved in video-caffe-master/output/c3d/v_ApplyEyeMakeup_g01_c01/000*.fc8
but the resut is saved in video-caffe-master/0000*.fc8. I don't know why is it. I also create the directory like this : video-caffe-master/output/c3d/v_ApplyEyeMakeup_g01_c01 ,but the result is still saved in video-caffe-master, not my set the path ,

**Comment by xibaohe** [comment]
maybe  your current work dir is  video-caffe-master/  ?
not in example/********

**Comment by dutran** [comment]
Check the prefix file, the tool should follow the prefix file to store the features
