### ISSUE TITLE
why C3D use  continuous 16  frames?

### ISSUE THREAD

**Issue by xibaohe** [facebook/C3D#179]
I mean  the two adjacent frames  must be redundancy..   
 the continuous 16 frames may not contains a complete action

I think  we should take  one from each 5 or 10 frames . (I see sampling_rate options ,may be could do it)

when I use  c3d_ucf101_finetune_whole_iter_20000  from dropbox,tested on split1, I get accuracy : 0.77075, not 0.8019

I finetuned myself got 0.787154.

Am I made some mistake? or it's OK?

**Comment by dutran** [comment]
Did you try this? https://github.com/facebook/C3D/blob/master/examples/c3d_finetuning/ucf101_testing.sh I and a couple others can confirm the 0.8 something accuracy. Check again!

**Comment by b-safwat** [comment]
@xibaohe I indeed have tried different FPS and they yielded better results, check it here: https://ieeexplore.ieee.org/document/8639245
