### ISSUE TITLE
cuda issue during running

### ISSUE THREAD

**Issue by apoliver** [facebook/C3D#18]
Hi,

I work on ubuntu 14.04 and using GTX 980 with cuda 6.5. I can successfully compiled C3D. But when I execute running, it reports following error:

Check failed: error == cudaSuccess (8 vs. 0)  invalid device function 

This error is reported when executing CUDA_POST_KERNEL_CHECK; in vol2col.cu's row 75.

I can run caffe successfully also.

Do anyone have any idea of how shall I fix this? Thanks so much.

**Comment by dutran** [comment]
@apoliver : You may not get your CUDA correctly setup. Please refer to the similar issue:
https://github.com/BVLC/caffe/issues/138

**Comment by apoliver** [comment]
Thanks Du, I checked this page before. Probably due to other reasons. I will try to figure it out.

**Comment by apoliver** [comment]
Thanks, Du. I just figured it out. I find that my Makefile.config lacks a slash at the end of the line 13 as like "-gencode arch=compute_35,code=sm_35 \" after uncommon line 14 and 15. After I add it, C3D can work well.
