### ISSUE TITLE
questions about C3D model fine-tuned on UCF101

### ISSUE THREAD

**Issue by hayato8059** [facebook/C3D#182]
thank you to share the C3D code. In C3D User Guide you provide the C3D model fine-tuned on UCF101 on https://www.dropbox.com/s/mkc9q7g4wnqnmcv/c3d_ucf101_finetune_whole_iter_20000 this web, but i can't open this. Is this website have some problems?

**Comment by xibaohe** [comment]
dropbox has been blocked in china。

**Comment by dutran** [comment]
@hayato8059 try this https://drive.google.com/file/d/0Bx-2rTokRAt1UTM5NzJhZGtKc2M/view?usp=sharing
