### ISSUE TITLE
Is there any script to read the computed mean file

### ISSUE THREAD

**Issue by jiang2764** [facebook/C3D#183]
I want to read the pre-computed mean file, such as "c3d_finetuning/train01_16_128_171_mean.binaryproto".　I used the following python script to read it, I got the error as below:

import caffe
import numpy as np
blob = caffe.proto.caffe_pb2.BlobProto()
data = open( '../examples/c3d_finetuning/train01_16_128_171_mean.binaryproto', 'rb' ).read()
blob.ParseFromString(data)
arr = np.array( caffe.io.blobproto_to_array(blob) )

raceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "caffe/io.py", line 32, in blobproto_to_array
    return data.reshape(blob.num, blob.channels, blob.height, blob.width)
ValueError: total size of new array must be unchanged

I understand that the python wrapper is not ready. Can you provide some hints? Thanks.

**Comment by dutran** [comment]
We don't have tool to read pre-computed mean file yet. Simple option is slightly modify compute-mean-tool to save it to your format (e.g. binary files used for feature extraction and use matlab or python to read)

**Comment by grantlj** [comment]
is there any solution?

**Comment by jiang2764** [comment]
You can change 'data.reshape(blob.num, blob.channels, blob.height, blob.width)' in line 32 of caffe/io.py
to be 'data.reshape(blob.num, blob.channels, blob.length, blob.height, blob.width)'
