### ISSUE TITLE
Calculate mean value of blobs in c++?

### ISSUE THREAD

**Issue by JinJunho** [facebook/C3D#185]
I am pretty new to Caffe. I am currently working on classifying c3d features using SVM (reference: http://vra.github.io/2016/03/03/c3d-use/). Since I don't have matlab installed on my machine, I am trying to calculate the mean value of features for each frame but have no clue to do so using c++ because I am not aware of the blob structure. Can you explain the blob structure especially its properties such as length, num or channels and how to manipulate them?

**Comment by dutran** [comment]
blob is 5D tensor of Count x Channels x Length x Height x Width in row-order. Closing since this is not software-related issue.
