### ISSUE TITLE
Check failed: prefetch_rng_ 

### ISSUE THREAD

**Issue by ThinkLock** [facebook/C3D#186]
Hi，dutran.
   I'm very interested in your work on C3D and would like to follow the work.
   I extract the feature successful, but when i try to train on my own net, i got the error message.
  
   **F1222 12:14:52.081912  9746 video_data_layer.cpp:445] Check failed: prefetch_rng_** 
   
    Can you provide some solution? Thanks.

**Comment by dutran** [comment]
I think your problem is on some setting options on data layer, tweeting between mirror, shuffle, or something like this. Could you share your data layer prototxt?

**Comment by ThinkLock** [comment]
Thanks for your attention.
I modify the mirror from true to false, and this error disappear。

Now, I train on the UCF101 successfully, and i get the clips accuracy about 43~44%. 
Recently,  i am interested  in your another paper 'Deep End2End Voxel2Voxel Perdiction'. And i find 'video_with_voxel_truth_data_layer' and 'deconvolution3d_layer' in the C3D source code. But i did not find the examples of this layers. So i do not get how to use this layers. 

Could you share some examples? Thanks

**Comment by ThinkLock** [comment]
Thanks @dutran ,
I set the mirror=false, and this error disappear.
Thanks a lot!

**Comment by ThinkLock** [comment]
Hi, @dutran 

Recently, i am interested in your another paper 'Deep End2End Voxel2Voxel Prediction'.
And, i found some related layers in the C3D source code, such as Deconv3d, VIDEO_WITH_VOXEL_TRUTH_DATA.But when I read the example of the /v2v/ucf101_optical_flow,  the source: "/data/users/trandu/datasets/ucf101/list/train_flow01_brox.txt" confused me. I do not know how to get and use this source file. So, Could you share some more specific suggestion?

Thanks a lot~~

**Comment by liu666666** [comment]
@dutran  @ThinkLock  Could you show more details about the source: "/data/users/trandu/datasets/ucf101/list/train_flow01_brox.txt" ? Thanks!
