### ISSUE TITLE
How to visualize the learned filters?

### ISSUE THREAD

**Issue by lishanlu136** [facebook/C3D#189]
Hi, thank you for sharing such good code. I successfully run the C3D, but I want to visualize the learned filters, how should I do?

**Comment by kajal15003** [comment]
http://www.cs.nyu.edu/~fergus/papers/zeilerECCV2014.pdf
Refer this paper. Code is available on github.

**Comment by dutran** [comment]
Yes, sorry. The current version does not provide full visualization. As there are many requests, I think we should have a PR for this soon.
