### ISSUE TITLE
Feature extraction: need to resize video frames?

### ISSUE THREAD

**Issue by firmamentqj** [facebook/C3D#19]
Hi Du,

Just a quick question. Do I need to resize the videos before extracting their C3D features? Because in your paper, you have resized all video frames into 128*171.

Thank you very much:)

Nigel

**Comment by apoliver** [comment]
I think you don't need to do so since C3D will take care of this.

**Comment by dutran** [comment]
@apoliver is right. In the video data layer, you can specify new_height: 128, and new_width: 171, then C3D will scale your input videos to that scale.

**Comment by firmamentqj** [comment]
That's great. Thanks a lot:) @dutran @apoliver
