### ISSUE TITLE
Test V2V without Training phase

### ISSUE THREAD

**Issue by ltnghia** [facebook/C3D#191]
Hello,

My GPU is not large enough for training and testing at the same time. Thus, I train V2V first and then test the network. However, when I use "test_net.bin", it cannot show any results if I include this layer:

```
layers {
  name: "loss"
  type: VOXEL_SOFTMAX_LOSS
  bottom: "predict"
  bottom: "truth"
}
```

I set iterations = 10, but it cannot run and show only:

```
...
E0106 18:58:56.807622 14288 test_net.cpp:45] Running 10 iterations.
```

Can you help me this problem?

Thank you in advance.

**Comment by dutran** [comment]
You should use extract_image_features tool to extract predict blob (remember to rescale the predictions). The evaluate them either using matlab or python.
