### ISSUE TITLE
How to extract feature for longer sequences?

### ISSUE THREAD

**Issue by LongLong-Jing** [facebook/C3D#192]
Hi. Thanks for your amazing job. This is a great help for my research. I had a hard time to extract features for a longer sequence such as 32 frames. I changed the new_length variable in c3d_sport1m_feature_extractor_frm.prototxt form 16 into 32, and changed some code files, but there still some problems. I only need the convolutional features so I think the C3D can handle this. Can you give me some advice? Thanks!

**Comment by LongLong-Jing** [comment]
I solved this problem these days. You can close this issue. Thanks!

**Comment by Girmaw** [comment]
Hi LongLong-Jing,

I also need to extract features for video segments of longer frames (e.g., 90), will you have some tips?

Thanks

**Comment by mengliu1991** [comment]
@LongLong-Jing how you use the released code to extract features for longer sequence?
