### ISSUE TITLE
C3D implementation in Torch

### ISSUE THREAD

**Issue by arshadcair** [facebook/C3D#194]
Hi, 

Is there any update on the C3D implementation in Torch? In another issue, you had mentioned about the release of the Torch implementation for C3D in near future.

Arshad

**Comment by dutran** [comment]
Have you checked this out? https://github.com/DeepMark/deepmark/blob/master/torch/image%2Bvideo/c3d.lua

**Comment by dutran** [comment]
Also this [https://github.com/MohsenFayyaz89/C3DTorch]. I haven't checked though :)

**Comment by omair-kg** [comment]
A bit of shameless self promotion but [this](https://github.com/omair-kg/Torch-C3D) also works.
