### ISSUE TITLE
Missing error report loading images

### ISSUE THREAD

**Issue by escorciav** [facebook/C3D#195]
I feel that an error report is missing in [these lines](https://github.com/facebook/C3D/blob/master/src/caffe/util/image_io.cpp#L194-L195). You already have it a couple of [lines later](https://github.com/facebook/C3D/blob/master/src/caffe/util/image_io.cpp#L202-L205), but the previous is silently passed.

Lemme know if a pull request is worth it. It is too trivial that you could do it easily.

```c++
if (!img_origin.data) {
    LOG(ERROR) << "Could not open or find file " << fn_im;
    return false;
}
```

**Comment by dutran** [comment]
Yes, that's right. Thanks for pointing this out. You can go ahead and make a PR.
