### ISSUE TITLE
Error running "make all"

### ISSUE THREAD

**Issue by medhini** [facebook/C3D#199]
I get this error while running "make all":

In file included from ./include/caffe/vision_layers.hpp:13:0, from src/caffe/layers/tanh_layer.cpp:9: ./include/caffe/neuron_layers.hpp:13:18: fatal error: hdf5.h: No such file or directory
compilation terminated.

Makefile:325: recipe for target 'build/src/caffe/layers/tanh_layer.o' failed
make: *** [build/src/caffe/layers/tanh_layer.o] Error 1

**Comment by dutran** [comment]
@medhini it seems you missed hdf5 library. Install that dependency then re-compile.
