### ISSUE TITLE
Feature extraction for videos -- Index of the first frame: 0 or 1?

### ISSUE THREAD

**Issue by firmamentqj** [facebook/C3D#20]
Hi Du,

I followed the C3DUserGuide and started to extract features for my videos. One of the videos has totally 224 frames and I wrote the input list file as follows:
```
input/avi/sample224.avi 1 0
input/avi/sample224.avi 17 0
input/avi/sample224.avi 33 0
input/avi/sample224.avi 49 0
input/avi/sample224.avi 65 0
input/avi/sample224.avi 81 0
input/avi/sample224.avi 97 0
input/avi/sample224.avi 113 0
input/avi/sample224.avi 129 0
input/avi/sample224.avi 145 0
input/avi/sample224.avi 161 0
input/avi/sample224.avi 177 0
input/avi/sample224.avi 193 0
input/avi/sample224.avi 209 0
```
However, it said:
```
F0717 20:00:40.468828  1975 image_io.cpp:135] Check failed: end_frm <= num_of_frames (225 vs. 224) end frame must less or equal to num of frames
*** Check failure stack trace: ***
Aborted (core dumped)
```

So I modified the input list as follows:
```
input/avi/sample224.avi 0 0
input/avi/sample224.avi 16 0
input/avi/sample224.avi 32 0
input/avi/sample224.avi 48 0
input/avi/sample224.avi 64 0
input/avi/sample224.avi 80 0
input/avi/sample224.avi 96 0
input/avi/sample224.avi 112 0
input/avi/sample224.avi 128 0
input/avi/sample224.avi 144 0
input/avi/sample224.avi 160 0
input/avi/sample224.avi 176 0
input/avi/sample224.avi 192 0
input/avi/sample224.avi 208 0
```
and it worked well and features were extracted successfully.

So I looked into the source code of image_io.cpp and found:
```
#133: cap.set(CV_CAP_PROP_POS_FRAMES, use_start_frm);
#134: int end_frm = use_start_frm + length * sampling_rate;
```
Then I found **CV_CAP_PROP_POS_FRAMES: 0-based index of the frame to be decoded/captured next.**

So I guess the cause of my problem may be the index of the first frame is **0** in OpenCV. For example, if I write
```
input/avi/sample224.avi m 0
```
in the input list, it actually starts capturing from frame **m+1** and extracts features for frames from **m+1** to **m+16**, not from **m** to **m+15**.

So I think it would be better if you use the following input list file as an example:
```
input/avi/v_ApplyEyeMakeup_g01_c01.avi 0 0
input/avi/v_ApplyEyeMakeup_g01_c01.avi 16 0
input/avi/v_ApplyEyeMakeup_g01_c01.avi 32 0
input/avi/v_ApplyEyeMakeup_g01_c01.avi 48 0
input/avi/v_ApplyEyeMakeup_g01_c01.avi 64 0
input/avi/v_ApplyEyeMakeup_g01_c01.avi 80 0
input/avi/v_ApplyEyeMakeup_g01_c01.avi 96 0
input/avi/v_ApplyEyeMakeup_g01_c01.avi 112 0
input/avi/v_ApplyEyeMakeup_g01_c01.avi 128 0
input/avi/v_ApplyEyeMakeup_g01_c01.avi 144 0
input/avi/v_BaseballPitch_g01_c01.avi 0 0
input/avi/v_BaseballPitch_g01_c01.avi 16 0
input/avi/v_BaseballPitch_g01_c01.avi 32 0
input/avi/v_BaseballPitch_g01_c01.avi 48 0
input/avi/v_BaseballPitch_g01_c01.avi 64 0
input/avi/v_BaseballPitch_g01_c01.avi 80 0
```

Are there any misunderstandings about the above problem? Do you have any further suggestions?

Many thanks,
Nigel

**Comment by dutran** [comment]
That's correct. Frame number is starting from 1 for frames, but from 0 for videos. I think https://github.com/facebook/C3D/blob/master/examples/c3d_feature_extraction/prototxt/input_list_video.txt need to be updated.

**Comment by firmamentqj** [comment]
@dutran Please also update the User Guide:) Thank you very much!

**Comment by dutran** [comment]
@firmamentqj Thanks.
