### ISSUE TITLE
[mpeg4 @ 0x7fdca40003a0] too many thread_release_buffer calls!

### ISSUE THREAD

**Issue by Y2L** [facebook/C3D#203]
When I run this project using videos as data, it repotrs errors like this.

**Comment by dutran** [comment]
Hi @Y2L thanks for reporting the issue, I think this is somehow ffmpeg issue.

**Comment by Y2L** [comment]
Hi @dutran , I've installed the latest version ffmpeg on Ubuntu 14.04, but it still doesn't work.

**Comment by jasonustc** [comment]
@Y2L Another option: you can use ffmpeg to convert these videos into mp4 format, then it should work for video data.

**Comment by Y2L** [comment]
@jasonustc thank you, I've convert them into images.

**Comment by Y2L** [comment]
@jasonustc  Thank you, I've converted them into images.
