### ISSUE TITLE
run fine tuning test_net.bin error

### ISSUE THREAD

**Issue by Musicwire** [facebook/C3D#204]
I have got an error when run the test_net.bin.
E0303 09:52:36.501031 18221 test_net.cpp:35] Using GPU #1
I0303 09:52:36.503170 18221 net.cpp:76] Creating Layer data
I0303 09:52:36.503196 18221 net.cpp:112] data -> data
I0303 09:52:36.503209 18221 net.cpp:112] data -> label
..............
...............
...............
I0303 09:52:40.349706 18221 net.cpp:76] Creating Layer loss
I0303 09:52:40.349711 18221 net.cpp:86] loss <- fc8-2
I0303 09:52:40.349717 18221 net.cpp:86] loss <- label
I0303 09:52:40.349730 18221 net.cpp:154] loss needs backward computation.
I0303 09:52:40.349755 18221 net.cpp:183] Collecting Learning Rate and Weight Decay.
I0303 09:52:40.349771 18221 net.cpp:176] Network initialization done.
I0303 09:52:40.349776 18221 net.cpp:177] Memory required for Data 1130622240
E0303 09:52:40.754417 18221 test_net.cpp:45] Running 1000 iterations.
**my_test_finetuning.sh: line 1: 18221 segment fault               (core dumped) GLOG_logtostderr=1 ../../build/tools/test_net.bin ./model/my_finetuning_test.prototxt ./snapshot/my_finetune_iter_48000 1000 GPU** 1

**Comment by dutran** [comment]
Segment fault can be anything, but most of the time come from memory. Did you make it out of memory, if so, try to reduce mini-batch size to see what happen next.
