### ISSUE TITLE
train 3D convoluton architecture to get feature map

### ISSUE THREAD

**Issue by wuzhan11** [facebook/C3D#206]
I have trained a 3D architecture, but i do not know how to use the deconvolution to get the each layer feature map. 
Could you please tell me the solution about the question. 
Thank you in advance.

**Comment by dutran** [comment]
@wuzhan11 it is not implemented in the current version. If someone would like to lead the effort I can help, but I cannot not spend time implementing it myself for now.

**Comment by GFTQ** [comment]
@wuzhan11 Hi, i have the same question, do you make any progress?
