### ISSUE TITLE
Feature extraction with C3D1.1 & video files extract less features file than requested

### ISSUE THREAD

**Issue by InnovArul** [facebook/C3D#209]
I am trying to extract features of the HMDB51 videos using a pre-trained model. The command is as follows:

```
GLOG_logtostderr=1 ../../build/tools/extract_image_features.bin c3d_resnet18_hmdb51_feature_extraction.prototxt ./models/c3d_hmdb51_iter_20000.caffemodel 0 30 2226 featextract_prefix.lst prob pool5 res5b
```

There are totally 66770 instances of data (video clip) to extract features from. So, taking batch size as 30, there will be 2226 batches.
After feature extraction process is completed, the output says that 66770 features were extracted.

```
I0309 04:23:51.668015 94552 extract_image_features.cpp:130] Extracted features of 57030 images.
I0309 04:26:43.844326 94552 extract_image_features.cpp:130] Extracted features of 60030 images.
I0309 04:26:43.844382 94552 blocking_queue.cpp:49] Waiting for data
I0309 04:30:12.105039 94552 extract_image_features.cpp:130] Extracted features of 63030 images.
I0309 04:32:30.997515 94552 extract_image_features.cpp:130] Extracted features of 66030 images.
I0309 04:33:09.378058 94552 extract_image_features.cpp:134] Successfully extracted 66770 features!

```
But in the folder, only the features of 11130 data instances (video clip) were present. (i.e. 33390 files = 3 files (res5b, prob, pool5) per video clip).

I have attached the prototxt, input files list, prefix list for your reference.
Could you please let me know what might be the cause for this behavior.

[c3d_resnet18_hmdb51_feature_extraction.proto.txt](https://github.com/facebook/C3D/files/829264/c3d_resnet18_hmdb51_feature_extraction.proto.txt)
[featextract_files.lst.txt](https://github.com/facebook/C3D/files/829265/featextract_files.lst.txt)
[featextract_prefix.lst.txt](https://github.com/facebook/C3D/files/829266/featextract_prefix.lst.txt)

**Comment by dutran** [comment]
I cannot see your prototxt file, where is it?

**Comment by InnovArul** [comment]
@dutran thanks for being lightning fast. It took sometime for uploading.

**Comment by dutran** [comment]
@InnovArul In your c3d_resnet18_hmdb51_feature_extraction.proto.txt, you use batch size = 5, in the command line you use batch size = 30. You should fix either one of these and re-calcuate the number of mini-batches.
Suggestions, change batch size in prototxt file from 5 -> 30.

**Comment by saxenarohit** [comment]
@InnovArul Can you share the pre-trained c3d_hmdb51_iter_20000.caffemodel model

**Comment by InnovArul** [comment]
I have it here. See if it is helpful. As I remember, I have finetuned hmdb51 on split 1 configuration.
https://github.com/InnovArul/codesmart/tree/master/computer_vision/caffe-feat-extraction/hmdb51_feat_extraction
