### ISSUE TITLE
Check failed: num_axes() <= 4 (5 vs. 4) Cannot use legacy accessors on Blobs with > 4 axes

### ISSUE THREAD

**Issue by wjb123** [facebook/C3D#211]
I train my own network using the C3D1.1, but the code always reports these errors.
I0309 10:59:53.305505  2415 caffe.cpp:248] Starting Optimization
I0309 10:59:53.305531  2415 solver.cpp:273] Solving DeepConv3DNet_ucf101_finetuning
I0309 10:59:53.305543  2415 solver.cpp:274] Learning Rate Policy: step
I0309 10:59:53.306550  2415 solver.cpp:331] Iteration 0, Testing net (#0)
I0309 10:59:53.312021  2415 blocking_queue.cpp:49] Waiting for data
F0309 10:59:53.350008  2415 blob.hpp:140] Check failed: num_axes() <= 4 (5 vs. 4) Cannot use legacy accessors on Blobs with > 4 axes.
*** Check failure stack trace: ***
    @     0x7f64253558dd  google::LogMessage::Fail()
    @     0x7f642535777d  google::LogMessage::SendToLog()
    @     0x7f64253554cc  google::LogMessage::Flush()
    @     0x7f642535809e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f64259da535  caffe::Blob<>::LegacyShape()
    @     0x7f64259da647  caffe::Blob<>::offset()
    @     0x7f6425a39c83  caffe::VIDEO_MILLayer<>::Forward_cpu()
    @     0x7f64259aac12  caffe::Net<>::ForwardFromTo()
    @     0x7f64259aae2f  caffe::Net<>::Forward()
    @     0x7f6425b0aaba  caffe::Solver<>::Test()
    @     0x7f6425b0b52e  caffe::Solver<>::TestAll()
    @     0x7f6425b0d032  caffe::Solver<>::Step()
    @     0x7f6425b0d286  caffe::Solver<>::Solve()
    @           0x40a5b0  train()
    @           0x4079e2  main
    @     0x7f642435d76d  (unknown)
    @           0x408069  (unknown)

**Comment by dutran** [comment]
Can you share your prototxt file of the network?

**Comment by wjb123** [comment]
[c3d_mil_train.txt](https://github.com/facebook/C3D/files/829645/c3d_mil_train.txt)

**Comment by wjb123** [comment]
I solve it by modifying the limitation for num_axes(), so you can close it.

**Comment by applesleam** [comment]
Hi @wjb123 , I have the same problem with you. Can you provide more detail about your solution?

**Comment by moaljazaery** [comment]
I have the same error, how can I solve it? how can I modify the limitation for num_axes()?
