### ISSUE TITLE
fine-tune pre-trained(sports-1m) C3D model with my own dataset

### ISSUE THREAD

**Issue by wuzhan11** [facebook/C3D#213]
when i fine-tune pre-trained(sports-1m) C3D model with my own dataset, the error is occurred.

Check failed: ReadImageSequenceToVolumeDatum(file_list_[id].c_str(), start_frm_list_[id], label_list_[id], new_length, new_height, new_width, sampling_rate, &datum)

my database is composed of the clips. Each clips is composed of 10 frames and my picture suffix is .jpg.
I have tryed to solve the problem, but i don't know how to solve the problem.

can we use the C3D to fine-tuning the picture sequences?
could you tell me the answer or the possible methods of solving problems?

Thank you in advance!

**Comment by dutran** [comment]
@wuzhan11 C3D (v1.0) needs at least 16 frames per clip.
