### ISSUE TITLE
Why C3Dv1.1 isn't in need of mean file？

### ISSUE THREAD

**Issue by applesleam** [facebook/C3D#214]
In C3Dv1.0 there‘s a needing for **mean file** like provided fie `sports1m_train16_128_mean.binaryproto`.

Why in C3Dv1.1 this mean file isn't in need? or might compute in other place?
Will this have influence on computing efficiency or accuracy?

Can anybody help me with this question? Thanks a lot!

**Comment by dutran** [comment]
@applesleam we can do the volume mean, but it does not make much different, so we choose to use value mean instead.

**Comment by yanmengjia** [comment]
@dutran How to compute mean value to our own dataset in C3D v1.1? Thanks a lot!
