### ISSUE TITLE
fine-tune C3D with multi-label data

### ISSUE THREAD

**Issue by samiksome** [facebook/C3D#216]
Is it possible to train C3D with multi-label data.
Basically I am having trouble figuring out how to supply the multi-label input to C3D since the prescribed format simply allows for a single class.
Any help would be appreciated.
Thanks!

**Comment by dutran** [comment]
V1.1 allows you to use multiple labels. see here: https://github.com/facebook/C3D/blob/master/C3D-v1.1/src/caffe/proto/caffe.proto#L877-L878

Set use_multiple_label: true
num_of_labels: number of categories.

Format is the same, but instead 1 label, multiples are separated by commas.

<the same as be before> 1,8

Meaning this clip has labels 1 and 8 

Sorry for not putting this into document yes.

**Comment by samiksome** [comment]
@dutran Thank you very much!

**Comment by samiksome** [comment]
The label indexing starts from 0 right?
As in if I have 10 categories valid labels are 0-9.

**Comment by dutran** [comment]
this is correct.
