### ISSUE TITLE
Get weights using only conv3d_deepnetA_sport1m_iter_1900000

### ISSUE THREAD

**Issue by raghavgoyal14** [facebook/C3D#218]
Hi,

I'm trying to get the weights of convolution filters of the 3D-CNN model trained on sports-1m: `conv3d_deepnetA_sport1m_iter_1900000`. 

Code:
``` python
path_to_model = "../conv3d_deepnetA_sport1m_iter_1900000"

model = open(path_to_model, 'rb')
net_param = caffe.proto.caffe_pb2.NetParameter()
net_param.ParseFromString(model.read())

 for layers in range(1, len(net_param.layers)):
     print net_param.layers[layers].name  # layers name
     print net_param.layers[layers].type  # layers type
     for blob in range(0, len(net_param.layers[layers].blobs)):
         print np.array(net_param.layers[layers].blobs[blob].data) # weights and biases
```
The problem is that I'm using an earlier version of this repo and the `blobs` do not contain the shape information and spits out a 1-dimensional array which needs to be reshaped.

Do you have a correct permutation of shape information saved in `conv3d_deepnetA_sport1m_iter_1900000`? 
For e.g. `(out_channels, in_channels, depth, height, width)` 

Thanks in advance,
Raghav

**Comment by dutran** [comment]
For C3D v1.0, you can use this tool (https://github.com/facebook/C3D/blob/master/C3D-v1.0/tools/extract_learned_filters.cpp) to extract the learned filters.
