### ISSUE TITLE
How to load C3D features into numpy array？

### ISSUE THREAD

**Issue by MichaelXin** [facebook/C3D#22]
Hi,
I want to read a binary blob of C3D feature into a numpy array.
I have readed the matlab script， but I don't really get its meaning.
What is the stucture of *.fc6-1 file? Are the first five 32 bytes recorded the num, chanel, length, height and width?

**Comment by dutran** [comment]
@MichaelXin The format is:
5 32-bit integers: num, chanel, length, height, width. (record the size of the blob)
Then followed by the data of (num * channel * length * height * width) each data is a 32-bit float.

**Comment by dutran** [comment]
@MichaelXin check out the script to read blob which preserving blob shape: https://github.com/facebook/C3D/blob/master/examples/c3d_feature_extraction/script/read_binary_blob_preserve_shape.m
You can write similar Python script. Note that MATLAB uses column order, while numpy uses row order. Thus, you don't need to reshape (as I used in MATLAB).

**Comment by SuperLee506** [comment]
@MichaelXin  Hi,I'm confused about load the "fc6-1"features.The  feature's number is 4096，so why we shoud reshape the data size.
Thanks.

**Comment by Prithviraj7** [comment]
Could you please give me a python script for read_binary_blob and read_binary_bob_preserve_shape.m ?

**Comment by gbpcosta** [comment]
Hi, I made a python function that might help: https://gist.github.com/gbpcosta/22f9679c1984473f2971e4d4d2d60aa9

**Comment by Prithviraj7** [comment]
@gbpcosta Thanks a lot! :)
