### ISSUE TITLE
adding C3D-v1.1/examples/c3d_feature_extraction

### ISSUE THREAD

**Issue by kevinlyu1** [facebook/C3D#224]
I was wondering where I could get the c3d_feature_extraction folder for "v1.1" I am trying to run `sh c3d_sport1m_feature_extraction_frm.sh` to check if everythings working correctly, but I can't find it.

**Comment by dutran** [comment]
@kevinlyu1 here it is https://github.com/facebook/C3D/tree/master/C3D-v1.1/examples/c3d_ucf101_feature_extraction

**Comment by kevinlyu1** [comment]
So I would just run the "feature_extraction.sh" in that folder?
