### ISSUE TITLE
Getting the UCF101 frm dataset

### ISSUE THREAD

**Issue by kevinlyu1** [facebook/C3D#225]
I was wondering if you have a link for the dataset? So far I am using the dataset at "http://crcv.ucf.edu/data/UCF101.php" and clicking where it says "The UCF101 data set can be downloaded by clicking here", but this gives me `.avi` files and I need `.jpg`. I am running into an error when trying to run the `feature_extraction.sh` which says `Could not open or find file /home/klyu/computerVision/C3D/C3D-v1.1/examples/ucf101/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01//000001.jpg`. The path is different from the one for trandu's and I have changed it to where I downloaded the above dataset too.
If you can help me figure out why the `feature_extraction.sh` isn't able to pull the right `.jpg` or if I have the wrong dataset and where to get it that'd be great?

**Comment by dutran** [comment]
you can use ffmpeg to extract frames, in order to get high quality frames you should use -q:v in your arguments with ffmpeg.

**Comment by kevinlyu1** [comment]
Okay that sounds great. Thanks for the help!
