### ISSUE TITLE
Action Recognition Demo

### ISSUE THREAD

**Issue by kevinlyu1** [facebook/C3D#227]
I was wondering if you had an action recognition demo? I saw there was the web_demo, which did classification, but not action classification. Just wondering if there was a demo that's plug and play.

**Comment by dutran** [comment]
There is not such a demo yet. Sorry, I could not have anytime for building such a demo.

**Comment by kevinlyu1** [comment]
Okay no problem. Thanks for the quick responses.

**Comment by kevinlyu1** [comment]
@nicebaby This wasn't a problem with their code, just that they did not have it. I don't believe that I implemented an action recognition demo. If you have any more questions feel free to let me know.

**Comment by nicebaby** [comment]
@kevinlyu1 I'm very sorry that my word is not accurate. I just want to know if you implement this demo.

**Comment by kevinlyu1** [comment]
I did not end up implementing it.
