### ISSUE TITLE
Question about action recognition experiment

### ISSUE THREAD

**Issue by minhkv** [facebook/C3D#229]
Hi dutran,
I have a question about the architecture you mentioned in the action recognition experiment. What's the difference between C3D with 1 nets and 3 nets? And how do you combined C3D with iDT to produce the best result on UCF 101.
Thank you,

**Comment by dutran** [comment]
1. We have 3 nets, simply average predictions of these 3 nets.
2. Simply concatenate C3D features with iDT features, then do linear SVM.

**Comment by minhkv** [comment]
Thank you very much!
