### ISSUE TITLE
 C3Dv1.0 can use graphics card gtx1080

### ISSUE THREAD

**Issue by wuzhan11** [facebook/C3D#230]
I would like to know whether C3Dv1.0 can use graphics card gtx1080.
if C3Dv1.0 can use graphics card gtx1080,would you tell me the solution?

Thank you in advance!

**Comment by dutran** [comment]
I did not try on this card, could you try and give us an update here? I think it may work as long as CUDA is properly installed. In case memory is not enough, you can reduce the batch size a little bit.

**Comment by escorciav** [comment]
Yes, it's possible to use GTX1080. I manage to compile both versions with CUDA 7.5. I just tested version 1.1. Using the resnet18 model, your batch size should be around 8-12.

@dutran, lemme know if you wanna check version 1.0? Could you also tell me if u are using CUDA8? what about CUDNN?

**Comment by escorciav** [comment]
my question about CUDNN is solved [here](https://github.com/facebook/C3D/issues/244#issuecomment-292853942). TLDR, there is an error in CUDNN with 5D tensors. Regarding CUDA8, I tested it and it works without problem.

**Comment by dutran** [comment]
@escorciav Thanks for testing it on GTX1080. It works fine with CUDA 8.0 and I have not tried CUDNN yet.
