### ISSUE TITLE
How to combine clip-level accuracy to get video-level accuracy, in action recognition?

### ISSUE THREAD

**Issue by misunusc** [facebook/C3D#232]
Hi Du Tran,

In your paper, for the section of "action recognition", the reported results are about clip-level or video-level?
Here is my understanding:
The C3D extracts feature descriptor for every 16 frame long clip. And, by using linear SVM, it would give the classification result for each clip. Then, how to get the result for each whole video?

Look forward to your reply.
Thanks a lot.

**Comment by dutran** [comment]
For UCF101, we average pooled fc6 features, l2-normalized, then linear SVM to classify the actions. We do not report clip accuracy for UCF101. For Sports1M, just simply average clip predictions to make video prediction.
