### ISSUE TITLE
question about fine-tune C3D

### ISSUE THREAD

**Issue by mangdian** [facebook/C3D#233]
Dear Du Tran,
 The VIDEO_DATA layer is new in CAFFE C3D.Now I am trying to fine-tune C3D on ActivityNet dataset.Would you please tell me the format of file path of trainlist?
![9nkp 2vbl9cfb80yb9 ci p](https://cloud.githubusercontent.com/assets/18326098/24436845/551277e0-1470-11e7-87ef-26d5c49d6eea.png)
why the frames is extracted every 16 frames?
the only thing I need to do to fine-tune C3D is adjust the trainlist file?

**Comment by dutran** [comment]
currently handy-fixed (a bit hacky) as jpg files (see https://github.com/facebook/C3D/blob/master/C3D-v1.1/src/caffe/util/image_io.cpp#L335), but you can easily adjust to whatever work for you.
