### ISSUE TITLE
Could not open or find file 

### ISSUE THREAD

**Issue by wuzhan11** [facebook/C3D#234]
[log.txt](https://github.com/facebook/C3D/files/881762/log.txt)
I have tryed to use the C3D V1.1 for training my own database in the correct path I think, but it occurs error——Could not open or find file /home/chentong/C3D-master/C3D-v1.1﻿/examples/NIRfacebody_320/train_test/train/Anger/NIR_01/000001.jpg

the log text has been uploaded.
hope to get the solution.

**Comment by dutran** [comment]
it should be %06.jpg you used %07d.jpg, either rename your files or modify this line https://github.com/facebook/C3D/blob/master/C3D-v1.1/src/caffe/util/image_io.cpp#L335

**Comment by wuzhan11** [comment]
I find my files's name is not wrong I just feel, please help me to check the error exist in my files.
thank you very much! this is my data and my label.
![data](https://cloud.githubusercontent.com/assets/26197689/24554836/93546566-1661-11e7-89aa-3dcc50d7f2da.JPG)

[train_01.txt](https://github.com/facebook/C3D/files/885953/train_01.txt)

**Comment by dutran** [comment]
1) when you do ls /home/chentong/C3D-master/C3D-v1.1﻿/examples/NIRfacebody_320/train_test/train/Anger/NIR_01/ ?
2) can you share your full error log?
3) can you share your data layer prototxt

**Comment by wuzhan11** [comment]
[conv3d_ucf101_train.prototxt.txt](https://github.com/facebook/C3D/files/887692/conv3d_ucf101_train.prototxt.txt)
[log.txt](https://github.com/facebook/C3D/files/887691/log.txt)

this is my log and my conv3d_ucf101_train.prototxt
when I run the conv3d_ucf101_train.prototxt,  the log always display the error-"Could not open or find file /home/chentong/C3D-master/C3D-v1.1﻿/examples/NIRfacebody_320/train_test/train/Anger/NIR_01/000001.jpg"  until i stop manually.



thank you very much for sovling my error.

**Comment by dutran** [comment]
The log file says:

^CI0402 22:07:21.101649 16044 solver.cpp:448] Snapshotting to binary proto file /home/chentong/C3D-master/C3D-v1.1/examples/NIRfacebody_320/caffemodel/NIRbody_iter_307.caffemodel
I0402 22:07:21.577457 16044 sgd_solver.cpp:273] Snapshotting solver state to binary proto file /home/chentong/C3D-master/C3D-v1.1/examples/NIRfacebody_320/caffemodel/NIRbody_iter_307.solverstate
I0402 22:07:21.636520 16044 solver.cpp:295] Optimization stopped early.
I0402 22:07:21.636538 16044 caffe.cpp:259] Optimization Done.


which means it is running fine, and you stopped it Ctrl+C, current snapshot is at /home/chentong/C3D-master/C3D-v1.1/examples/NIRfacebody_320/caffemodel/NIRbody_iter_307.caffemodel

**Comment by wuzhan11** [comment]
Does the log always show the error or just the warning -‘’Could not open or find file /home/chentong/C3D-master/C3D-v1.1﻿/examples/NIRfacebody_320/train_test/train/Anger/NIR_01/000001.jpg"  is no problem?

**Comment by dutran** [comment]
@wuzhan11 In training, we allow to miss some examples, in testing (mainly feature extraction), we don't allow to miss examples, which may cause miss-alignment between computed features and feature prefix.

To get rid of the warnings, you really have to verify the missing examples and remove them from the list (or fix them, make them readable for the data layer).
