### ISSUE TITLE
Converting mean binaryproto file to numpy array

### ISSUE THREAD

**Issue by samiksome** [facebook/C3D#235]
I was trying to convert https://github.com/facebook/C3D/blob/master/C3D-v1.0/examples/c3d_feature_extraction/sport1m_train16_128_mean.binaryproto to a numpy array so that I could port it for usage in v1.1

Now the problem is the blob contains 1050624 elements in blob.data whereas (blob.num,blob.channel,blob.height,blob.width) is only (1,3,128,171) which means a total of 65664 elements. The actual number of elements present are 16 times as much.

I believe that this is because of having 16 frames in input layer.

So, how do I convert this to a v1.1 blob? Should I keep it similar in structure to the original blob?. i.e. actually have 1050624 elements but set (n,c,h,w) to (1,3,128,171)?

**Comment by dutran** [comment]
Which script did you use to convert, its size should be (1,3,16,128,171), you may miss on dimension, Perhaps your script works for 4D tensor only, but this is 5D tensor.

**Comment by samiksome** [comment]
I was loading it up in python as follows:

```python
import caffe
import numpy as np
b = caffe.proto.caffe_pb2.BlobProto()
b.ParseFromString(open('sport1m_train16_128.binaryproto','rb').read())
a = caffe.io.blobproto_to_array(b)
```

**Comment by samiksome** [comment]
I have another issue.

While loading C3D v1.0 I find that the weights of a conv3d layer are 4d. For example 'conv1a' has shape (64,3,3,3)

However when the same model is converted for v1.1 and loaded weights are 5d. 'conv1a' becomes (64,3,3,3,3)

These are the shapes of the param[0] fields

**Comment by samiksome** [comment]
Nevermind, I figured out the problem.

I was using the python interface which was not updated to return length field. I updated the python wrapper and now it works

**Comment by samiksome** [comment]
Just to be sure, the weights are in `(num, channels, length, height, width)` right?

**Comment by whmin** [comment]
@samiksome Hi，I met the same problem,can not convert bianry file to npy file.Can you help me how to write the python wrapper?
This is my convert code.
![2018-01-22 16 58 08](https://user-images.githubusercontent.com/23375545/35212562-87b05562-ff95-11e7-9935-5502f96f680d.png)
The error showed as 
![2018-01-22 16 58 24](https://user-images.githubusercontent.com/23375545/35212609-afeaaa78-ff95-11e7-9081-091ee6e80d6f.png)
Thank you very much!!!

**Comment by meisa233** [comment]
> @samiksome Hi，I met the same problem,can not convert bianry file to npy file.Can you help me how to write the python wrapper?
> This is my convert code.
> ![2018-01-22 16 58 08](https://user-images.githubusercontent.com/23375545/35212562-87b05562-ff95-11e7-9935-5502f96f680d.png)
> The error showed as
> ![2018-01-22 16 58 24](https://user-images.githubusercontent.com/23375545/35212609-afeaaa78-ff95-11e7-9081-091ee6e80d6f.png)
> Thank you very much!!!

Maybe it's to late.
You can see https://github.com/chuckcho/c3d-tensorflow2/blob/master/convert_mean.py
