### ISSUE TITLE
How to test the finetuning result on resnet18

### ISSUE THREAD

**Issue by vra** [facebook/C3D#237]
Hi dutran,
I run the script ` finetuning_ucf101.sh` in `C3D-v1.1/examples/c3d_ucf101_finetuning` dir, it seems that this script only runs the training phase since the `test_state` is commented in `solver_r2.prototxt`. So could you please tell me how to run the test phase?  Great thanks.

**Comment by dutran** [comment]
sent a script. Cheers.

**Comment by vra** [comment]
Thanks!😊 Hope to see your new paper or  report soon.

**Comment by KervinBill** [comment]
Hi，could  you please send me the test script ? Many thanks.
