### ISSUE TITLE
Could not open or find file2

### ISSUE THREAD

**Issue by wuzhan11** [facebook/C3D#238]
I find my files's name is not wrong using C3D-v1.1 I just feel, please help me to check the error exist in my files.
thank you very much! this is my data and my label.
[train_01.txt](https://github.com/facebook/C3D/files/887229/train_01.txt)
![data](https://cloud.githubusercontent.com/assets/26197689/24573591/dd7fc7f6-16b7-11e7-89c6-4da8c6aa9ec2.JPG)

**Comment by dutran** [comment]
follow up on #234
