### ISSUE TITLE
How to run the test phase?

### ISSUE THREAD

**Issue by KervinBill** [facebook/C3D#239]
Hi, dutran,
My question is as same as #237  ,could you please send me that script ?  Many thanks.

**Comment by KervinBill** [comment]
#237

**Comment by vra** [comment]
Actually, dutran didn't send me a script, he just added it into this repo, you can check it at <https://github.com/facebook/C3D/blob/master/C3D-v1.1/examples/c3d_ucf101_finetuning/testing_ucf101.sh>.

**Comment by KervinBill** [comment]
@vra thanks~

**Comment by KervinBill** [comment]
@vra My database has 2000 videos, I want use C3D, do you know how to do 3 fold Cross-validation ?
