### ISSUE TITLE
C3D Feature Extraction: Frame-based work but Video doesn't, part2

### ISSUE THREAD

**Issue by ycjlin** [facebook/C3D#24]
Here is my result of running Video extraction script (I've passed the frame script):
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0727 22:44:11.561401 28087 extract_image_features.cpp:55] Using GPU #0
I0727 22:44:11.563448 28087 net.cpp:76] Creating Layer data
I0727 22:44:11.563490 28087 net.cpp:112] data -> data
I0727 22:44:11.563510 28087 net.cpp:112] data -> label
I0727 22:44:11.563531 28087 video_data_layer.cpp:283] Opening file prototxt/input_list_video.txt
I0727 22:44:11.563642 28087 video_data_layer.cpp:317] A total of 16 video chunks.
[mpeg4 @ 0x51b84c0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x51b84c0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x51e93a0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x51eea20] Invalid and inefficient vfw-avi packed B frames detected
I0727 22:44:11.592236 28087 video_data_layer.cpp:365] output data size: 50,3,16,112,112
I0727 22:44:11.592283 28087 video_data_layer.cpp:387] Loading mean file fromsport1m_train16_128_mean.binaryproto
I0727 22:44:11.638545 28087 net.cpp:127] Top shape: 50 3 16 112 112 (30105600)
I0727 22:44:11.638589 28087 net.cpp:127] Top shape: 50 1 1 1 1 (50)
I0727 22:44:11.638603 28087 net.cpp:159] data does not need backward computation.
I0727 22:44:11.638622 28087 net.cpp:76] Creating Layer conv1a
I0727 22:44:11.638633 28087 net.cpp:86] conv1a <- data
I0727 22:44:11.638653 28087 net.cpp:112] conv1a -> conv1a
I0727 22:44:11.639158 28087 net.cpp:127] Top shape: 50 64 16 112 112 (642252800)
I0727 22:44:11.639184 28087 net.cpp:154] conv1a needs backward computation.
I0727 22:44:11.639199 28087 net.cpp:76] Creating Layer relu1a
I0727 22:44:11.639209 28087 net.cpp:86] relu1a <- conv1a
I0727 22:44:11.639219 28087 net.cpp:100] relu1a -> conv1a (in-place)
I0727 22:44:11.639231 28087 net.cpp:127] Top shape: 50 64 16 112 112 (642252800)
I0727 22:44:11.639241 28087 net.cpp:154] relu1a needs backward computation.
I0727 22:44:11.639253 28087 net.cpp:76] Creating Layer pool1
I0727 22:44:11.639262 28087 net.cpp:86] pool1 <- conv1a
I0727 22:44:11.639272 28087 net.cpp:112] pool1 -> pool1
I0727 22:44:11.639292 28087 net.cpp:127] Top shape: 50 64 16 56 56 (160563200)
I0727 22:44:11.639308 28087 net.cpp:154] pool1 needs backward computation.
I0727 22:44:11.639322 28087 net.cpp:76] Creating Layer conv2a
I0727 22:44:11.639331 28087 net.cpp:86] conv2a <- pool1
I0727 22:44:11.639343 28087 net.cpp:112] conv2a -> conv2a
[mpeg4 @ 0x7f5770002be0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f5770002be0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f57700057a0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f5770002460] Invalid and inefficient vfw-avi packed B frames detected
I0727 22:44:11.650568 28087 net.cpp:127] Top shape: 50 128 16 56 56 (321126400)
I0727 22:44:11.650612 28087 net.cpp:154] conv2a needs backward computation.
I0727 22:44:11.650629 28087 net.cpp:76] Creating Layer relu2a
I0727 22:44:11.650641 28087 net.cpp:86] relu2a <- conv2a
I0727 22:44:11.650653 28087 net.cpp:100] relu2a -> conv2a (in-place)
I0727 22:44:11.650665 28087 net.cpp:127] Top shape: 50 128 16 56 56 (321126400)
I0727 22:44:11.650674 28087 net.cpp:154] relu2a needs backward computation.
I0727 22:44:11.650686 28087 net.cpp:76] Creating Layer pool2
I0727 22:44:11.650696 28087 net.cpp:86] pool2 <- conv2a
I0727 22:44:11.650706 28087 net.cpp:112] pool2 -> pool2
I0727 22:44:11.650717 28087 net.cpp:127] Top shape: 50 128 8 28 28 (40140800)
I0727 22:44:11.650727 28087 net.cpp:154] pool2 needs backward computation.
I0727 22:44:11.650739 28087 net.cpp:76] Creating Layer conv3a
I0727 22:44:11.650749 28087 net.cpp:86] conv3a <- pool2
I0727 22:44:11.650759 28087 net.cpp:112] conv3a -> conv3a
[mpeg4 @ 0x7f57700236a0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f57700236a0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f57700236a0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f5770003e00] Invalid and inefficient vfw-avi packed B frames detected
I0727 22:44:11.682303 28087 net.cpp:127] Top shape: 50 256 8 28 28 (80281600)
I0727 22:44:11.682332 28087 net.cpp:154] conv3a needs backward computation.
I0727 22:44:11.682344 28087 net.cpp:76] Creating Layer relu3a
I0727 22:44:11.682353 28087 net.cpp:86] relu3a <- conv3a
I0727 22:44:11.682361 28087 net.cpp:100] relu3a -> conv3a (in-place)
I0727 22:44:11.682369 28087 net.cpp:127] Top shape: 50 256 8 28 28 (80281600)
I0727 22:44:11.682376 28087 net.cpp:154] relu3a needs backward computation.
I0727 22:44:11.682385 28087 net.cpp:76] Creating Layer conv3b
I0727 22:44:11.682392 28087 net.cpp:86] conv3b <- conv3a
I0727 22:44:11.682400 28087 net.cpp:112] conv3b -> conv3b
[mpeg4 @ 0x7f57700236a0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f57700236a0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f57700236a0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f5770004480] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f57700236a0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f57700236a0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f57700236a0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f57702ddde0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f577006dd00] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f577006dd00] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f577006dd00] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f577001eca0] Invalid and inefficient vfw-avi packed B frames detected
I0727 22:44:11.740874 28087 net.cpp:127] Top shape: 50 256 8 28 28 (80281600)
I0727 22:44:11.740916 28087 net.cpp:154] conv3b needs backward computation.
I0727 22:44:11.740928 28087 net.cpp:76] Creating Layer relu3b
I0727 22:44:11.740937 28087 net.cpp:86] relu3b <- conv3b
I0727 22:44:11.740947 28087 net.cpp:100] relu3b -> conv3b (in-place)
I0727 22:44:11.740955 28087 net.cpp:127] Top shape: 50 256 8 28 28 (80281600)
I0727 22:44:11.740962 28087 net.cpp:154] relu3b needs backward computation.
I0727 22:44:11.740970 28087 net.cpp:76] Creating Layer pool3
I0727 22:44:11.740978 28087 net.cpp:86] pool3 <- conv3b
I0727 22:44:11.740985 28087 net.cpp:112] pool3 -> pool3
I0727 22:44:11.740995 28087 net.cpp:127] Top shape: 50 256 4 14 14 (10035200)
I0727 22:44:11.741003 28087 net.cpp:154] pool3 needs backward computation.
I0727 22:44:11.741011 28087 net.cpp:76] Creating Layer conv4a
I0727 22:44:11.741019 28087 net.cpp:86] conv4a <- pool3
I0727 22:44:11.741026 28087 net.cpp:112] conv4a -> conv4a
[mpeg4 @ 0x7f577006dd00] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f577006dd00] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f577006dd00] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f577006af00] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f577006dd00] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f577006dd00] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f577006dd00] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f5770781ba0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f577006dd00] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f577006dd00] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f577006dd00] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f577001d940] Invalid and inefficient vfw-avi packed B frames detected
I0727 22:44:11.857704 28087 net.cpp:127] Top shape: 50 512 4 14 14 (20070400)
I0727 22:44:11.857738 28087 net.cpp:154] conv4a needs backward computation.
I0727 22:44:11.857750 28087 net.cpp:76] Creating Layer relu4a
I0727 22:44:11.857758 28087 net.cpp:86] relu4a <- conv4a
I0727 22:44:11.857767 28087 net.cpp:100] relu4a -> conv4a (in-place)
I0727 22:44:11.857775 28087 net.cpp:127] Top shape: 50 512 4 14 14 (20070400)
I0727 22:44:11.857784 28087 net.cpp:154] relu4a needs backward computation.
I0727 22:44:11.857791 28087 net.cpp:76] Creating Layer conv4b
I0727 22:44:11.857799 28087 net.cpp:86] conv4b <- conv4a
I0727 22:44:11.857805 28087 net.cpp:112] conv4b -> conv4b
[mpeg4 @ 0x7f5770555fa0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f5770555fa0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f5770555fa0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f5770022b20] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f5770555fa0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f5770555fa0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f5770555fa0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f5770004c60] Invalid and inefficient vfw-avi packed B frames detected
I0727 22:44:12.026093 28113 image_io.cpp:143] No data at frame 92
F0727 22:44:12.026762 28113 video_data_layer.cpp:123] Check failed: read_status Testing must not miss any example
*** Check failure stack trace: ***

Is this due to that openCV was not compiled with enable-shared flag ON?
I've installed openCV and ffmpeg 0.8.17-4:0.8.17-0ubuntu0.12.04.1.
But I'm not sure if openCV was installed with enable-shared flag ON.
Any suggestion is welcome. Thank you.

**Comment by dutran** [comment]
You may want to compile both ffmpeg and opencv from source and make sure --enable-shared flag is ON, so that openCV can use codecs from ffmpeg. This is known to work for this issue.
