### ISSUE TITLE
How can I use crop layer in C3D v1.0

### ISSUE THREAD

**Issue by yanmengjia** [facebook/C3D#241]
I need to fine-tuning the conv3d_deepnetA_sport1m_iter_1900000, so I have to deal with whole process on C3D v1.0. However, I also need to use crop layer which is not include in C3D v1.0.  I found that I can not directly copy the crop_layer in C3D v1.1 to C3D v1.1. How can I use crop layer in C3D v1.0?

**Comment by dutran** [comment]
@yanmengjia can you use model in v1.1 to fine-tune, it is known to be more accurate than the v1.0 model. In case you need the model in 1.0, I think you can wait to use the converting model (#210)

**Comment by yanmengjia** [comment]
@dutran thank you for your reply. I just read your C3D paper, and found that the C3D v1.1's finetuning architecture is quite different from that paper. I am not sure the new architecture is what I need. Do you have a new paper about C3D v1.1's architecture? Or there's any document I can get to know about this architecture? Thank you.
