### ISSUE TITLE
Question about top_k_

### ISSUE THREAD

**Issue by KervinBill** [facebook/C3D#242]
@dutran Hi, dutran, my data has 3classes, less than 5 classes, when I train it, 
` CHECK_LE(top_k_, bottom[0]->count() / bottom[0]->num())
      << "top_k must be less than or equal to the number of classes."`
Could you please tell me how to solve it? Thanks.

**Comment by dutran** [comment]
@KervinBill you just simply remove that accuracy layer (the top 5), just keep only the top 1.
