### ISSUE TITLE
Error caused by dimension checking of blob.hpp

### ISSUE THREAD

**Issue by polyuxdq** [facebook/C3D#244]
Hello, I met some problem about the dimension checking of the blob.hpp file. When I was runing the finetuning example as well as the simple training, it is reported that the input exceeded 4. The input should be like number * channel/features * depth(length) * height * width, but I notice that the blob.hpp has limited the dimension and blob.cpp does not deal with length.
I figured out this problem by changing the dimension limit to be 5 but did not change the blob.cpp. 
I am wondering whether this issue will influence the model training. Or did I input the data in a wrong way? Thanks.

Here is the error message:

I0405 08:34:12.681352  7086 layer_factory.hpp:77] Creating layer data
I0405 08:34:12.681434  7086 net.cpp:84] Creating Layer data
I0405 08:34:12.681483  7086 net.cpp:380] data -> data
I0405 08:34:12.681548  7086 net.cpp:380] data -> label
I0405 08:34:12.682114  7086 video_data_layer.cpp:67] Opening file train_01.lst
I0405 08:34:12.682222  7086 video_data_layer.cpp:140] A total of 1 video chunks.
I0405 08:34:13.122795  7086 video_data_layer.cpp:182] output data size: 1,3,16,112,112
I0405 08:34:13.148277  7086 net.cpp:122] Setting up data
I0405 08:34:13.148332  7086 net.cpp:129] Top shape: 1 3 16 112 112 (602112)
I0405 08:34:13.148344  7086 net.cpp:129] Top shape: 1 (1)
I0405 08:34:13.148350  7086 net.cpp:137] Memory required for data: 2408452
I0405 08:34:13.148360  7086 layer_factory.hpp:77] Creating layer conv1a
I0405 08:34:13.148391  7086 net.cpp:84] Creating Layer conv1a
I0405 08:34:13.148402  7086 net.cpp:406] conv1a <- data
I0405 08:34:13.148424  7086 net.cpp:380] conv1a -> conv1a
I0405 08:34:13.150471  7086 net.cpp:122] Setting up conv1a
I0405 08:34:13.150504  7086 net.cpp:129] Top shape: 1 64 16 112 112 (12845056)
I0405 08:34:13.150513  7086 net.cpp:137] Memory required for data: 53788676
I0405 08:34:13.150537  7086 layer_factory.hpp:77] Creating layer relu1a
I0405 08:34:13.150578  7086 net.cpp:84] Creating Layer relu1a
I0405 08:34:13.150589  7086 net.cpp:406] relu1a <- conv1a
I0405 08:34:13.150599  7086 net.cpp:367] relu1a -> conv1a (in-place)
F0405 08:34:13.879493  7086 blob.hpp:140] Check failed: num_axes() <= 4 (5 vs. 4) Cannot use legacy accessors on Blobs with > 4 axes.

**Comment by saltsuger** [comment]
hello, I met the problem same with you, do you solve it?

**Comment by polyuxdq** [comment]
@saltsuger I modified the include/caffe/blob.hpp to increase the limitation of dimension. The network can be trained and the dimension of each layer seems to be correct. But I am not sure for the solution.

    CHECK_LE(num_axes(), 4)
        << "Cannot use legacy accessors on Blobs with > 4 axes.";
    CHECK_LT(index, 4);
    CHECK_GE(index, -4);

**Comment by saltsuger** [comment]
@polyuxdq  I used the **v1.0** successfully，you can try it.

**Comment by escorciav** [comment]
@polyuxdq, I also found the same error. Did you compile with CUDNN?
I removed it and it disappears.

**Comment by dutran** [comment]
@polyuxdq ReLU with CuDNN need to be modify to adapt to 5D tensor. Just turn off it for now and compile again. @escorciav thanks!

**Comment by polyuxdq** [comment]
@dutran @escorciav Thank you very much!

**Comment by srbnghosh99** [comment]
I am getting the same error and my CuDNN is also on. how to turnoff CuDNN? @polyuxdq @escorciav

**Comment by srbnghosh99** [comment]
what is v1.0 ? @saltsuger

**Comment by escorciav** [comment]
- Disable cudnn while you are installing. Check the cmake (try `ccmake` or something similar that brings up a graphical CLI).

- By v1.0, I meant the previous version and models of C3D.

For me, it was easier because I don't have the libraries and headers tied to the folders of cuda.

Check out [this](https://github.com/escorciav/C3D/tree/build-conda) if you are familiar with conda. Good luck!
