### ISSUE TITLE
Extracting features from matlab command window

### ISSUE THREAD

**Issue by Girmaw** [facebook/C3D#245]
Hi Dutran,

Thanks for the material. 
I can successfully extract features both in GPU and CPU mode from ubuntu terminal.
Would it be possible to have a matlab equivalent of extract_C3D_feature.py?
when I try it from matlab command as  e.g., system(sprintf('sh c3d_sport1m_feature_extraction_frm.sh'))
Error: 
....
v_BaseballPitch_g01_c01/000107.jpg
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0406 14:00:38.053948 19911 extract_image_features.cpp:64] Using GPU #0
I0406 14:00:38.055227 19911 net.cpp:76] Creating Layer data
I0406 14:00:38.055243 19911 net.cpp:112] data -> data
I0406 14:00:38.055260 19911 net.cpp:112] data -> label
I0406 14:00:38.055271 19911 video_data_layer.cpp:283] Opening file prototxt/input_list_frm.txt
I0406 14:00:38.055348 19911 video_data_layer.cpp:317] A total of 16 video chunks.
I0406 14:00:38.055374 19911 video_data_layer.cpp:344] read video from input/frm/v_ApplyEyeMakeup_g01_c01/
F0406 14:00:38.055465 19911 video_data_layer.cpp:346] Check failed: ReadImageSequenceToVolumeDatum(file_list_[id].c_str(), start_frm_list_[id], label_list_[id], new_length, new_height, new_width, sampling_rate, &datum) 
*** Check failure stack trace: ***

Any hint? 
Thanks

**Comment by dutran** [comment]
both matlab and python wrappers need a little bit more work to modify the input blobs.
