### ISSUE TITLE
Check failed: axis_index < num_axes() (0 vs. 0) axis 0 out of range for 0-D Blob with shape (1)

### ISSUE THREAD

**Issue by yanmengjia** [facebook/C3D#247]
When I try to extract features from my finetuning model using C3D v1.1, this error happened. I found that actually my datasets's frame is one channel, but when I do finetuning and feature extraction, it shows that input's channel still 3. 

And I want to output the loss. I think it may be the problem. How can I output loss?

Could anybody help me? Thank you so much.

**Comment by dutran** [comment]
use feature extraction (extract_image_features) tool to extract the loss.
