### ISSUE TITLE
Reason for using jpg images only

### ISSUE THREAD

**Issue by rohitqut** [facebook/C3D#249]
Hello,

In C3D userguide its suggested to use '%6d.jpg'. Can I know the reason behind it or can we also use other image formats like png for feature extraction? If it is possible so, then in which source file I need to make changes from jpg to png?

**Comment by dutran** [comment]
this is a ugly hack, the right way is to allow users to choose image extension that they use as one option in data layer. For a quick modification, you can modify here https://github.com/facebook/C3D/blob/master/C3D-v1.1/src/caffe/util/image_io.cpp#L335. I will adjust the data layer soon.
