### ISSUE TITLE
feature extraction custom frame size

### ISSUE THREAD

**Issue by KVinken** [facebook/C3D#251]
I am trying to use the pre-trained sport1m model for feature extraction on my own videos. My video frames are square-sized. I guess I could use:

crop_size: 0
new_height: 112
new_width:  112

However I guess this conflicts with the mean_file size. Is there any way I can make it work with the provided mean_file: "sport1m_train16_128_mean.binaryproto"?

Here is the output:

WARNING: Logging before InitGoogleLogging() is written to STDERR
E0425 15:18:40.559752   914 common.cpp:31] Cannot create Cublas handle. Cublas won't be available.
E0425 15:18:40.603746   914 common.cpp:38] Cannot create Curand generator. Curand won't be available.
E0425 15:18:40.603788   914 extract_image_features.cpp:68] Using CPU
I0425 15:18:40.605567   914 net.cpp:76] Creating Layer data
I0425 15:18:40.605587   914 net.cpp:112] data -> data
I0425 15:18:40.605598   914 net.cpp:112] data -> label
I0425 15:18:40.605638   914 video_data_layer.cpp:283] Opening file prototxt/input_list_frm.txt
I0425 15:18:40.620018   914 video_data_layer.cpp:317] A total of 180 video chunks.
I0425 15:18:40.620033   914 video_data_layer.cpp:344] read video from input/frm/mov01_filtered/
I0425 15:18:40.641546   914 video_data_layer.cpp:365] output data size: 50,3,16,112,112
I0425 15:18:40.641564   914 video_data_layer.cpp:387] Loading mean file from sport1m_train16_128_mean.binaryproto
F0425 15:18:40.684722   914 video_data_layer.cpp:394] Check failed: data_mean_.height() == datum_height_ (128 vs. 112)
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by dutran** [comment]
You can use tool e.g. https://github.com/facebook/C3D/blob/master/C3D-v1.0/tools/compute_volume_mean_from_list.cpp or https://github.com/facebook/C3D/blob/master/C3D-v1.0/tools/compute_volume_mean_from_list_videos.cpp to compute your mean. Are you using 1.0? As 1.1 we only use mean value.

**Comment by KVinken** [comment]
Thanks so much for the fast response! I am using v1.0 at the moment, because I am interested in the VGG architecture and not Resnet...

With this tool you mention I guess can only calculate means of my own videos (unless I download the whole sport1m, which would be a bit overkill), right? Won't this affect the features?
