### ISSUE TITLE
 undefined reference to `cv::VideoCapture::VideoCapture()'

### ISSUE THREAD

**Issue by mangdian** [facebook/C3D#253]
when I run "make all",there are errors:
`build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::set(int, double)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::open(cv::String const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::release()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::~VideoCapture()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::isOpened() const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::get(int) const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::VideoCapture()'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/compute_image_mean.bin] Error 1
make: *** Waiting for unfinished jobs....
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::set(int, double)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::open(cv::String const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::release()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::~VideoCapture()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::isOpened() const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::get(int) const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
`
How can I fix this?

**Comment by dutran** [comment]
do you have opencv and ffmpeg installed on your machine?

**Comment by mangdian** [comment]
yes,I have already install opencv.and I can successfully compile v1.0.

**Comment by dutran** [comment]
It is weird, sounds like a linking problem. Some LD_LIBRARY_PATH may solve it

**Comment by dutran** [comment]
check this https://github.com/facebook/C3D/issues/259

**Comment by dutran** [comment]
@mangdian try again, just modify Makefile

**Comment by heixi** [comment]
![5tuwt](https://cloud.githubusercontent.com/assets/16206119/25799513/cb8cf596-3417-11e7-820d-ab3e28f538c9.png)
How to solve this problem？

**Comment by sunnyxiaohu** [comment]
modify :　LIBRARIES += opencv_core opencv_highgui opencv_imgproc opencv_video
to: LIBRARIES += opencv_core opencv_highgui opencv_imgproc opencv_videoio

**Comment by dutran** [comment]
try to pull and compile again should solve the issue.

**Comment by tianzening** [comment]
@sunnyxiaohu thanks,it works for me,(and my opencv version is 3.2).

**Comment by IanMin1022** [comment]
@sunnyxiaohu  how can I put the linking in my bash?

**Comment by codestamp** [comment]
thanks @sunnyxiaohu  adding opencv_videoio did the job.

**Comment by prasuchit** [comment]
Hi,

Could you tell me the location of this makefile where the path change has to be made? I tried searching through the entire opencv folder and couldn't find the right file.

**Comment by ibrahimqazi** [comment]
> 
> 
> It is weird, sounds like a linking problem. Some LD_LIBRARY_PATH may solve it

I have also the same problem, I am using ROS and compiling it using Catkin, I have CMakeLists.txt file for my package. Can you please explain what is mean by LD_LIBRARY_PATH, how can I solve it in my case ? thanks

**Comment by YHAY** [comment]
> > It is weird, sounds like a linking problem. Some LD_LIBRARY_PATH may solve it
> 
> I have also the same problem, I am using ROS and compiling it using Catkin, I have CMakeLists.txt file for my package. Can you please explain what is mean by LD_LIBRARY_PATH, how can I solve it in my case ? thanks

i have same problem:(

**Comment by BluebirdStory** [comment]
或许这就是大佬吧 @sunnyxiaohu

**Comment by showgood163** [comment]
@sunnyxiaohu 
Thank you.

**Comment by TangShengqin** [comment]
@sunnyxiaohu 大佬大佬！

**Comment by TangShengqin** [comment]
modify Makefile as @sunnyxiaohu said!

**Comment by sljlp** [comment]
> modify :　LIBRARIES += opencv_core opencv_highgui opencv_imgproc opencv_video
> to: LIBRARIES += opencv_core o
