### ISSUE TITLE
Problems when extracting feature using UCF_finetuned caffemodel

### ISSUE THREAD

**Issue by mangdian** [facebook/C3D#254]
I use the released model finetuned on UCF101 to extract feature,however,I found that the extracted prob is different if I run the code again,and the classification result is obviously wrong.Is this because I didn't write the prototxt rightly?I have tried every possible method.Can anyone tell me how can I fix it.

**Comment by hjjpku** [comment]
Good questions. Does anybody have any ideas?

**Comment by dutran** [comment]
@mangdian make sure, your data layer has shuffle: false and using the right blob name.
