### ISSUE TITLE
about the visualization of C3D

### ISSUE THREAD

**Issue by 1292765944** [facebook/C3D#256]
In figure 4 of your paper 'Learning Spatialtemporal Features with 3D Convolutional Networks', you have visualised the feature learned in conv5b. But how do you get the relationship between the original frames and the features? I cannot comprehend this figure.

Besides, I wonder where can I get the dataset I380K. I donot find any reference to the dataset.

Best!
guangxing

**Comment by dutran** [comment]
- The visualization was used is deconv, we follow this paper [https://www.cs.nyu.edu/~fergus/papers/zeilerECCV2014.pdf].
- We cannot release I380K, but you can try Sports1M which is 3x bigger than that.
