### ISSUE TITLE
Computing Mean from list of images

### ISSUE THREAD

**Issue by sainisanjay** [facebook/C3D#258]
@dutran   I am trying to compute volume mean for my images using 
`GLOG_logtostderr=1 /home/sanjay/Workspace/0_Gesture_recog/C3D_new/C3D-v1.0/build/tools/compute_volume_mean_from_list.bin /home/sanjay/Workspace/0_Gesture_recog/C3D_new/C3D-v1.0/examples/c3d_finetuning/nvidia_train_list.lst 16 128 171 1 /home/sanjay/Workspace/0_Gesture_recog/C3D_new/C3D-v1.0/examples/c3d_finetuning/123.binaryproto
`
I have make my file names as %s/image_%04d.jpg thus i have changed the
`src/caffe/util/image_io.cpp file with sprintf(fn_im, "%s/image_%04d.jpg", img_dir, i);`

my file format is like
```
/home/sanjay/Workspace/1_Data/NVIDIA/Video_data/class_01/subject10_r0/duo_left 1 0
/home/sanjay/Workspace/1_Data/NVIDIA/Video_data/class_01/subject10_r0/duo_left 17 0
/home/sanjay/Workspace/1_Data/NVIDIA/Video_data/class_01/subject10_r0/duo_left 33 0
/home/sanjay/Workspace/1_Data/NVIDIA/Video_data/class_01/subject10_r0/duo_left 49 0
```
**Error**
```
E0502 11:03:47.211109  6576 image_io.cpp:205] Image path: /home/sanjay/Workspace/1_Data/NVIDIA/Video_data/class_01/subject10_r0/duo_left/image_0001.jpg
E0502 11:03:47.211252  6576 image_io.cpp:209] Check000 
E0502 11:03:47.212024  6576 image_io.cpp:221] Check1 
E0502 11:03:47.463919  6576 image_io.cpp:229] check data 0
E0502 11:03:47.463955  6576 image_io.cpp:246] Check3
E0502 11:03:47.463994  6576 image_io.cpp:205] Image path: /home/sanjay/Workspace/1_Data/NVIDIA/Video_data/class_01/subject10_r0/duo_left/image_0002.jpg
E0502 11:03:47.464000  6576 image_io.cpp:209] Check0 
E0502 11:03:47.464264  6576 image_io.cpp:221] Check1 
E0502 11:03:47.464350  6576 image_io.cpp:229] check data 0
*** Error in `/home/sanjay/Workspace/0_Gesture_recog/C3D_new/C3D-v1.0/build/tools/compute_volume_mean_from_list.bin': free(): invalid next size (normal): 0x0000000002ae8f00 ***
Aborted (core dumped)
```
When i compute mean from videos, it worked perfect but when i try to computer from list of images it give me above error.

**Comment by dutran** [comment]
@sainisanjay have you solved your issue?

**Comment by sainisanjay** [comment]
Yes @dutran i have solved.

**Comment by dutran** [comment]
glad to hear!

**Comment by sophiazy** [comment]
@sainisanjay @dutran 
 I am trying to run create_volume_mean.sh for ucf101 image .using
GLOG_logtostderr=1 ../../build/tools/compute_volume_mean_from_list.bin ../c3d_finetuning/train_01.lst 16 128 171 1 ucf101_train_mean.binaryproto 10

input  file l format is following

/data/zhaoyan/ucf101_img_TV/Billiards/v_Billiards_g19_c02/ 1 11
/data/zhaoyan/ucf101_img_TV/Billiards/v_Billiards_g19_c02/ 17 11
/data/zhaoyan/ucf101_img_TV/Billiards/v_Billiards_g19_c02/ 33 11
/data/zhaoyan/ucf101_img_TV/Billiards/v_Billiards_g19_c02/ 49 11
/data/zhaoyan/ucf101_img_TV/Billiards/v_Billiards_g19_c02/ 65 11
/data/zhaoyan/ucf101_img_TV/Billiards/v_Billiards_g19_c02/ 81 11


error

I1010 13:51:48.235913 26588 compute_volume_mean_from_list.cpp:53] using dropping rate 10
I1010 13:51:48.270182 26588 compute_volume_mean_from_list.cpp:80] Starting Iteration
F1010 13:51:49.171322 26588 compute_volume_mean_from_list.cpp:92] Check failed: size_in_datum == data_size (0 vs. 1050624) Incorrect data field size 0
*** Check failure stack trace: ***
    @     0x7f9f06b1cdaa  (unknown)
    @     0x7f9f06b1cce4  (unknown)
    @     0x7f9f06b1c6e6  (unknown)
    @     0x7f9f06b1f687  (unknown)
    @           0x408ae2  main
    @     0x7f9f04ad7ec5  (unknown)
    @           0x408cf2  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

  I have check the opencv ,the opencv can play the video .can you give me some advice?
