### ISSUE TITLE
Torch-C3D-binding?

### ISSUE THREAD

**Issue by ycjlin** [facebook/C3D#26]
Dear Du,
There's a torch-caffe-binding:
https://github.com/szagoruyko/torch-caffe-binding
I was wondering if it could be applied to C3D.
If it's possible, please kindly suggest how to modify for this command
net = caffe.Net('deploy.prototxt', 'bvlc_alexnet.caffemodel', 'test')
Thank you.

**Comment by dutran** [comment]
@ycjlin I did not use this tool before but you I can give it a try and keep me posted. For your information, we will soon release C3D model in Torch, so no binding needed.

**Comment by ycjlin** [comment]
That's a great news. Looking forward to C3D in Torch!!

**Comment by MaxReimann** [comment]
Is there an expected release date for the C3D model in Torch ?

**Comment by apoliver** [comment]
Hi Du, I am wondering is there any implementation of C3D in Torch7?

Thanks a lot.

**Comment by hassony2** [comment]
Hi @dutran 
Do you know if a C3D torch implementation was ever made ?
It would be great to have ! :)
