### ISSUE TITLE
feature_extraction

### ISSUE THREAD

**Issue by zhaiyuan** [facebook/C3D#260]
Hi
For C3D-v1.1, i want to change the parameter 4970 for my dataset in feature_extraction.sh, but i found if i choose a parameter<4970, e.g. 320, there would be no features generated for some data, i don't know why. 
Moreover, generated features  are of different sizes ( have different number of files in output folders ) in that videos have different frames, do you know how to quantify features of different videos to features of same size?

**Comment by dutran** [comment]
This is mostly about your list_file and list_prefix miss-aligned. Also, you need to calculate the number of mini-batch correctly. e.g. number of clip / mini-batch-size then round up.
