### ISSUE TITLE
cannot extract features

### ISSUE THREAD

**Issue by VictorLeeLk** [facebook/C3D#261]
Hi,when running the shell c3d_sport1m_feature_extraction_frm.sh, I find there is no folder named ../../build/tools/extract_image_features.bin,even I put the build folder into the project,I cannot find the 
extract_image_features.bin file at all, what is the problem?looking forward to hear from you,Thank you!

**Comment by dutran** [comment]
this means you have not build the tool successfully.

**Comment by VictorLeeLk** [comment]
I have built caffe-master successfuly,I find the folder build ,then I copy this folder into the caffe-cvprw15-master,but still cannot find the file of /build/tools/extract_image_features.bin, is it OK?What should I do?Thank you!

**Comment by dutran** [comment]
I think you are confused between caffe and C3D

**Comment by VictorLeeLk** [comment]
Thank you very much! I am new to caffe and linux, I have got what you said,firstly I should make the Makefile.config and this step will produce the folder build,right?
