### ISSUE TITLE
Something goes wrong wrong with VideoData layer?

### ISSUE THREAD

**Issue by bityangke** [facebook/C3D#264]
When running C3D-v1.1/examples/c3d_ucf101_feature_extraction/feature_extraction.sh
Error messege are as followings:
```
I0507 21:29:03.782029  6581 layer_factory.hpp:77] Creating layer data
F0507 21:29:03.782055  6581 layer_factory.hpp:81] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: VideoData (known types: AbsVal, Accuracy, ArgMax, BNLL, BatchNorm, BatchReindex, Bias, BlackHole, Concat, ContrastiveLoss, Convolution, Convolution3D, Crop, Data, Deconvolution, Deconvolution3D, Dropout, DummyData, ELU, Eltwise, Embed, EuclideanLoss, Exp, Filter, Flatten, HDF5Data, HDF5Output, HingeLoss, Im2col, InfogainLoss, InnerProduct, Input, L2Normalize, LRN, LSTM, LSTMUnit, Log, MVN, MemoryData, MultinomialLogisticLoss, PReLU, Parameter, Pooling, Pooling3D, Power, Python, RNN, ReLU, Reduction, Reshape, SPP, Scale, Sigmoid, SigmoidCrossEntropyLoss, Silence, Slice, Softmax, SoftmaxWithLoss, Split, TanH, Threshold, Tile)
*** Check failure stack trace: ***
    @     0x7f064d2395cd  google::LogMessage::Fail()
    @     0x7f064d23b433  google::LogMessage::SendToLog()
    @     0x7f064d23915b  google::LogMessage::Flush()
    @     0x7f064d23be1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f064d741a5c  caffe::Net<>::Init()
    @     0x7f064d743a10  caffe::Net<>::Net()
    @           0x403886  feature_extraction_pipeline<>()
    @     0x7f064c8ed830  __libc_start_main
    @           0x402e59  _start
    @              (nil)  (unknown)
Aborted (core dumped)
```

**Comment by dutran** [comment]
working fine one my end.

I0508 11:19:23.528013 1349415 net.cpp:198] scale_conv1 needs backward computation.
I0508 11:19:23.528017 1349415 net.cpp:198] bn_conv1 needs backward computation.
I0508 11:19:23.528031 1349415 net.cpp:198] conv1 needs backward computation.
I0508 11:19:23.528035 1349415 net.cpp:200] label_data_1_split does not need backward computation.
I0508 11:19:23.528039 1349415 net.cpp:200] data does not need backward computation.
I0508 11:19:23.528043 1349415 net.cpp:242] This network produces output accuracy/top-1
I0508 11:19:23.528046 1349415 net.cpp:242] This network produces output accuracy/top-5
I0508 11:19:23.528050 1349415 net.cpp:242] This network produces output loss
I0508 11:19:23.528151 1349415 net.cpp:255] Network initialization done.
I0508 11:19:23.755826 1349415 upgrade_proto.cpp:77] Attempting to upgrade batch norm layers using deprecated params: c3d_resnet18_sports1m_r2_iter_2800000.caffemodel
I0508 11:19:23.755858 1349415 upgrade_proto.cpp:80] Successfully upgraded batch norm layers using deprecated params.
I0508 11:19:23.786332 1349415 extract_image_features.cpp:96] Extracting features for 4970 batches
I0508 11:19:24.749745 1349415 extract_image_features.cpp:130] Extracted features of 30 images.

May be try to pull again and compile.
