### ISSUE TITLE
FATAL error when trying C3D-1.1

### ISSUE THREAD

**Issue by abuzn** [facebook/C3D#269]
I am trying the C3D-1.1(c3d_ucf101_finetuning). And some fatal error occurred in network creating step. Below is the error log
I0517 10:39:42.503278 31410 layer_factory.hpp:77] Creating layer scale_conv1
I0517 10:39:42.503402 31410 net.cpp:122] Setting up scale_conv1
I0517 10:39:42.503417 31410 net.cpp:129] Top shape: 16 64 8 56 56 (25690112)
I0517 10:39:42.503423 31410 net.cpp:137] Memory required for data: 327548992
I0517 10:39:42.503434 31410 layer_factory.hpp:77] Creating layer conv1_relu
I0517 10:39:42.503446 31410 net.cpp:84] Creating Layer conv1_relu
I0517 10:39:42.503460 31410 net.cpp:406] conv1_relu <- conv1
I0517 10:39:42.503469 31410 net.cpp:367] conv1_relu -> conv1 (in-place)
F0517 10:39:43.455974 31410 blob.hpp:140] Check failed: num_axes() <= 4 (5 vs. 4) Cannot use legacy accessors on Blobs with > 4 axes.
*** Check failure stack trace: ***
    @     0x7f271a2b0e6d  (unknown)
    @     0x7f271a2b2ced  (unknown)
    @     0x7f271a2b0a5c  (unknown)
    @     0x7f271a2b363e  (unknown)
    @     0x7f27211e7ad5  caffe::Blob<>::LegacyShape()
    @     0x7f272125b536  caffe::CuDNNReLULayer<>::Reshape()
    @     0x7f27213351a5  caffe::Net<>::Init()
    @     0x7f27213370c2  caffe::Net<>::Net()
    @     0x7f272133e7d0  caffe::Solver<>::InitTrainNet()
    @     0x7f272133f773  caffe::Solver<>::Init()
    @     0x7f272133fa4f  caffe::Solver<>::Solver()
    @     0x7f2721356d11  caffe::Creator_SGDSolver<>()
    @           0x40edde  caffe::SolverRegistry<>::CreateSolver()
    @           0x407f6c  train()
    @           0x405a0c  main
    @     0x7f2711233b15  __libc_start_main
    @           0x40627d  (unknown)
./finetuning_ucf101.sh: line 7: 31410 Aborted                 (core dumped) GLOG_log_dir="./LOG_TRAIN" ../../build/tools/caffe.bin train --solver=solver_r2.prototxt --weights=c3d_resnet18_sports1m_r2_iter_2800000.caffemodel --gpu=0

The GPU I used is Titan-X. The building config for caffe is as follows:

USE_CUDNN := 1

USE_OPENCV := 1

CUDA_DIR := /usr/local/cuda-8.0
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
		-gencode arch=compute_20,code=sm_21 \
		-gencode arch=compute_30,code=sm_30 \
		-gencode arch=compute_35,code=sm_35 \
		-gencode arch=compute_50,code=sm_50 \
		-gencode arch=compute_50,code=compute_50

BLAS := atlas

PYTHON_INCLUDE := /usr/include/python2.7 \
		/usr/lib/python2.7/dist-packages/numpy/core/include

PYTHON_LIB := /usr/lib

print(numpy.core.__file__)'))/include

INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib

BUILD_DIR := build
DISTRIBUTE_DIR := distribute
TEST_GPUID := 0
Q ?= @

Anyone knows how to solve this problem?

**Comment by dutran** [comment]
USE_CUDNN := 0 then try again

**Comment by abuzn** [comment]
It works. Thanks a lot!

**Comment by gehuageyan** [comment]
I comment  USE_CUDNN := 1, but it doesn't work, @dutran , error as below:

I0531 20:01:27.890867 28863 layer_factory.hpp:77] Creating layer data
I0531 20:01:27.891362 28863 net.cpp:84] Creating Layer data
I0531 20:01:27.891376 28863 net.cpp:380] data -> data
I0531 20:01:27.891384 28863 net.cpp:380] data -> label
I0531 20:01:27.895123 28863 net.cpp:122] Setting up data
I0531 20:01:27.895136 28863 net.cpp:129] Top shape: 1 3 32 9 32 (27648)
I0531 20:01:27.895141 28863 net.cpp:129] Top shape: 1 1 1 32 32 (1024)
I0531 20:01:27.895145 28863 net.cpp:137] Memory required for data: 114688
I0531 20:01:27.895149 28863 layer_factory.hpp:77] Creating layer label_data_1_split
I0531 20:01:27.895157 28863 net.cpp:84] Creating Layer label_data_1_split
I0531 20:01:27.895161 28863 net.cpp:406] label_data_1_split <- label
I0531 20:01:27.895167 28863 net.cpp:380] label_data_1_split -> label_data_1_split_0
I0531 20:01:27.895174 28863 net.cpp:380] label_data_1_split -> label_data_1_split_1
I0531 20:01:27.895200 28863 net.cpp:122] Setting up label_data_1_split
I0531 20:01:27.895205 28863 net.cpp:129] Top shape: 1 1 1 32 32 (1024)
I0531 20:01:27.895210 28863 net.cpp:129] Top shape: 1 1 1 32 32 (1024)
I0531 20:01:27.895212 28863 net.cpp:137] Memory required for data: 122880
I0531 20:01:27.895216 28863 layer_factory.hpp:77] Creating layer conv1_1
I0531 20:01:27.895228 28863 net.cpp:84] Creating Layer conv1_1
I0531 20:01:27.895231 28863 net.cpp:406] conv1_1 <- data
I0531 20:01:27.895236 28863 net.cpp:380] conv1_1 -> conv1_1
F0531 20:01:27.895272 28863 blob.hpp:140] Check failed: num_axes() <= 4 (5 vs. 4) Cannot use legacy accessors on Blobs with > 4 axes.
