### ISSUE TITLE
How to use the extracted feature for classification accuracy

### ISSUE THREAD

**Issue by sainisanjay** [facebook/C3D#270]
Hi @ dutran, 
I have train the C3D_Resnet model with my own dataset and also i have extracted the features from trained model. Extracted features are  `prob, pool5 `and ` res5b. ` . After this stage i confused a bit like how to read these features to train linear SVM (as there is no script in C3D-v1.1 model). I wounder if you can provide the script for reading the features and train the SVM. Thanks

**Comment by dutran** [comment]
The same script for ver1.0 (https://github.com/facebook/C3D/tree/master/C3D-v1.0/examples/c3d_feature_extraction/script) will work.

**Comment by sainisanjay** [comment]
Thanks you so much for swift reply. As script are `.m ` file thus to execute these files we need matlab right???. Further, i am very grateful if i can get smv classification accuracy testing script.
