### ISSUE TITLE
Which layer feature we have to extract in C3D_Resenet. 

### ISSUE THREAD

**Issue by sainisanjay** [facebook/C3D#271]
Hello @ dutran, 
I would like to know which layer features i have to extract in C3D_Resnet model to get the high accuracy. If i will extract the res5b and pool5 layer features than what will be the dimension of these features. is the feature dimension equal to `num_output:`  of the layer. 
Thanks

**Comment by dutran** [comment]
res5b is lightly more accurate than pool5 for action recognition (UCF101, HMDB51). Output size of res5b is 512x1x7x7, pool5 is 512x1x1x1 (AvegagePool of res5b).

**Comment by sainisanjay** [comment]
Thanks @dutran
