### ISSUE TITLE
read video error

### ISSUE THREAD

**Issue by wlgcqh** [facebook/C3D#276]
I use video as input, and set use_image=false.
it will produce the following error(that video really exist):
E0608 00:18:30.950901 31445 image_io.cpp:146] Cannot open /home/ssd1/vis/SGB6yf9UApM_000558_000568.mp4

**Comment by yangzhikai** [comment]
me too. have you handled it?

**Comment by dutran** [comment]
@wlgcqh @yangzhikai more context, log message should be helpful, otherwise it is hard to know which were your issues. First thing is to look at (image_io.cpp:146) to understand what was the cause.

**Comment by yangzhikai** [comment]
thank you. then I look back in detail,I find this when" cmake"：CMake Error at docs/CMakeLists.txt:82(file):
     file STRING file ''~/C3D-v1.1/.Doxyfile" cannot be read.
    Can't find OUTPUT_DIRECTORY in doxygen config file.try to use default: ./doxygen/   
But I have installed "doxygen" and  used "doxygen -s -g" to compile "Doxyfile"  in toot"~/C3D-v1.1/build/"..............

**Comment by yangzhikai** [comment]
ohhh,sorry.I  know what has happened. because the name of *.jpg is not right form .I use jpg  for LRCN .....

**Comment by dutran** [comment]
glad to hear you got your issue solved.
