### ISSUE TITLE
The depth of input

### ISSUE THREAD

**Issue by youssefoumate** [facebook/C3D#278]
Hi Sir,
I have a question for you, 
If I understand your paper well, the 3D convolutional layer needs an input which has a depth dimension besides other dimensions. If I'm not mistaken the depth is considered as a number of frames that the 3D kernel convolves to get a 3D feature map.
If that is right, what is the depth used in your implementation (number of frames)? 

Thank you

**Comment by dutran** [comment]
@youssefoumate right, kernel it 3D (if not consider channels), and if consider input and output channels it becomes 5D.
Input we can use 16 frames (for ver1.0) and 8 frames (or ver 1.1). all kernels have depth=3

**Comment by Hzzone** [comment]
@dutran batch*channels*frames*width*height? Could I use your 3D kernel on 3D medical image such CT which consists of 1*(channels)*slices*width*height? not the time sequence like video, but space information.

**Comment by dutran** [comment]
@Hzzone yes, you could, provided that you have your data loader. Minor correction: batch x channels x frames x height x width for videos.
