### ISSUE TITLE
running  the fine-tuned have mistake on C3D-1.1v

### ISSUE THREAD

**Issue by 812406210** [facebook/C3D#283]
when i run "sh testing_ucf101.sh",it has some mistake----"testing_ucf101.sh: 1: testing_ucf101.sh: ../../build/tools/caffe.bin: not found", i can't resolve it ,can U help me to resolve it ,  (ps:i use "the C3D model fine-tuned" )

**Comment by dutran** [comment]
You did not build caffe successfully.
