### ISSUE TITLE
Training on optical flow frames: Is Single Channel Input Allowed?

### ISSUE THREAD

**Issue by vivoutlaw** [facebook/C3D#284]
Hi Du,

is it possible to train C3D on optical flow frames which has only one channel? As in the current setup  the "Convolution3D" has  kernel_size: 3 and kernel_depth: 3 parameters which I assume that it takes 3-channel input i.e. RGB images. 

Is the "Convolution3D" adaptable on the basis of input channels (either be 1-channel or 3-channel)fed as input to the layer? Can you please comment.

Thanks and best, Vivek

**Comment by dutran** [comment]
@vivoutlaw Yes, it is possible. The current setup can do any number of channel. See example below.

Input: batch_size x num_input_channels x Length x Height x Width 
Kernel: num_output_filters x num_input_channels x 3 x 3 x 3

Kernel size can be any, but the above example is 3x3x3. It always create filters that match the number of input channel. Assume we do padding and striding = 1 (both spatial and temporal).

Output: batch_size x num_output_filters x Length x Height x Width

**Comment by vivoutlaw** [comment]
Awesome, thanks!

**Comment by dutran** [comment]
Hope to see you around there.
