### ISSUE TITLE
Could we reshape the network according to the input blob of network?

### ISSUE THREAD

**Issue by huangjunshi** [facebook/C3D#285]
First of all, thanks for the authors' work. :)

We are trying to feed the network by its input blob, rather than the VideoDataLayer, as the batch size may change occasionally. However, when we are using the 3D Conv and 3D pooling by feeding images of different numbers, we find that the shape of data blobs of network layers cannot change accordingly. For example, the prototxt of network input looks like:

...
_input: data
input_shape {
  dim: 1 # batch size
  dim: 3 # channels
  dim: 8 # temporal length
  dim: 112 # height
  dim: 112 # width
}_
...

and we hope the first dim of following data blobs may change when we feed this data blob with different batch sizes.

We also try to use the network with only 2D Conv and 2D pooling layers, and find that the network shape function works well. We checked the potential reason, and find that the 3D Conv and 3D pooling layer do not implement the Reshape() function, and integrate it into the LayerSetUp() function. We are not sure whether this implementation is "canonical". Does anyone face the same problem? Do we miss something for the network reshaping?

Thanks!

**Comment by huangjunshi** [comment]
We find the reason of network reshape problem. My suggestion is to call the LayerSetUp() function in the Reshape() function of Conv3d and pool3d layer, which will be called in the forward() function of base class Layer.

**Comment by dutran** [comment]
When converting caffe model to caffe2 models, I found there is a minor bug in python wrapper (enforce the input shape is always 4D). Let me know if you already fix your issue? If not, I will look to fix that bug.

**Comment by huangjunshi** [comment]
Hi @dutran , we use the input blob in C++ interface, rather than the python wrapper, so we did not face the reshape problem as you mentioned. :)

**Comment by potazhou** [comment]
@ huangjunshi  Have you solved this problem? I face the same problem!

**Comment by huangjunshi** [comment]
@potazhou Hi zhou, please find a possible solution at my second comment if you are using c++ API.
