### ISSUE TITLE
implementation of temporal jitter for data augmentation

### ISSUE THREAD

**Issue by hekim3434** [facebook/C3D#287]
From the C3D paper, I saw that jittering(both spatial and temporal) and mirror are used for data augmentation.
I want to know where I can find the implementation about temporal jittering.
implementation of spatial jittering seems to be included in random crop step.
However, I can't find the role of "use_temporal_jitter" option in video_data_layer.cpp.
Where can I find the implementation of temporal jitter in C3D codes?

**Comment by dutran** [comment]
It is implemented both v1.0 and v.1.1 in video data layer with see [https://github.com/facebook/C3D/blob/master/C3D-v1.1/examples/c3d_ucf101_feature_extraction/c3d_resnet18_ucf101_feature_extraction.prototxt#L21] and [https://github.com/facebook/C3D/blob/master/C3D-v1.0/examples/c3d_finetuning/c3d_ucf101_finetuning_train.prototxt#L11]
