### ISSUE TITLE
CPU_ONLY support

### ISSUE THREAD

**Issue by jiazhentim** [facebook/C3D#288]
Does it support CPU_only mode? I can not compile C3D-v1.0 without CUDA environment.

**Comment by kasparov92** [comment]
I remember it was written (most probably in the documentation down in the FAQ section) that you need to install CUDA but without having actual Nvidia GPU, this will act as if you installed in CPU_mode only as it will not find any suitable GPU so it will use the CPU

**Comment by jiazhentim** [comment]
Thanks for pointing that out and sorry for not noticing that. I will try. @kasparov92

**Comment by dutran** [comment]
and also for 1.1, CPU_ONLY is an option on Makefile.config
