### ISSUE TITLE
How to add the C3D function on the latest Caffe?

### ISSUE THREAD

**Issue by ycjlin** [facebook/C3D#29]
Dear @dutran,

Since there are many new functions in the latest Caffe, it would be helpful to add the great
C3D function on the latest BVLC/Caffe. 
However, the codes are quite different.
I'm still not very familiar with Caffe repository.
May you suggest how to do it smoothly? Thank you.

**Comment by dutran** [comment]
Hi @ycjlin 
I haven't followed caffe recently, so I don't know how big the difference for now. I remember to see some PRs doing ND convolution and ND pooling, you may want to check them out.

Another option is cuDNN, cuDNN allow ND convolution, you need to implement only 3D pooling.
The old caffe supports only 4D blob, I don't know its status now. If it does not support ND blob, then you need to extend it at least to support 5D blob.

Hope this helps.

**Comment by ycjlin** [comment]
@dutran Thank for your advice. It helps a lot. :D
