### ISSUE TITLE
when i got c3d features  using the suffix '.fc6'.how to transform those feature files to mat or npy

### ISSUE THREAD

**Issue by mengya22** [facebook/C3D#294]
when i got c3d features  using the suffix '.fc6'.how to transform those feature files to mat or npy.because I want to use these features in tensorflow .

**Comment by dutran** [comment]
@mengya22 you can use these scripts [https://github.com/facebook/C3D/tree/master/C3D-v1.0/examples/c3d_feature_extraction/script] to load them from matlab, or write a similar script to load from python.
