### ISSUE TITLE
Should frames chosen for feature extraction depend on frame rate ?

### ISSUE THREAD

**Issue by rohit-gupta** [facebook/C3D#296]
I am trying to use C3D extracted features for action classification. However my dataset of videos has videos of varying frame rates. Should I extract 16 frames equally spaced in time or should I jst use c3d with 16 consecutive frames ? And if I extract frames equally spaced in time what time interval should I use ?

**Comment by dutran** [comment]
C3D is trained on videos with ~25-30 fps. To get it worked best, ideally you should have your videos have similar fps. But other fps also works.
