### ISSUE TITLE
pretrain caffemodels for C3D and Res3D

### ISSUE THREAD

**Issue by 1292765944** [facebook/C3D#297]
Where can I find the pretrain C3D and Res3D caffemodels? I do not find any links to these models.

**Comment by dutran** [comment]
Res3D: https://www.dropbox.com/s/qqfrg6h44d4jb46/c3d_resnet18_sports1m_r2_iter_2800000.caffemodel
C3D: https://www.dropbox.com/s/vr8ckp0pxgbldhs/conv3d_deepnetA_sport1m_iter_1900000?dl=0
