### ISSUE TITLE
would you send me the caffemodel file? 

### ISSUE THREAD

**Issue by beihaidao** [facebook/C3D#299]
Unable to access network to download the caffemodel.
failed to  download:
https://www.dropbox.com/s/qqfrg6h44d4jb46/c3d_resnet18_sports1m_r2_iter_2800000.caffemodel
https://www.dropbox.com/s/mkc9q7g4wnqnmcv/c3d_ucf101_finetune_whole_iter_20000
 would you please send this two flies to me ? and my mail is  <sandychen137@gmail.com>
thanks a lot:)

**Comment by dutran** [comment]
@beihaidao Have you got the model downloaded?

**Comment by Marchong** [comment]
I failed to download it too,has there another url can be used to download it ?

**Comment by beihaidao** [comment]
@dutran yes, i got. thanks

**Comment by Marchong** [comment]
@beihaidao  Can you send me this file ? Thank you .

**Comment by beihaidao** [comment]
@Marchong ok.please give me an email address.

**Comment by Marchong** [comment]
@beihaidao  1104069613@qq.com 
Thank you so much !

**Comment by Marchong** [comment]
@beihaidao  and if you have this file **c3d_resnet18_sports1m_r2_iter_2800000.caffemodel** ,please send me together ,thank you
