### ISSUE TITLE
Error while fine-tuning : Check failed: num_axes() <= 4 (5 vs. 4)

### ISSUE THREAD

**Issue by Aravinda89** [facebook/C3D#304]
I'm trying to finetune c3dv1.1 for UCFsports dataset using this weight 
"c3d_resnet18_ucf101_r2_ft_iter_20000.caffemodel.mdlp". I'm getting following error. Log file is attached. I'm new to deep learning,I don't know reason for this error and how to solve this. Please help.

I0830 17:01:21.922052  4885 net.cpp:84] Creating Layer conv1_relu
I0830 17:01:21.922055  4885 net.cpp:406] conv1_relu <- conv1
I0830 17:01:21.922060  4885 net.cpp:367] conv1_relu -> conv1 (in-place)
F0830 17:01:22.088516  4885 blob.hpp:140] Check failed: num_axes() <= 4 (5 vs. 4) Cannot use legacy accessors on Blobs with > 4 axes.
*** Check failure stack trace: ***
    @     0x7fa335daedbd  google::LogMessage::Fail()
    @     0x7fa335db0c5d  google::LogMessage::SendToLog()
    @     0x7fa335dae9ac  google::LogMessage::Flush()
    @     0x7fa335db157e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fa3363151f1  caffe::Blob<>::LegacyShape()
    @     0x7fa3363e1ee6  caffe::CuDNNReLULayer<>::Reshape()
    @     0x7fa336347b05  caffe::Net<>::Init()
    @     0x7fa3363499d2  caffe::Net<>::Net()
    @     0x7fa3364b9ca0  caffe::Solver<>::InitTrainNet()
    @     0x7fa3364bac63  caffe::Solver<>::Init()
    @     0x7fa3364baf3f  caffe::Solver<>::Solver()
    @     0x7fa33632c791  caffe::Creator_SGDSolver<>()
    @           0x411a16  caffe::SolverRegistry<>::CreateSolver()
    @           0x40a97d  train()
    @           0x40845c  main
    @     0x7fa334b44f45  (unknown)
    @           0x408ccb  (unknown)
[Log.txt](https://github.com/facebook/C3D/files/1263206/Log.txt)

**Comment by dutran** [comment]
Set (https://github.com/facebook/C3D/blob/master/C3D-v1.1/Makefile.config.example#L5) 
USE_CUDNN :=0
and re-compile.
