### ISSUE TITLE
C3D Regression float labels

### ISSUE THREAD

**Issue by tamtammarmat** [facebook/C3D#307]
Dear community,

I am trying to finetune the provided model for a regression task. However I am struggling with the fact that it is not possible to work with float labels. I already tried to adapt the video_data_layer.cpp and the video_data_layer.hpp, but it doesn't work. Has anybody any idea how I can finetune the model with float labels? 

I would appreciate any hints! Thanks in advance.

**Comment by dutran** [comment]
tamtammarmat: you can adopt video data layer, example can be found here https://github.com/dutran/C3D_dev/blob/master/src/caffe/layers/video_with_voxel_truth_data_layer.cpp
