### ISSUE TITLE
accuracy of SVM and C3D-softmax

### ISSUE THREAD

**Issue by gss-ucas** [facebook/C3D#309]

**Comment by gss-ucas** [comment]
When I directly use C3D softmax layer to get predicted label, the accuracy is only 45%, has
 a big difference with SVM accuracy, does anyone has this problem? Is it normal?
If it's normal, and why?
Please help me! Thank you very much!

**Comment by dutran** [comment]
Please read the paper carefully to reproduce the numbers, softmax has very low capacity. For C3D version 1.0, you should use fc6, fc7. For 1.1, you should use res5b or pool5. Also pay attention to normalization scheme.
