### ISSUE TITLE
Unbuntu15.04 installation error. /usr/bin/ld: /usr/local/lib/libhdf5.a(H5.c.o): relocation R_X86_64_32 against `H5_debug_g'

### ISSUE THREAD

**Issue by rockstone533** [facebook/C3D#31]
I tried to install C3D under Unbuntu15.04, but I got an error below.Anyone could help me?

/usr/bin/ld: /usr/local/lib/libhdf5.a(H5.c.o): relocation R_X86_64_32 against `H5_debug_g' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libhdf5.a: error adding symbols: 错误的值
collect2: 错误： ld 返回 1
Makefile:285: recipe for target 'build/lib/libcaffe.so' failed
make: *** [build/lib/libcaffe.so] Error 1

**Comment by dutran** [comment]
Your problem is with linking and with hdf5. Your header file has a different version from that of your lib file. Try to compile your hdf5 from source and modify your Makefile.config to point to consistent hdf5 both include dir and library dir.

**Comment by rockstone533** [comment]
@dutran  maybe sth goes wrong with my hdf5.a.I uninstall my hdf5 and install libhdf5-dev, and the problem get solved.
