### ISSUE TITLE
How  to do the demo?

### ISSUE THREAD

**Issue by chaobeiying** [facebook/C3D#316]
How to produce  the video of test results ?

Sport classification using C3D on Sports-1M dataset. Video frames are visualized with top 2 predictions.

**Comment by dutran** [comment]
I did that two steps, first run the net on some videos to generate the predictions, then render frames with overlaid prediction scores. If you have a GPU, you can run C3D real-time and print prediction scores real-time on frames (unfortunately it is not currently implemented).
