### ISSUE TITLE
question about the video clip label in computing volume mean 

### ISSUE THREAD

**Issue by sophiazy** [facebook/C3D#317]
Hi@dutran
I can compute volume mean value for ucf101 successfully.Now I want to generate the mean value for my own dataset.in my dataset ,every video contain several action class.Because in the train.lst contain the video clip label,so I do not know how to annotate the label for video clip(e.g. the clip length set 16) ?
further more ,I am confused that why compute the volume value need the video clip label.Can you give me some instruction?
I really appreciate for your reply and advice,thanks!

**Comment by dutran** [comment]
I think you just replace UCF101 data with your data and labels. The tool will work for you.
