### ISSUE TITLE
extract_image_features.bin is not found???

### ISSUE THREAD

**Issue by leileestone** [facebook/C3D#318]
Excuse me，when I run sh c3d_sport1m_feature_extraction_frm.sh or sh c3d_sport1m_feature_extraction_video.sh,there is a error that extract_image_features.bin is not found

**Comment by kartikeyaSh** [comment]
first you have to build c3d. after that you'll find the file in C3D-v1.1/build/tools/extract_image_features.bin
in case you've build c3d successfully you can search for the file in C3D-v1.1 folder manually. or as in your case you are using c3d-v1.0 which is deprecated and v1.1 is now available i recommend you build v1.1

**Comment by leileestone** [comment]
@ Kartikeya Sharma  thank you, I have built c3d v1.1 ,and I have met such problem below. when I run the feature_extraction.sh
image_io.cpp:339] Could not open or find file /data/users/trandu/datasets/ucf101/frm/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01//000001

**Comment by kartikeyaSh** [comment]
open ucf101_video_frame.list , ucf101_video_frame.prefix files and add path to the folder in which you have stored your frames of video.
you will find something like /data/users/trandu/datasets/ucf101/frm/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01//000001 writen in those files. make sure you remove that

**Comment by leileestone** [comment]
@kartikeyaSh  I have notice that I should change the  ucf101_video_frame.list , ucf101_video_frame.prefix. I mean how can I add the path of my frame into it, these are so many frame, There is any code I can generate  the path into that file

**Comment by kartikeyaSh** [comment]
@leileestone you'll have to write your own script for that

**Comment by dutran** [comment]
For the 1.1 version, video data layer has root_folder value, where you can use for this.

**Comment by dutran** [comment]
But for prefix, you have to prepare it anyway :)

**Comment by leileestone** [comment]
@kartikeyaSh  I don't konw how to write a script to generate a file like that

**Comment by leileestone** [comment]
and afterinstalling  ffmpeg，there is a error called permission denied,How can I fix that?

**Comment by dutran** [comment]
It would be easier if you post your full error messages.
