### ISSUE TITLE
compile problem below

### ISSUE THREAD

**Issue by leileestone** [facebook/C3D#319]
CXX/LD -o .build_release/tools/upgrade_net_proto_text.bin
.build_release/lib/libcaffe.so：对‘cv::VideoCapture::set(int, double)’未定义的引用
.build_release/lib/libcaffe.so：对‘cv::VideoCapture::open(cv::String const&)’未定义的引用
.build_release/lib/libcaffe.so：对‘cv::VideoCapture::release()’未定义的引用
.build_release/lib/libcaffe.so：对‘cv::VideoCapture::~VideoCapture()’未定义的引用
.build_release/lib/libcaffe.so：对‘cv::VideoCapture::isOpened() const’未定义的引用
.build_release/lib/libcaffe.so：对‘cv::VideoCapture::get(int) const’未定义的引用
.build_release/lib/libcaffe.so：对‘cv::VideoCapture::read(cv::_OutputArray const&)’未定义的引用
.build_release/lib/libcaffe.so：对‘cv::VideoCapture::VideoCapture()’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:625: recipe for target '.build_release/tools/upgrade_net_proto_text.bin' failed
make: *** [.build_release/tools/upgrade_net_proto_text.bin] Error 1

how can I fix it? I use cpu mode

**Comment by kartikeyaSh** [comment]
it's an opencv installation problem (either you don't have it installed or opencv libraries are not found due to some reason)
also make sure you have proper version of ffmpeg and opencv installed. (in simple words try playing a video using opencv and make sure it works)

**Comment by leileestone** [comment]
@kartikeyaSh thank you!!!

**Comment by dutran** [comment]
This looks like a linking issue with OpenCV.

**Comment by leileestone** [comment]
@dutran Thanks，I have fixed this problem.
