### ISSUE TITLE
c3d installation error

### ISSUE THREAD

**Issue by rockstone533** [facebook/C3D#32]
/usr/bin/ld: /usr/local/lib/libhdf5.a(H5.c.o): relocation R_X86_64_32 against `H5_debug_g' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libhdf5.a: error adding symbols: 
collect2: error: ld returned 1 exit status
Makefile:285: recipe for target 'build/lib/libcaffe.so' failed
make: *** [build/lib/libcaffe.so] Error 1
make: *** 

/usr/bin/ld: /usr/local/lib/libprotobuf.so: undefined reference to symbol 'inflate'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:310: recipe for target 'build/tools/convert_imageset.bin' failed
make: *** [build/tools/convert_imageset.bin] Error 1

/usr/bin/ld: /usr/local/lib/libprotobuf.so: undefined reference to symbol 'inflate'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:310: recipe for target 'build/tools/compute_image_mean.bin' failed
make: *** [build/tools/compute_image_mean.bin] Error 1
/usr/bin/ld: /usr/local/lib/libprotobuf.so: undefined reference to symbol 'inflate'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:310: recipe for target 'build/tools/upgrade_net_proto_text.bin' failed
make: *** [build/tools/upgrade_net_proto_text.bin] Error 1
/usr/bin/ld: /usr/local/lib/libprotobuf.so: undefined reference to symbol 'inflate'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:310: recipe for target 'build/tools/compute_image_mean_from_list.bin' failed
make: *** [build/tools/compute_image_mean_from_list.bin] Error 1
//usr/bin/ld: /usr/local/lib/usr/libprotobuf.sobin: undefined /reference to symbol 'ldinflate': 
//usrusr/lib/local/gcc//x86_64lib-linux-/libprotobuf.sognu/4.8/..:/../. ./x86_64undefined-linux-gnu reference/libz.so to: error  adding symbolssymbol : DSO missing' from command inflate'
line
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libz.so: error collect2: error: ld returned 1 exit status
adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:310: recipe for target 'build/tools/upgrade_net_proto_binary.bin' failed
make: *** [build/tools/upgrade_net_proto_binary.bin] Error 1
Makefile:310: recipe for target 'build/tools/compute_volume_mean_from_list.bin' failed
make: *** [build/tools/compute_volume_mean_from_list.bin] Error 1
/usr/bin/ld: /usr/local/lib/libprotobuf.so: undefined reference to symbol 'inflate'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:310: recipe for target 'build/tools/extract_learned_filters.bin' failed
make: *** [build/tools/extract_learned_filters.bin] Error 1
/usr/bin/ld: /usr/local/lib/libprotobuf.so: undefined reference to symbol 'inflate'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:310: recipe for target 'build/tools/blob_proto_to_blob_binary.bin' failed
make: *** [build/tools/blob_proto_to_blob_binary.bin] Error 1

/usr/bin/ld: /usr/local/lib/libprotobuf.so: undefined reference to symbol 'inflate'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:310: recipe for target 'build/tools/compute_volume_mean.bin' failed
make: *** [build/tools/compute_volume_mean.bin] Error 1
/usr/bin/ld: /usr/local/lib/libprotobuf.so: undefined reference to symbol 'inflate'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:310: recipe for target 'build/tools/train_net.bin' failed
make: *** [build/tools/train_net.bin] Error 1
/usr/bin/ld: /usr/local/lib/libprotobuf.so: undefined reference to symbol 'inflate'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:310: recipe for target 'build/tools/extract_features.bin' failed
make: *** [build/tools/extract_features.bin] Error 1
/usr/bin/ld: /usr/local/lib/libprotobuf.so: undefined reference to symbol 'inflate'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libz.so: error adding symbols: /DSO missing from command lineusr
/bin/ld: /usr/local/lib/libprotobuf.so: undefined reference to symbol 'inflate'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linuxcollect2: error: ld returned 1 exit status
-gnu/libz.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:310: recipe for target 'build/tools/extract_image_features.bin' failed
make: *** [build/tools/extract_image_features.bin] Error 1
Makefile:310: recipe for target 'build/tools/dump_network.bin' failed
make: *** [build/tools/dump_network.bin] Error 1
/usr/bin/ld: /usr/local/lib/libprotobuf.so: undefined reference to symbol 'inflate'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:310: recipe for target 'build/tools/net_speed_benchmark.bin' failed
make: *** [build/tools/net_speed_benchmark.bin] Error 1
/usr/bin/ld: /usr/local/lib/libprotobuf.so: undefined reference to symbol 'inflate'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:310: recipe for target 'build/tools/test_net.bin' failed
make: *** [build/tools/test_net.bin] Error 1
/usr/bin/ld: /usr/local/lib/libprotobuf.so: undefined reference to symbol 'inflate'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:310: recipe for target 'build/tools/finetune_net.bin' failed
make: *** [build/tools/finetune_net.bin] Error 1

**Comment by dutran** [comment]
@rockstone533 does this similar to #31?

**Comment by rockstone533** [comment]
@dutran Thank you so much! I use opencv3.0 to build C3D, and I find that some modules have been changed since the third version.At last, I get the problem solved.
