### ISSUE TITLE
docker version of C3D and cann't find "extract_image_features.bin"

### ISSUE THREAD

**Issue by supernihui** [facebook/C3D#321]
I have already built c3d 1.1 version of docker. But the dockerfile just compile the caffe. When I use your examples, it still cannot find ”the extract_image_features.bin“ . I knew that if I build the c3d project, the ”the extract_image_features.bin" will be produced. However, in my opinion, if I stalled the docker vision, I don't need to compile again because the dockerfile has done that for me.

I cannot find "extract_image_features.bin" either in opt/caffe folder or /workspace. I hope you can explain in  much details because I have been struggling about this problem for two days.

Thanks.

**Comment by dutran** [comment]
I think extract_image_features.bin is in tools and compiled by "make"
