### ISSUE TITLE
Difference between C3D and the BVLC caffe

### ISSUE THREAD

**Issue by amh28** [facebook/C3D#324]
Hello, I wanted to ask what are  the modifications or differences of this work with respect to the BVLC caffe, for example in the case of  3D convolution, the N-D convolution can already be used  for this purpose. Thanks for the help

**Comment by NonvolatileMemory** [comment]
caffe doesn't have video data layer,but it's very easy to code......

**Comment by dutran** [comment]
yeah, In the long run, I will either merge this to caffe/caffe2/pytorch for their long-term supports, as this code will be outdated soon, with new version of CUDA coming out.
