### ISSUE TITLE
Doubt about the model

### ISSUE THREAD

**Issue by rcrespocano** [facebook/C3D#328]
Hi all,

I am not sure if this code is related to paper "**_Learning Spatiotemporal Features with 3D Convolutional Networks_**" or to paper "**_ConvNet Architecture Search for Spatiotemporal Feature Learning_**".

In the second one is said that "_For the sake of reproducible research,the source code and pre-trained models are available at http://github.com/facebook/C3D_". It seems that this code is related to the first paper and not to the second paper. Besides, in the second paper pretrained models are not named as 'C3D' because this is the name for the oldest study. This confuses me a lot.

Can you help me?

Thank you in advance.

Best,
Rubén

**Comment by dutran** [comment]
Rube'n, C3D is v1.0 and Res3D is v1.1

**Comment by rcrespocano** [comment]
Thank you for your quick reply!

In which folder are located the pre-trained models?

- Res3D on Sports-1M? 
- Model trained with 128-frame long clip (∼ 4.5 to 5 seconds)?

Thank you so much in advance. And... good job! :)

Best,
Rubén

**Comment by dutran** [comment]
https://github.com/facebook/C3D/blob/master/C3D-v1.1/examples/c3d_ucf101_feature_extraction/feature_extraction.sh#L2

**Comment by rcrespocano** [comment]
In the paper it is said that for the training process _it is extracted randomly five 2-second long clips from each training video_. So, the model is trained with 10 seconds of each video file. Besides, it is also said that _Res3D uses only 10 crops_.

What I do not understand is whether you extract 8 frames from this five 2-second long clips or this 8 frames are consecutive frames from each video. How many frames are used for each video file? And more importantly, this 8 frames used as input are consecutive frames (or are non-consecutive frames spaced in time)? Before starting to use your model I need to know if this 8 frames are consecutive frames or conversely, they are not consecutive.

Thank you so much for your quick replies!

Best,
Rubén
