### ISSUE TITLE
run examples error

### ISSUE THREAD

**Issue by rockstone533** [facebook/C3D#33]
When I tried to run_ucf101.sh, I got an error message below.Anyone could  be so kind to help me ?@dutran 

F0921 17:46:52.132236  3023 video_data_layer.cpp:346] Check failed: ReadImageSequenceToVolumeDatum(file_list_[id].c_str(), 1, label_list_[id], new_length, new_height, new_width, sampling_rate, &datum) 

Also when I tried to run c3d_sport1m_feature_extraction_frm.sh, I got an error message below.

F0921 10:21:11.483539  9951 vol2col.cu:79] Check failed: error == cudaSuccess (8 vs. 0)  invalid device function

**Comment by dutran** [comment]
@rockstone533  you may want to look at this https://github.com/BVLC/caffe/issues/869

**Comment by rockstone533** [comment]
@dutran  I've solved the 2nd error by uncomment the last line of CUDA_ARCH in makefile.config.But how can I sovle the 1st error? Could you help me?The whole message are as follows.



I0921 21:17:04.632088  6032 video_data_layer.cpp:344] read video from /data/users/trandu/datasets/ucf101/frm/JumpingJack/v_JumpingJack_g25_c05/
F0921 21:17:04.632129  6032 video_data_layer.cpp:346] Check failed: ReadImageSequenceToVolumeDatum(file_list_[id].c_str(), 1, label_list_[id], new_length, new_height, new_width, sampling_rate, &datum) 
*** Check failure stack trace: ***
    @     0x7efd01251c7d  google::LogMessage::Fail()
    @     0x7efd01253b30  google::LogMessage::SendToLog()
    @     0x7efd01251842  google::LogMessage::Flush()
    @     0x7efd0125454e  google::LogMessageFatal::~LogMessageFatal()
    @           0x4b01fe  caffe::VideoDataLayer<>::SetUp()
    @           0x4458cb  caffe::Net<>::Init()
    @           0x446b75  caffe::Net<>::Net()
    @           0x43412f  caffe::Solver<>::Init()
    @           0x43783b  caffe::Solver<>::Solver()
    @           0x40b826  main
    @     0x7efcfcfd9a40  (unknown)
    @           0x40e079  _start
Aborted (core dumped)

**Comment by dutran** [comment]
The first issue is with I/O, do you have any frames at /data/users/trandu/datasets/ucf101/frm/JumpingJack/v_JumpingJack_g25_c05/ ?

It is likely that you did not have data here because this is the absolute path on my setting. If your frames are at different location, then you need to modify the list file to point to your path.

**Comment by dutran** [comment]
@rockstone533 have you figured out your issue?

**Comment by rockstone533** [comment]
@dutran Yeah, I've modified the frm path, but it seems that my memory isn't enough.
1.How much memory do I need to finetune C3D model  on UCF101?
2.How do you extract frms from videos?
3.If I wanna train volume data, can I use C3D?

**Comment by dutran** [comment]
1. It needs around 10GB (e.g. a K40), but if you have less memory, you can reduce batch size
2. You can use ffmpeg
3. You can use it, but may need to provide your specific-IO functions and modify video-data-layer to handle it.

**Comment by thierrypin** [comment]
I'm having this trouble. I suspect it is caused by the image extension. Does it have to be JPEG? I'm trying to load PNGs.

**Comment by bhattif** [comment]
> @rockstone533 have you figured out your issue?

dutran, I have the same issue and I have checked the path which is correctly pointing to my frms. But I am still getting this error - any thoughts please.

F0912 12:11:16.601537  3004 video_data_layer.cpp:346] Check failed: ReadImageSequenceToVolumeDatum(file_list_[id].c_str(), start_frm_list_[id], label_list_[id], new_length, new_height, new_width, sampling_rate, &datum)
