### ISSUE TITLE
In what way turn the video into pictures

### ISSUE THREAD

**Issue by jetyingjia** [facebook/C3D#330]
Hi,@dutran, Can you tell me what kind of way you turn the video into pictures? ffmpeg or opencv?
I find the picture size is small getted from ffmpeg than opencv, and the performance is also inferior to opencv.
When testing on UCF101, a video is split into 16 frame long clips with a 8-frame overlap or not?
Thank you in advance!

**Comment by dutran** [comment]
If training using frames input, I used ffmpeg to extract frames then train models. If use videos directly, our code use opencv (with ffmpeg) to decode videos during training.
