### ISSUE TITLE
A question about iter in C3D testing

### ISSUE THREAD

**Issue by JerryYaoGl** [facebook/C3D#331]
Hi Du,

Thank you for your good works C3D.

I have a quesion about the testing.
There a 41822 clips in test list.

In training experiment, the bath_size is 30 in test.prototxt.
41822/30 = 1394.06 = 1395
Why the iter is 1396 in the test.sh? 

In finetuning experiment, The bath_size is 50 in test.prototxt.
41822/50 = 836.44 = 837
Why the iter is 838 in the test.sh?

Thank you so much.

**Comment by dutran** [comment]
Technically it should be rounded (as your calculation). If it has one iteration more (assume it is as you pointed out), it does not make a big difference.
