### ISSUE TITLE
Use c3d_resnet18_sports1m_r2_iter_2800000.caffemodel from c3d_ucf101_finetuning, but the connection failed.

### ISSUE THREAD

**Issue by angd123** [facebook/C3D#333]
Use https://www.dropbox.com/s/qqfrg6h44d4jb46/c3d_resnet18_sports1m_r2_iter_2800000.caffemodel from c3d_ucf101_finetuning, but the connection failed.Can anyone answer it? thank you very much.
I tried it several times and has always been this error message.

https://www.dropbox.com/s/qqfrg6h44d4jb46/c3d_resnet18_sports1m_r2_iter_2800000.caffemodel
Resolving host  www.dropbox.com (www.dropbox.com)... 205.186.152.122, 31.13.78.66
connecting www.dropbox.com (www.dropbox.com)|205.186.152.122|:443... Failed:connection timed out.
connecting www.dropbox.com (www.dropbox.com)|31.13.78.66|:443... ... Failed:connection timed out.

**Comment by dutran** [comment]
It seems working fine to me. Alternative url: https://drive.google.com/drive/folders/0Bx-2rTokRAt1WjhmRU4xZ05Zams
