### ISSUE TITLE
I run C3D-v1.1 in ucf-101. When I run train_simple.sh,error occured!

### ISSUE THREAD

**Issue by Jessespace** [facebook/C3D#334]
I1204 14:17:49.945123 11220 layer_factory.hpp:77] Creating layer data
I1204 14:17:49.945164 11220 net.cpp:84] Creating Layer data
I1204 14:17:49.945169 11220 net.cpp:380] data -> data
I1204 14:17:49.945188 11220 net.cpp:380] data -> label
I1204 14:17:49.945536 11220 video_data_layer.cpp:67] Opening file train_01.lst
I1204 14:17:50.000282 11220 video_data_layer.cpp:130] Shuffling data
I1204 14:17:50.001407 11220 video_data_layer.cpp:140] A total of 107258 video chunks.
I1204 14:17:50.154569 11220 video_data_layer.cpp:182] output data size: 30,3,16,112,112
I1204 14:17:50.261296 11220 net.cpp:122] Setting up data
I1204 14:17:50.261332 11220 net.cpp:129] Top shape: 30 3 16 112 112 (18063360)
I1204 14:17:50.261335 11220 net.cpp:129] Top shape: 30 (30)
I1204 14:17:50.261337 11220 net.cpp:137] Memory required for data: 72253560
I1204 14:17:50.261343 11220 layer_factory.hpp:77] Creating layer conv1a
I1204 14:17:50.261355 11220 net.cpp:84] Creating Layer conv1a
I1204 14:17:50.261360 11220 net.cpp:406] conv1a <- data
I1204 14:17:50.261373 11220 net.cpp:380] conv1a -> conv1a
I1204 14:17:50.263443 11220 net.cpp:122] Setting up conv1a
I1204 14:17:50.263469 11220 net.cpp:129] Top shape: 30 64 16 112 112 (385351680)
I1204 14:17:50.263473 11220 net.cpp:137] Memory required for data: 1613660280
I1204 14:17:50.263543 11220 layer_factory.hpp:77] Creating layer relu1a
I1204 14:17:50.263566 11220 net.cpp:84] Creating Layer relu1a
I1204 14:17:50.263569 11220 net.cpp:406] relu1a <- conv1a
I1204 14:17:50.263572 11220 net.cpp:367] relu1a -> conv1a (in-place)
F1204 14:17:50.431455 11220 blob.hpp:140] Check failed: num_axes() <= 4 (5 vs. 4) Cannot use legacy accessors on Blobs with > 4 axes.
*** Check failure stack trace: ***
    @     0x7fb5abf0d5cd  google::LogMessage::Fail()
    @     0x7fb5abf0f433  google::LogMessage::SendToLog()
    @     0x7fb5abf0d15b  google::LogMessage::Flush()
    @     0x7fb5abf0fe1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb5ac4a6e66  caffe::CuDNNReLULayer<>::Reshape()
    @     0x7fb5ac663776  caffe::Net<>::Init()
    @     0x7fb5ac665fce  caffe::Net<>::Net()
    @     0x7fb5ac66e96a  caffe::Solver<>::InitTrainNet()
    @     0x7fb5ac66fdd5  caffe::Solver<>::Init()
    @     0x7fb5ac6700ff  caffe::Solver<>::Solver()
    @     0x7fb5ac63f911  caffe::Creator_SGDSolver<>()
    @           0x40bed3  train()
    @           0x408590  main
    @     0x7fb5aad2a830  __libc_start_main
    @           0x408db9  _start
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by dutran** [comment]
using this PR can fix your issue of 
@mattphillipskitware (https://github.com/facebook/C3D/pull/327). Let me know if it works, then I can pull it to master.
