### ISSUE TITLE
Question about the speed of finetuning

### ISSUE THREAD

**Issue by JerryYaoGl** [facebook/C3D#335]
Hi Du,

I conducted finetuning on two datasets (UCF101 and UCF Sports).
UCF Sports contains 150 videos, and I selected 100 videos from them for training.
Compare with UCF101, UCF Sports is extremely small.

When I conducted finetuing using C3D, the speeds of these two datasets are almost same. (I thought the finetuning speed of the UCF Sports should be higher)

When I conducted finetuing using ResC3D, the finetuing speed of the UCF Sports is much slower than the speed of UCF101. (I thought the finetuning speed of the UCF Sports should be higher)

Why? Could you help to resolve this question?
Or is there some mistake when I conducted finetuning.

(UCF101 finetuning, I used your code)
(UCF Sports finetuning, I prepared the videos, changed num_output and mean_value_file(in C3D))

Thank you so much.

B,R,
Yao

**Comment by dutran** [comment]
You need to change the number of iterations and step size in solver to reflect the size of the dataset.
https://github.com/facebook/C3D/blob/master/C3D-v1.0/examples/c3d_finetuning/c3d_ucf101_finetuning_solver.prototxt#L10-L14
https://github.com/facebook/C3D/blob/master/C3D-v1.1/examples/c3d_ucf101_finetuning/solver_r2.prototxt#L12-L16
