### ISSUE TITLE
question about reading videos and extracting frames

### ISSUE THREAD

**Issue by JerryYaoGl** [facebook/C3D#336]
Hi Du,

There is a log "no data at frame xxx" in the C3D finetuing using videos.
But there is no this log in the ResC3D finetuing.
Q1. If this log is caused by ffmpeg? But why this log doesNOT appear in ResC3D finetuing?
Q2. Shuold I resolve this log in C3D finetuning?

Another question:
When I conducted finetuning using frames.
The train_01.lst and the extracted frames for UCF101 in C3D.zip is a little different with the my list and frames generated from UCF101 by reading the frame using Opencv.(small parts of videos are different)
Q3. Caused by the different versions of tools (opencv or ffmpeg)? or caused by the different fps in frame extracton?
Q4. Shuold I resolve the difference to have same list and frames with yours?

Thank you so much.

B.R.
Yao

**Comment by dutran** [comment]
C3D and Res3D has minor logging differences in code, so you should not be worry about the logging message. Frames extracted can be different by difference decoder and its options. I used ffmpeg with lossless extraction e.g. -q:v 1 (non compressed frame output) for UCF101. I note there some quality difference when we use compressed frames (default ffmpeg w/o specify option -q:v 1 )
