### ISSUE TITLE
Example for volume_data_layer

### ISSUE THREAD

**Issue by ntajbakhsh** [facebook/C3D#34]
Hi Dutran,

Thank you for creating and sharing this fork! From the examples you have provided, I understand that you have developed this package primarily for video data analysis, but I have also noticed the implementation for  "volume_data_layer", which takes a level-db as its input. I think a  volume_data_layer for 64x64x50 subvolumes should simply look like this 

layers {
  name: "data"
  type: VOLUME_DATA
  top: "data"
  top: "label"
  image_data_param {
    source: "vol_6x64x50_leveldb"
    mean_file: "vol_mean_64x64x50.binaryproto"
    batch_size: 30
    mirror: false
    show_data: 0
    shuffle: true
  }
}

But I don't know how to generate a leveldb file for the volumetric data. If you happen to have such a script, could you please share it with us? A few posts on the caffe's github page suggest the use of hdf5 for volumetric data but no mentions of leveldb...So, I would appreciate if you could explain how such a leveldb file can be generated. 

Thank you! 
Nima

**Comment by dutran** [comment]
Yes, i wrote the volume data layer for level-db back then. You can look into some functions like (and modify it for your purpose):
ReadImageSequenceToVolumeDatum and ReadVideoToVolumeDatum (in https://github.com/facebook/C3D/blob/master/src/caffe/util/image_io.cpp)
and an example like:
https://github.com/facebook/C3D/blob/master/examples/cifar10/convert_cifar_data.cpp

In short, if your data is not video, e.g. CT Scans of medical images, then you need to have a I/O function e.g.
ReadCTSlideToVolumeDatum
and then look into https://github.com/facebook/C3D/blob/master/examples/cifar10/convert_cifar_data.cpp
to do a similar job of creating a level-db.

*Note level-db is fast, but it uses a mutex-lock, so you can run only one training on a leveldb at a time.
