### ISSUE TITLE
when created layer conv1_relu, the network checked failures!

### ISSUE THREAD

**Issue by potazhou** [facebook/C3D#340]
this issue as follows:
...
I1214 18:19:03.116343 18000 net.cpp:84] Creating Layer conv1_relu
I1214 18:19:03.116348 18000 net.cpp:406] conv1_relu <- conv1
I1214 18:19:03.116353 18000 net.cpp:367] conv1_relu -> conv1 (in-place)
F1214 18:19:03.324808 18000 blob.hpp:140] Check failed: num_axes() <= 4 (5 vs. 4) Cannot use legacy accessors on Blobs with > 4 axes.
...
 Has it been happened?  thanks!

**Comment by dutran** [comment]
in you makefile, turn off CuDNN option, it will fix the issue. There is one PR (https://github.com/facebook/C3D/pull/327) to fix this with cuDNN as well.
