### ISSUE TITLE
The question about the blob shape

### ISSUE THREAD

**Issue by potazhou** [facebook/C3D#341]
hi, I just have a problem when I look at the blob.cpp and the convolution3d_layer.cpp:
the dims of blob shape are 4 or 5?
if 4, during the convolution3d_layer.cpp, the representation of blob:
num_ = bottom[0]->shape(0);
  channels_ = bottom[0]->shape(1);
  length_ = bottom[0]->shape(2);
  height_ = bottom[0]->shape(3);
  width_ = bottom[0]->shape(4);
if 5, during the function Reshape of the blob.cpp, only having the variates:
  vector<int> shape(4);
  shape[0] = num;
  shape[1] = channels;
  shape[2] = height;
  shape[3] = width;
  Reshape(shape);
I may be not understand the ideas of your code, because the previous C3D network had 5dims.  If you see my question, please reply message to me! Thank you vary much!

**Comment by dutran** [comment]
for 3D ConvNet, blob is 5D tensor of batch_size x channels x length x height x width.

**Comment by potazhou** [comment]
@dutran ,well, thanks! But I want to get a deploy file so that I can do prediction in my C++ code which I just need transmit my data set (such as the number of frames is 16) to the net_->input_blobs() . And the format of input data is :
...
input: data
input_shape {
dim: 1 # batch size
dim: 3 # channels
dim: 8 # temporal length
dim: 112 # height
dim: 112 # width
}
...
May I finish it? Thank you!
