### ISSUE TITLE
The problem about parameter： sampling_rate

### ISSUE THREAD

**Issue by potazhou** [facebook/C3D#342]
hi， may I ask a question about the data layer?
The parameters both new_length and sampling_rate are initial as:
......
new_length: 8
sampling_rate: 2
......
How work they are?  In my train.lst, the format of data is:
normal/11 1 0	
normal/11 17 0	
normal/11 33 0	
normal/11 49 0	
normal/11 65 0	
normal/11 81 0	
......
Sampling per 16, while I do test, I find the length I must set 8! What's wrong?
And,
new_length: 16
sampling_rate: 1
Are there any different?

**Comment by dutran** [comment]
the clip_length = 8, however sampling = 2 meaning you skip every other frame.
