### ISSUE TITLE
question about ucf101_finetuning.sh

### ISSUE THREAD

**Issue by nicebaby** [facebook/C3D#343]
when I run the ucf101_finetuning.sh(examples/c3d_finetuning) ,the following question is:

I1224 17:09:40.411164  7406 video_data_layer.cpp:317] A total of 107258 video chunks.
E1224 17:09:40.411537  7406 image_io.cpp:111] Cannot open UCF101/UCF-101/JumpingJack/v_JumpingJack_g25_c05.avi/
F1224 17:09:40.411547  7406 video_data_layer.cpp:341] Check failed: ReadVideoToVolumeDatum(file_list_[id].c_str(), start_frm_list_[id], label_list_[id], new_length, new_height, new_width, sampling_rate, &datum) 
*** Check failure stack trace: ***
    @     0x7f0fbb09a5cd  google::LogMessage::Fail()
    @     0x7f0fbb09c433  google::LogMessage::SendToLog()
    @     0x7f0fbb09a15b  google::LogMessage::Flush()
    @     0x7f0fbb09ce1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x4e32b6  caffe::VideoDataLayer<>::SetUp()
    @           0x43efb7  caffe::Net<>::Init()
    @           0x440475  caffe::Net<>::Net()
    @           0x44455f  caffe::Solver<>::Init()
    @           0x44736b  caffe::Solver<>::Solver()
    @           0x40c83d  main
    @     0x7f0fb326b830  __libc_start_main
    @           0x40ea89  _start
    @              (nil)  (unknown)
./ucf101_finetuning.sh: 行 1:  7406 已放弃               (核心已转储) GLOG_logtostderr=1 ../../build/tools/finetune_net.bin c3d_ucf101_finetuning_solver.prototxt ../c3d_feature_extraction/conv3d_deepnetA_sport1m_iter_1900000
Tried many ways, but still no solution.I would appreciated for some advice,very thanks!

**Comment by dutran** [comment]
@nicebaby You may want to extract your videos UCF101/UCF-101/JumpingJack/v_JumpingJack_g25_c05.avi into frames, e.g. UCF101/UCF-101/JumpingJack/v_JumpingJack_g25_c05/%06d.jpg before you do fine-tuning
