### ISSUE TITLE
some questions about train/test ucf101

### ISSUE THREAD

**Issue by jetyingjia** [facebook/C3D#347]
Hi,@dutran;
 I have some questions about train/test ucf101.
 a.train: how to do the video to get the train dataset? 
            1. randomly sampled 10 clips per video;
            2. uniformed sampled 10 clips per video;
            3. get consecutive frames per video, just as the release train_01.lst
            4. other method?
b. test:  how to de the test clip for per video?
            1. randomly sampled 10 clips per video;
            2. uniformed sampled 10 clips per video;
            3. get consecutive frames per video, just as the release test_01.lst
            4. other method?
Thank you in advance!

**Comment by dutran** [comment]
just as train_01.lst and test_01.lst.
