### ISSUE TITLE
Frames Extracted from Videos

### ISSUE THREAD

**Issue by myaldiz** [facebook/C3D#353]
Hello!

I was wondering the effect of extracted number of frames per second to the final accuracy. As far as I understand, we select consecutive 16 frames from videos having 25~30 fps. Which means clips constitute less than 1 second. I was curious whether having clips covering longer period of times, say 2 seconds ie (8 fps per clip) would effectively change accuracy? Since some actions covered really briefly for the network, is it really enough to understand? Or did I miss something about implementation or paper?

Thank you..

**Comment by dutran** [comment]
@myaldiz it will effect the performance. In our paper (e.g. Res3D), we use sampling of 2 (for videos of 25-30fps), meaning it is equivalent with video of 12-15fps with sampling=1. Depend on your video frame rate you can adjust. Finally, you can always fine-tune the models to adapt to your video distribution for the best performance.
