### ISSUE TITLE
Test accuracy on 3D-Res18.

### ISSUE THREAD

**Issue by zzy123abc** [facebook/C3D#354]
I train from scratch on UCF-101 by 3D-Res18.
This is solver.

net: "train_resnet18_r2.prototxt"
#test_iter: 100
#test_state: { stage: 'test-on-train' }
#test_iter: 100
#test_state: { stage: 'test-on-val' }
#test_interval: 0
base_lr: 0.01
momentum: 0.9
weight_decay: 0.005
lr_policy: "step"
gamma: 0.1
stepsize: 40000
#Display every 20 iterations
display: 20
#The maximum number of iterations
max_iter: 180000
#snapshot intermediate results
snapshot: 10000
snapshot_prefix: "c3d_resnet18_ucf101_r2_ft"
solver_mode: GPU

And I use your train_resnet18_r2.prototxt.
However I just get 0.16 score.And loss did not decrease.Your paper says your score is 0.456.
What's wrong with it?

**Comment by dutran** [comment]
@zzy123abc here are my prototxt and my model https://www.dropbox.com/sh/i73b9h2evxrlyf4/AAAp6yiOQv_lUuYgLPUhW50Pa?dl=0

**Comment by zzy123abc** [comment]
Sorry,my batchsize can only set 5.Even I use two gpus,it can reach 10,but not 20.Is this the problem I can not reimplement your paper?How can I solve this problem,thanks.
