### ISSUE TITLE
test_ucf101.sh

### ISSUE THREAD

**Issue by nicebaby** [facebook/C3D#355]
GLOG_logtostderr=1 ../../build/tools/test_net.bin conv3d_ucf101_test.prototxt conv3d_ucf101_iter_60000 1396 GPU 0
What does this 1396 mean?
Can you help me answer, thanks

**Comment by zzy123abc** [comment]
It's the iteration of the test,for example , epoch = iteration * batch size

**Comment by dutran** [comment]
@zzy123abc Thanks for helping!
