### ISSUE TITLE
About sh c3d_sport1m_feature_extraction_video.sh

### ISSUE THREAD

**Issue by mengliu1991** [facebook/C3D#358]
Hi,
  When I run the demo c3d_sport1m_feature_extraction_video.sh, it occurs the following erros, I do not know why?
I0212 21:03:10.133091 21792 image_io.cpp:143] No data at frame 80
F0212 21:03:16.556785 21792 video_data_layer.cpp:123] Check failed: read_status Testing must not miss any example
*** Check failure stack trace: ***
c3d_sport1m_feature_extraction_video.sh: line 3: 21727 Aborted                 (core dumped) GLOG_logtosterr=1 ../../build/tools/extract_image_features.bin prototxt/c3d_sport1m_feature_extractor_video.prototxt conv3d_deepnetA_sport1m_iter_1900000 14 50 1 prototxt/output_list_video_prefix.txt fc7-1 fc6-1 prob

 Besides, I run the demo extract_C3D_feature_example.sh, it is run correctly. 
 And I find that this demo is also on video feature extraction. Is there any difference between the above two demos. Namely, if the c3d_sport1m_feature_extraction_video.sh firstly extract frames, and then use the frm_prorotxt file to extract features as the demo extract_C3D_feature_example.sh do.

**Comment by XiongChengxin** [comment]
Hi, same error occurs to me, have you solved it?

**Comment by mengliu1991** [comment]
@XiongChengxin  No, I haven't solved it.  I just extract key frames and then using frame-level c3d feature extraction.

**Comment by dutran** [comment]
The VideoData layer cannot read the video you provided, thus cannot pass a hard check on missing data.
