### ISSUE TITLE
different clip length feature extraction based on your released mode 

### ISSUE THREAD

**Issue by mengliu1991** [facebook/C3D#359]
Hi, 

  I find that the released C3D_sport1M_model is trained with clip length 16. But we want to extract features of different length clips, such as 64,128, 256. How can we use your released model to extract these features?

**Comment by dutran** [comment]
you can chop your video into multiple 16-frame clips (can be overlapped with each other or not, depend on your own design). The clip feature are then average pooled, then L2-normalized as suggested in the paper.
