### ISSUE TITLE
Question about the LeNet Implmention on Jupyter Notebook

### ISSUE THREAD

**Issue by Zephyr06** [facebook/C3D#362]
I am one beginner who just installed caffe on my laptop. When I tried to execute caffe/examples/01-learning-lenet.ipynb on the Jupyter Note, as suggested on the website, the kernel always died and then restart when executing codes below:

caffe.set_device(0)
caffe.set_mode_gpu()
### load the solver and create train and test nets
solver = None  # ignore this workaround for lmdb data (can't instantiate two solvers on the same data)
solver = caffe.SGDSolver('mnist/lenet_auto_solver.prototxt') 

So is there anyone who can help me with this problem? Any help is appreciating!

**Comment by dutran** [comment]
You can check multiple tutorials of caffe here http://caffe.berkeleyvision.org/tutorial/
