### ISSUE TITLE
feature embedding

### ISSUE THREAD

**Issue by wangwen39** [facebook/C3D#363]
Hi,thanks for your wonderful work!
 In the paper "Learning Spatiotemporal Features with 3D Convolutional Networks" of Figure 6: How can I get the feature embedding visualizations ? use t-SNE to reducingdimension? Could you please release the code? Thanke you so much!

**Comment by dutran** [comment]
There are multiple Tsne implementations, check them out here: https://lvdmaaten.github.io/tsne
