### ISSUE TITLE
How to statistical classification result?

### ISSUE THREAD

**Issue by zhangshuaimm** [facebook/C3D#370]
I have trained my data from scrach and got a good result.see picture,I want to know which class was misclassified. Is there any way? Thanks!
![_20180329120926](https://user-images.githubusercontent.com/28031613/38069668-1f23854e-334a-11e8-876a-ce65d621a51a.png)

**Comment by dutran** [comment]
Use feature extraction tools to extract predictions for clips and you should know predictions for each clip.
