### ISSUE TITLE
How to output confusion matrix during testing ? 

### ISSUE THREAD

**Issue by ManhTruongDang** [facebook/C3D#374]
Hi, in the testing phase, we use: 

> sh test_ucf101.sh # test the accuracy of training

The content of test_ucf101.sh is:

> GLOG_logtostderr=1 ../../build/tools/test_net.bin conv3d_ucf101_test.prototxt conv3d_ucf101_iter_60000 1396 GPU 0

But what should I do if I want to output the confusion matrix ?
Please help me, thank you very much.

**Comment by dutran** [comment]
it does not support confusion matrix, you have to do it manually from predictions.
