### ISSUE TITLE
How to use Deconvolution3DLayer for 3D interpolation?

### ISSUE THREAD

**Issue by happyzhouch** [facebook/C3D#375]
I found that DeconvolutionLayer can act for bilinear interpolation, http://caffe.berkeleyvision.org/doxygen/classcaffe_1_1BilinearFiller.html.
How can I use Deconvolution3DLayer for 3D interpolation? Is the same as 2D DeconvolutionLayer ?

**Comment by dutran** [comment]
This is the same 2D except for it is in 3D, e.g. the upsampling kernel project into a cubic, rather than square, in the output tensor. Also output tensors for 3D is 5D (batch x channels x T x H x W) while 2D case is 4D (batch x channels x H x W)

**Comment by dksakkos** [comment]
Do the weights need to be initialized with a specific filler? Because bilinear filler isn't applicable and gaussian produces zero outputs.
