### ISSUE TITLE
High loss in training C3D with UCF101

### ISSUE THREAD

**Issue by XQLee1** [facebook/C3D#378]
Hi,

I have used your public version of modified caffe named video-caffe-master, and I have trained C3D-UCF101 there whose loss can down form 4.7 to 0.01. Now I used your new version of C3D-v1.1 and used the same parameter in training and solver file. But no matter how to change it, the training can only reduce the loss from 4.8 to 2, and sometimes appear the loss of 87.3. I don't know what's the problem with the new version. Could you please help me?

Regards,

**Comment by dutran** [comment]
Can you try to clone code before the PR https://github.com/facebook/C3D/pull/327 which supports CUDNN, I did not fully test it yet

**Comment by Caroline1994** [comment]
Hi, @dutran 
Would you mind telling me how to make my own behavior dataset that fits C3D training? What tools I can use  to intercept 16 frames of video

**Comment by dutran** [comment]
Video_data layer allows input in frames or videos, when using with videos, it allow you can specify start_frame for each clip or can be randamly generate (e.g. temporal_jitter), please read the video_data_layer for more details, sorry for not providing better documentation. If you still early in your project, we encourage you to use: https://github.com/facebookresearch/R2Plus1D in which we plan to have better docs and supports.
