### ISSUE TITLE
How to output the accuracy of  a single input video?

### ISSUE THREAD

**Issue by Jessespace** [facebook/C3D#385]
How to output the accuracy of  a single input video?

**Comment by Jessespace** [comment]
like this

![image](https://user-images.githubusercontent.com/24760248/39964358-7f909c76-56b5-11e8-85e3-c62a3a8df08f.png)

**Comment by dutran** [comment]
This one is not supported in the current repo, you can use feature_extraction tool extract softmax prediction for clips (densely from a video).
