### ISSUE TITLE
c3d_resnet18_sports1m_r2_iter_2800000.caffemodel

### ISSUE THREAD

**Issue by baixuexue** [facebook/C3D#387]
I can't download c3d_resnet18_sports1m_r2_iter_2800000.caffemodel from the link you provided. can you share it ? Thanks!

**Comment by dutran** [comment]
Since it is a known issue for IP from China cannot download Dropbox link, here is a Google drive link: https://drive.google.com/open?id=0Bx-2rTokRAt1bzNDNGVBei1mODg
