### ISSUE TITLE
Train features by SVM

### ISSUE THREAD

**Issue by fahimeh62** [facebook/C3D#41]
Hi Du,

I extracted the features successfully, how can I train them by SVM? Should I use Matlab or I can use "hinge loss layer" in Caffe for this purpose?
Could you please tell me the required steps after reading features by your script in matlab?
Thanks in advance!

**Comment by dutran** [comment]
There are many ways to experiment with SVM, but if you use only linear SVM, liblinear seems a reasonable option.

**Comment by fahimeh62** [comment]
Hi Du,
How did you use extracted features for training by SVM? Did you read them by your matlab script and then concatenate features of all classes and then use svmtrain function in matlab?
Cheers.

**Comment by alice0522** [comment]
> There are many ways to experiment with SVM, but if you use only linear SVM, liblinear seems a reasonable option.

Hi! Do you mind giving me the code of C3D+linearn SVM?
