### ISSUE TITLE
 Could not open or find file on example

### ISSUE THREAD

**Issue by alanotmt** [facebook/C3D#427]
i tried to use C3D-v1.1  feature_extraction.sh.
 follow  C3D User Guide to make it and i got this error:

 Could not open or find file /data/users/trandu/datasets/ucf101/frm/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01//000001.jpg

i check other user question like me, but they same question on training.

so where can i change this path on it? 

thank you for your help.

**Comment by dutran** [comment]
You do not have data at that location (e.g. /data/users/trandu/datasets/ucf101/frm/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01//000001.jpg), while the tool looks for it.
