### ISSUE TITLE
Where to locate ../../build/tools/extract_image_features.bin after re-compile?

### ISSUE THREAD

**Issue by VivaaindreanNg** [facebook/C3D#429]
I've 2 questions:
1. I got the error ../../build/tools/extract_image_features.bin is not found, because I didn't compile successfully. So, I have to re-start compiling all of the stuffs based on this link: http://vra.github.io/2016/03/03/c3d-use/ right? But I've done so and still got the same error:
![image](https://user-images.githubusercontent.com/40485262/53610623-81671e80-3c06-11e9-8ce7-3fa7e8a9586c.png)

2. So after I've done re-compiling, I want to confirm on the location of this extract_image_features.bin. I'll find the file in C3D-v1.0/build/tools/extract_image_features.bin , correct?

**Comment by EMCL** [comment]
yes me too

**Comment by Liu0114** [comment]
I got the error  file ../../build/tools/extract_image_features.bin is not foud,I want to know where the file?

**Comment by kjsr7** [comment]
The entire build directory gets generated once the build process is successful.

**Comment by Liu0114** [comment]
How to build ? Is there  a reference?

**Comment by kjsr7** [comment]
[This ](https://github.com/facebook/C3D/blob/master/C3D-v1.0/docs/installation.md)would help you I guess.

**Comment by Liu0114** [comment]
I have  build  Caffe successfully on CPU,but I don't find the bin file following the guidance

**Comment by dutran** [comment]
yes, you need to build it successfully to have the binary.

**Comment by Liu0114** [comment]
I want to build the v1.0 on CPU,but I have a error "./include/caffe/common.hpp:7:23: fatal error:cublas_v2.h: No such file or directory"when building

**Comment by Liu0114** [comment]
I want  to build the C3D_1.0 on CPU,but I have a error"cublas_v2.h:No such file or directory",How should modify the file?

**Comment by Liu0114** [comment]
How can I check my exacted features,and how to open them?

**Comment by Liu0114** [comment]
I changed the batch size 1,but I don't find any feature in the file however the shell show feature are exacted successfully.

**Comment by SatyaKrishna** [comment]
@Liu0114 check input file path in  "c3d_sport1m_feature_extractor_video.prototxt" and paths for chunks specified in input_list_video.txt and output_list_videos_prefix.txt.
