### ISSUE TITLE
C3D Feature Extraction: Error with frame based model

### ISSUE THREAD

**Issue by andrubrown** [facebook/C3D#43]
I'm working thorough the example of training from scratch on UCF101.

I'm able to extract the frames to jpeg with ffmpeg and I edited the test_01 and train_01 lists to the appropriate folder locations. I am able to run  create_volume_mean.sh but I encounter the following error when I run the train_ucf101.sh:

I1119 18:47:24.556890 31767 train_net.cpp:26] Starting Optimization
I1119 18:47:24.557006 31767 solver.cpp:41] Creating training net.
I1119 18:47:24.557912 31767 net.cpp:76] Creating Layer data
I1119 18:47:24.557937 31767 net.cpp:112] data -> data
I1119 18:47:24.557951 31767 net.cpp:112] data -> label
I1119 18:47:24.557973 31767 video_data_layer.cpp:283] Opening file ../c3d_finetuning/train_01.lst
I1119 18:47:24.622956 31767 video_data_layer.cpp:312] Shuffling data
I1119 18:47:25.010337 31767 video_data_layer.cpp:317] A total of 107258 video chunks.
I1119 18:47:25.010380 31767 video_data_layer.cpp:344] read video from /home/andrew/caffe/C3D/data/UCF-101/JumpingJack/v_JumpingJack_g25_c05/
F1119 18:47:25.010423 31767 video_data_layer.cpp:346] Check failed: ReadImageSequenceToVolumeDatum(file_list_[id].c_str(), 1, label_list_[id], new_length, new_height, new_width, sampling_rate, &datum) 
*** Check failure stack trace: ***
    @     0x7f5c43b5adaa  (unknown)
    @     0x7f5c43b5ace4  (unknown)
    @     0x7f5c43b5a6e6  (unknown)
    @     0x7f5c43b5d687  (unknown)
    @           0x49d43e  caffe::VideoDataLayer<>::SetUp()
    @           0x450905  caffe::Net<>::Init()
    @           0x451bb5  caffe::Net<>::Net()
    @           0x43172f  caffe::Solver<>::Init()
    @           0x434e3b  caffe::Solver<>::Solver()
    @           0x40ab46  main
    @     0x7f5c41638ec5  (unknown)
    @           0x40d3b7  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

I've been scratching my head. Any thoughts?

**Comment by dutran** [comment]
what does a 'ls /home/andrew/caffe/C3D/data/UCF-101/JumpingJack/v_JumpingJack_g25_c05/'
tells you?

**Comment by andrubrown** [comment]
$ ls /home/andrew/caffe/C3D/data/UCF-101/JumpingJack/v_JumpingJack_g25_c05/
ls: cannot access /home/andrew/caffe/C3D/data/UCF-101/JumpingJack/v_JumpingJack_g25_c05/: No such file or directory

**Comment by andrubrown** [comment]
$ ls /home/andrew/caffe/C3D/data/UCF-101/JumpingJack/v_JumpingJack_g25_c05/
100.jpg  112.jpg  20.jpg  32.jpg  44.jpg  56.jpg  68.jpg  7.jpg   91.jpg
101.jpg  113.jpg  21.jpg  33.jpg  45.jpg  57.jpg  69.jpg  80.jpg  92.jpg
102.jpg  114.jpg  22.jpg  34.jpg  46.jpg  58.jpg  6.jpg   81.jpg  93.jpg
103.jpg  11.jpg   23.jpg  35.jpg  47.jpg  59.jpg  70.jpg  82.jpg  94.jpg
104.jpg  12.jpg   24.jpg  36.jpg  48.jpg  5.jpg   71.jpg  83.jpg  95.jpg
105.jpg  13.jpg   25.jpg  37.jpg  49.jpg  60.jpg  72.jpg  84.jpg  96.jpg
106.jpg  14.jpg   26.jpg  38.jpg  4.jpg   61.jpg  73.jpg  85.jpg  97.jpg
107.jpg  15.jpg   27.jpg  39.jpg  50.jpg  62.jpg  74.jpg  86.jpg  98.jpg
108.jpg  16.jpg   28.jpg  3.jpg   51.jpg  63.jpg  75.jpg  87.jpg  99.jpg
109.jpg  17.jpg   29.jpg  40.jpg  52.jpg  64.jpg  76.jpg  88.jpg  9.jpg
10.jpg   18.jpg   2.jpg   41.jpg  53.jpg  65.jpg  77.jpg  89.jpg
110.jpg  19.jpg   30.jpg  42.jpg  54.jpg  66.jpg  78.jpg  8.jpg
111.jpg  1.jpg    31.jpg  43.jpg  55.jpg  67.jpg  79.jpg  90.jpg

**Comment by dutran** [comment]
Use %06d.jpg instead

**Comment by andrubrown** [comment]
Cool I'll give it a shot.

I tried %d first because the test_01 and train_01 lists seem to be in the %d format.

If I'm setting up my own frames the same should be true?:

folders - 000001.jpeg, 000002.jpeg... etc

and

train_01 - 1, 17.... etc

**Comment by dutran** [comment]
That should work, see here: https://github.com/facebook/C3D/blob/master/src/caffe/util/image_io.cpp#L191

**Comment by andrubrown** [comment]
Awesome Thanks Du looks like its working like a charm. Thanks for your quick response. I'me excited to try this out!

**Comment by jcpeterson** [comment]
Do you still have your .lst file for this? If so, I would love to see. I'm having trouble getting the format right since there are no explicit examples with jpg files.

**Comment by bhattif** [comment]
Dear Dutran, I am having the same issue as above. However, I am not understanding what you mean by using %06d.jpg . Does this mean that ' 20.jpg ' should be written as ' %20d.jpg '. 
Many thanks 
Farrukh
