### ISSUE TITLE
META DATA FILES FOR UCF-101 DATASET

### ISSUE THREAD

**Issue by abhisheksurya578** [facebook/C3D#432]
Hello @zpao @ericnakagawa @killian @achao @cdelahousse 

I'm doing research regarding action recognition.
I just downloaded UCF 101 dataset for action Recognition
But I need MetaData and Json Files and Description Files.
If any one can help us please forward the files.

Can any one please help me in Data Augmentation for this Dataset.

**Comment by dutran** [comment]
you can contact the author(s) of UCF101 here https://www.crcv.ucf.edu/data/UCF101.php
