### ISSUE TITLE
static link error with anaconda

### ISSUE THREAD

**Issue by Anirudh58** [facebook/C3D#435]
I am trying to set up caffe on CPU, 
when i try to run `make all` i get the following error

Makefile:320: *** Cannot static link with the /home/a.prabakaran/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++ compiler.  Stop.

**Comment by Joechann0831** [comment]
Hi, I've got the same problem as yours. Have you ever solved this problem? It would be kind of you to tell me your solution. Thanks a lot!
