### ISSUE TITLE
Finetuning error question

### ISSUE THREAD

**Issue by iamyup** [facebook/C3D#44]
Hi, 

I have a question about finetuning example.
I am trying findtuning with UCF101 dataset.

I tried this input video list file but I got below error.
![ucf101_finetuning_error](https://cloud.githubusercontent.com/assets/4445350/11502893/cd1780a4-9880-11e5-9cb2-63129f4b7574.JPG)

I already checked the #7 and I knew that the cause is exceeded frame number.

I just modified your train_01.lst that reduce all starting frame numbers by 1.
Actually, I expected that the modified list file is working.

I attached my input list file.
https://drive.google.com/file/d/0B8SF8y0vnydpQm01TERSbElhRVU/view?usp=sharing

**Comment by dutran** [comment]
@iamyup I think you got the same problem as #7, if you use videos, there some minor differences in term of UCF101 avi files and also codecs. So you may have problem with missing the last frames.
There are two options that you can try:
1) extract avi -> frames and regenerate the list file according to your real existing frames.
2) write script to check the number of frames for each avi file you have, base on that regenerate new list file based on the number of frames that you have.

Let me know if those options work for you

**Comment by iamyup** [comment]
@dutran Thanks for your comment. I am trying second option.
I regenerated new list file based on the number of frames that I have.
I am running the finetuning example. I will let you know when I get the result.

**Comment by dutran** [comment]
Does the option work for you?

**Comment by iamyup** [comment]
@dutran Sorry for late answer.
Thanks for your concern. Yes. It worked. and I finished the training.

And I modified the test list file for testing. I ran test and I got below error message while running test.
![finetuning_test_7](https://cloud.githubusercontent.com/assets/4445350/11621947/843f3740-9d04-11e5-9e48-1b2bf7af6bea.png)

I regenerated the test list file based on the number of frames that I have.

**Comment by dutran** [comment]
@iamyup some of your clips in the testing list file are not available (or failed to read). I had a trigger that require testing to be completed (meaning not missing any clip). You can comment out the trigger (if you don't need exact accuracy, assuming missing some examples does not change much the final accuracy if your testing set is large) or check you list file and remove the failed examples.

**Comment by hunter-87** [comment]
@iamyup how do you count the number of frames? 
i had the same problem using the number of frames you can read from file properties (like with opencv CV_CAP_PROP_FRAME_COUNT ) that sometime can be incorrect
you can solve counting the frames yourself or using an external tool to do the job ( i used ffprobe with the option -count_frames)

**Comment by iamyup** [comment]
Hi @dutran and @hunter-87 
Sorry for late reply and Thanks for your kind comments.

@dutran 
Ok, I understood it now, then how about add some code for printing out the file name ?

@hunter-87 
Yes. I counted the number of frames using opencv with CV_CAP_PROP_FRAME_COUNT. I will try ffprobe as you mentioned.

**Comment by dutran** [comment]
@iamyup I think you may get your issue fixed now?

**Comment by iamyup** [comment]
Yes. I fixed the issue. Thanks. 
Happy New Year~ :-)

**Comment by dutran** [comment]
Happy new year! :)
