### ISSUE TITLE
compute frame mean file failed

### ISSUE THREAD

**Issue by TinkerBell123** [facebook/C3D#45]
hi du,i use ffmpeg to extract frames from videos,here is some examples of my frames :
000001.jpg 000021.jpg 000041.jpg 000061.jpg 000081.jpg 000101.jpg 000121.jpg 000141.jpg 000161.jpg 000181.jpg

and i use the train_01.lst in your c3d_finetuning fiels ,the path is right,when i run the create_volume_mean file,there some error:

I1202 14:35:56.476048 31451 compute_volume_mean_from_list.cpp:53] using dropping rate 10
I1202 14:35:56.476285 31451 compute_volume_mean_from_list.cpp:81] Starting Iteration
E1202 14:35:56.595129 31451 compute_volume_mean_from_list.cpp:107] Processed 10000 files.
E1202 14:35:56.599031 31451 compute_volume_mean_from_list.cpp:113] Processed 10725 files.
I1202 14:35:56.599041 31451 compute_volume_mean_from_list.cpp:120] Write to ucf101_train_mean.binaryproto
I1202 14:35:56.599046 31451 compute_volume_mean_from_list.cpp:121] sum blob num: 1
I1202 14:35:56.599051 31451 compute_volume_mean_from_list.cpp:122] sum blob channels: 3
I1202 14:35:56.599056 31451 compute_volume_mean_from_list.cpp:123] sum blob length: 16
I1202 14:35:56.599061 31451 compute_volume_mean_from_list.cpp:124] sum blob height: 0
I1202 14:35:56.599064 31451 compute_volume_mean_from_list.cpp:125] sum blob width: 0

I add some test print in cpp. and I check the compute_volum_mean_from_list.cpp:

ReadImageSequenceToVolumeDatum(frm_dir.c_str(), start_frm, label, length, height, width, sampling_rate, &datum);
69 sum_blob.set_num(1);
70 sum_blob.set_channels(datum.channels());
71 sum_blob.set_length(datum.length());
72 sum_blob.set_height(datum.height());
73 sum_blob.set_width(datum.width());

i think the erro happen in the function ReadImageSequenceToVolumeDatum,the height=128,width=171,and datum.height()=0,datum.width()=0.

so ,could you give me some suggest ,thank you !

**Comment by dutran** [comment]
@TinkerBell123 have you sorted out your issue?

**Comment by TinkerBell123** [comment]
yes,i sorted it out .
But there comes another problems,when i run train_ucf101.sh:
F1202 20:52:52.343057 34102 syncedmem.cpp:47] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7f3a64a5016d  google::LogMessage::Fail()
    @     0x7f3a64a5202f  google::LogMessage::SendToLog()
    @     0x7f3a64a4fd03  google::LogMessage::Flush()
    @     0x7f3a64a5294e  google::LogMessageFatal::~LogMessageFatal()
    @           0x47582f  caffe::SyncedMemory::mutable_gpu_data()
    @           0x45d252  caffe::Blob<>::mutable_gpu_data()
    @           0x4e3f09  caffe::Convolution3DLayer<>::Forward_gpu()
    @           0x47bce8  caffe::Net<>::ForwardPrefilled()
    @           0x465479  caffe::Solver<>::Test()
    @           0x4678d1  caffe::Solver<>::Solve()
    @           0x4374bd  main
    @     0x7f3a61567d5d  __libc_start_main
    @           0x436e5d  (unknown)

I even set both train and test the batch size to  1,there is still  out of memory .
can you give some suggestions?
