### ISSUE TITLE
some install error

### ISSUE THREAD

**Issue by sophieag** [facebook/C3D#46]
Hi, I got the below error when install. Could you help me with an old cuda vision?
![image](https://cloud.githubusercontent.com/assets/14370904/11611380/9d908a3c-9c05-11e5-9eb9-4100573d1f20.png)

**Comment by dutran** [comment]
@sophieag see this https://github.com/facebook/C3D/issues/10

**Comment by sophieag** [comment]
Thank you so much.
And could I ask you another question? Since I have use the nlpcaffe for the LSTM code and make_all both of them, could I use these two tool together?

**Comment by dutran** [comment]
C3D is branched from an old branch of caffe where there is no nlpcaffe. So the answer is no.

**Comment by sophieag** [comment]
Well, thank you for the reply. Maybe I just use different path to run different code..
Thank you~
