### ISSUE TITLE
Videos of various lengths 

### ISSUE THREAD

**Issue by andrubrown** [facebook/C3D#47]
I have gotten the examples to work and I'm now trying to run experiments on my own data.

I'm wondering how C3D handles videos of different lengths. I would like to set the stride to 1 and include all the frames but the videos are of different lengths (100 - 170 frames). What is the best way to handle that kind of data?

I'm running into trouble with computing the mean but my first thought is that it's related to the lengths of the videos.

create_volume_mean.sh:
GLOG_logtostderr=1 ../../build/tools/compute_volume_mean_from_list.bin ../c3d_finetuning/train_house_01.lst 200 128 128 1 house_train_mean.binaryproto 

andrew@andrew-All-Series:~/caffe/C3D/examples/house$ sh create_volume_mean.sh
I1206 14:20:56.749550 23315 compute_volume_mean_from_list.cpp:80] Starting Iteration
E1206 14:20:56.756093 23315 compute_volume_mean_from_list.cpp:112] Processed 1524 files.
I1206 14:20:56.756122 23315 compute_volume_mean_from_list.cpp:119] Write to house_train_mean.binaryproto

The resulting house_train_mean.binaryproto is only 11 bytes. Like the other issues, I have made the folder names absolute and the file names are %06d.jpg.

**Comment by dutran** [comment]
@andrubrown 
What is the best way to handle that kind of data?
The simplest way you may want to try is to extract the feature densely (stride = 1), the average feature over videos.

The resulting house_train_mean.binaryproto is only 11 bytes. Like the other issues, I have made the folder names absolute and the file names are %06d.jpg.
It seem there was no clip had been read and thus empty mean file.

Minor:
I notice you use different frame aspect ratio (128x128): "GLOG_logtostderr=1 ../../build/tools/compute_volume_mean_from_list.bin ../c3d_finetuning/train_house_01.lst 200 128 128 1 house_train_mean.binaryproto" If you data has ratio 1:1 for w:h, you can do so, but remember to do the same on you data layer.
