### ISSUE TITLE
confused  about mean file

### ISSUE THREAD

**Issue by Michael-Guo** [facebook/C3D#50]
Before an image or a frame of video are thrown into a CNN, we usually subtract a mean file from the input image. And you have provided a mean file named " fb_train16_128_mean.binaryproto". How was this file created. Is it average image of all images in the train set? If I finetune my model in my own dataset, should I creat a new mean file for the new dataset?
Thanks a lot!

**Comment by dutran** [comment]
@Michael-Guo if you fine-tune for your new data set, you may want to (should) compute the new mean file for your dataset.
