### ISSUE TITLE
Successfully extracted 0 features!

### ISSUE THREAD

**Issue by Michael-Guo** [facebook/C3D#51]
Hello, I want to extract all features of UCF101. I modify your provided train_01.lst and test_01.lst as follow:
For input list:
[Uploading input_train_01_new_ucf101.txt…]()

For output lsit:
[output_train_01_new_ucf101t.txt](https://github.com/facebook/C3D/files/60832/output_train_01_new_ucf101t.txt)

However, Successfully extracted 0 features! I didn't get any features. 
Thanks a lot!

**Comment by dutran** [comment]
What is you command line to run. This result may be
1) you prefix file is empty OR
2) your input list file is empty

**Comment by Michael-Guo** [comment]
my input and output file are not empty. My command line is as follow:

GLOG_logtosterr=1 ../../build/tools/extract_image_features.bin prototxt/c3d_sport1m_feature_extractor_frm.prototxt conv3d_deepnetA_sport1m_iter_1900000 0 50 1 prototxt/output_train_01_new_ucf101.txt fc7-1

**Comment by dutran** [comment]
@Michael-Guo can you share the full screen snapshot?

**Comment by Michael-Guo** [comment]
@dutran I have solved my problem. I think maybe there are something wrong with your train or test list. For example, suppose the video has 47 frames, 47 is not divided exactly by 16, 16*3 = 48. It misses one frame. In this situation, your train list will contain these class labels : 1 17 33. So the third clip will miss one frame No.48. Then I copy the No.47 frame as N0.48. Then features are extracted successfully.

**Comment by dutran** [comment]
Glad to hear!
