### ISSUE TITLE
'A total of 0 video chunks'

### ISSUE THREAD

**Issue by Prithviraj7** [facebook/C3D#54]
Hi,
I am trying to train from scratch for a different dataset (UCF Sports). But for that I have fintune the model first.
My train_01.lst contains frame names as follows:
```
/.../..../action1/1.png 0
/.../..../action1/2.png 0
.
.
.
/.../..../action2/1.png 1
/.../..../action2/2.png 1
```
and so on so forth.

But when I run
``` sh ucf101_finetuning.sh ```
 I am getting the message 'A total of 0 video chunks'. Please specify the format in which I should store the video frames.

TIA,
Prithviraj

**Comment by Michael-Guo** [comment]
your train_01.lst is wrong. the image file name's format is not right. Please follow the original train list' format the author provided

**Comment by dutran** [comment]
@Michael-Guo thanks for your helps. Yes, @Prithviraj7 please follow the user guide.

**Comment by Prithviraj7** [comment]
OK I figured it out. 
Could you please give step by step instruction for training a model from scratch, so that I can extract from it?

There is no documentation for the 'training a model from scratch' example.
