### ISSUE TITLE
Get weights and biases of convolutional layers

### ISSUE THREAD

**Issue by MarcoSaku** [facebook/C3D#55]
Hi! I need to get the weights and the biases of the kernels in convolutional layer. Unfortunately using the python wrapper it seems that it doesn't work: I obtain an object of 4 dimensions instead 5. For example using the definition file for UCF-101, in the first convolutional layer I have num_output=64 and kernel size=3x3x3. If I use the python wrapper: 
```
caffe_net = caffe.Net(prototxt_filename,caffemodel_filename)
weights=caffe_net.params['conv1a'][jj].data
weights.shape
(64, 3, 3, 3)
```
I suppose that the shape should be (64,3,3,3,3). Any help would be appreciated, even a piece of C code.
Thanks.

**Comment by dutran** [comment]
@MarcoSaku you're right. You supposed to get 64x3x3x3x3 for conv1. You can use this tool (https://github.com/facebook/C3D/blob/master/tools/extract_learned_filters.cpp) to extract the weights of the filters including bias.

**Comment by MarcoSaku** [comment]
Thanks for the reply! I edited your script to write directly all the weights in separated files

[extract_learned_filters_ALL.txt](https://github.com/facebook/C3D/files/74244/extract_learned_filters_ALL.txt)
