### ISSUE TITLE
CUBLAS_STATUS_EXECUTION_FAILED   when fintune on UCF101

### ISSUE THREAD

**Issue by Michael-Guo** [facebook/C3D#56]
When I finetuned C3D on UCF101 by your shell ucf101_finetuning.sh, I encounted an error in itteration 4180
 
Check failed status = CUBLAS_STATUS_SUCCESS.

Just like this picture

![1](https://cloud.githubusercontent.com/assets/12717447/12031560/6001f5e8-ae48-11e5-87d1-afdcb2d1a011.jpg)

What's wrong with me? Thank you!

**Comment by Michael-Guo** [comment]
I have solved my problem right now. Because my conputer was set to suspend when no use in an hour. it's my mistake.

**Comment by dutran** [comment]
@Michael-Guo have you figured out your issue? If so, could you please share your solution? Thanks

**Comment by dutran** [comment]
Glad to hear!
