### ISSUE TITLE
Accuracy difference

### ISSUE THREAD

**Issue by visionresearcher** [facebook/C3D#57]
Hi,
I trained my network on a dataset and the testing accuracy while training was 100%. However, when I used the same trained network to extract fc6,fc7 and prob on the same testing dataset, the accuracy computed from .prob is around 50%, which is weird.

Any help in this regard is appreciated.

**Comment by Michael-Guo** [comment]
Which kind of classifier did you use? @visionresearcher

**Comment by visionresearcher** [comment]
I'm not using any classifier on the top. I'm using the c3d network which has soft max classification layer.

**Comment by dutran** [comment]
@visionresearcher could you share your prototxt files?

**Comment by visionresearcher** [comment]
@dutran 
Here are the train and test prototxt files I used to train the network:


[conv3d_samplenet_train.txt](https://github.com/facebook/C3D/files/78007/conv3d_samplenet_train.txt)
[conv3d_samplenet_test.txt](https://github.com/facebook/C3D/files/78008/conv3d_samplenet_test.txt)

Here is the protxt file I used for feature extraction and getting probabilities:

[c3d_samplenet_feature_extractor_frm.txt](https://github.com/facebook/C3D/files/78009/c3d_samplenet_feature_extractor_frm.txt)

**Comment by chuckcho** [comment]
@visionresearcher I would turn off shuffle in c3d_samplenet_feature_extractor_frm.txt and in conv3d_samplenet_test.txt.

**Comment by dutran** [comment]
I think @chuckcho is right. When you extract features, you need to turn shuffle = false, so that you keep the correspondences between inputs and features. As you shuffled, the your features are extracted in a random order. Thus you get 50% accuracy (random chance as you have 2 classes)
