### ISSUE TITLE
Please add documentation for training a network from scratch

### ISSUE THREAD

**Issue by Prithviraj7** [facebook/C3D#58]

**Comment by dutran** [comment]
Added to my task list. Thank @Prithviraj7 for posting the request.

**Comment by fahimeh62** [comment]
Hi Du,
I want to train C3D on UCF101 data from scratch. I tried once, but I got the low accuracy. How many itterations would be required to have a good result? (I used learning rate:0.003 and stepsize: 20000.
Do you have another suggestion?)
Thanks a lot.

**Comment by dutran** [comment]
I think this has been added in the User Guide already. Please refer to it.
