### ISSUE TITLE
FBVideo Network

### ISSUE THREAD

**Issue by kirillgavrilyuk** [facebook/C3D#62]
There are two network prototxts available in the C3D/examples/c3d_feature_extraction/prototxt/. One is for Sports1M dataset and pre-trained model is available on http://vlg.cs.dartmouth.edu/c3d/. Another one is for FBVideo. As I can understand from the paper it is the network which was trained on I380K dataset. But I can't find any references about how to download it. Is it available? If not, will it be available? The same questions about I380K dataset.

**Comment by dutran** [comment]
The I380K dataset and the network pre-trained on this dataset cannot be released at the moment and we do not have any plan to release it (at least for a short time from now).

**Comment by eswears** [comment]
Dutran, Has there been any progress on either releasing the I380K dataset or it's corresponding C3D pretrained model?
