### ISSUE TITLE
extracting model parameters

### ISSUE THREAD

**Issue by AtousaTorabi** [facebook/C3D#63]
Hi,
I am trying to load network and extarct fully connect layers parameters of C3D.  I am using caffe.Net() function but I get:
Failed to parse NetParameter file: ../prototxt/c3d_deploy.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

I am wondering If I can use caffe.Net to begin with since this is 3D CNN. If this is the case, could you please let me know how I should define the data layer. I am doing this:

input: "data"
input_shape {
  dim: 10
  dim: 3
  dim: 128
  dim: 171
  dim: 16
}  

Best,
Atousa

**Comment by dutran** [comment]
@AtousaTorabi this C3D version was branched from an old version of caffe. Some new functions/options from the new caffe may not work. Please follow the User Guide to see how to run/use C3D.

**Comment by AtousaTorabi** [comment]
Hi,

Thanks for your response. In your guide there is nothing related how to
save network parameters and it is only about how to train the network and
extract features. Could you please advice?

Best,
Atousa
