### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by fahimeh62** [facebook/C3D#64]
Hi 
My data are in size of 128 height and 171width. I have a problem to generate mean file from my data.  I got this error after running create_train_volume_mean.sh:

F0117 13:49:33.372684 28838 compute_volume_mean_from_list.cpp:92] Check failed: size_in_datum == data_size (1050624 vs. 0) Incorrect data field size 1050624

When I want to use yoyr proposed mean for UCF example after runing my ".sh" file for finetuning I get this error:

F0117 13:43:52.987411 28301 video_data_layer.cpp:346] Check failed: ReadImageSequenceToVolumeDatum(file_list_[id].c_str(), 1, label_list_[id], new_length, new_height, new_width, sampling_rate, &datum) 

Could you please help me to fix it?
Thanks a lot.

**Comment by dutran** [comment]
@fahimeh62 This error messing indicates that C3D cannot read inputs. It may be the list file is pointing to a wrong path or your opencv did not compiled with ffmpeg properly. Please check your list file.

**Comment by fahimeh62** [comment]
@dutran Thanks for reply. Do you mean that list file is the reason for first problem or second or both?
My list file looks like this:

/home/user/C3D/examples/c3d_finetuning/hmdb/crop1/brush_hair/April_09_brush_hair_u_nm_np1_ba_goo_0/ 1 0
/home/user/C3D/examples/c3d_finetuning/hmdb/crop1/brush_hair/April_09_brush_hair_u_nm_np1_ba_goo_0/ 17 0
/home/user/C3D/examples/c3d_finetuning/hmdb/crop1/brush_hair/April_09_brush_hair_u_nm_np1_ba_goo_0/ 33 0
/home/user/C3D/examples/c3d_finetuning/hmdb/crop1/brush_hair/April_09_brush_hair_u_nm_np1_ba_goo_0/ 49 0

and my images format looks like: 000002.jpg , 000003.jpg
The images start from 000002.jpg. Is there any problem?
Thanks in advance.

**Comment by dutran** [comment]
Yes, that the problem. This PR solves your problem if you have frame starting from 2 (https://github.com/NathanDeMaria/C3D/commit/df73d1201f9c2c7d872a39e0a83dfa8626f95720). Also, if you have frames starting from 2, why you have 

/home/user/C3D/examples/c3d_finetuning/hmdb/crop1/brush_hair/April_09_brush_hair_u_nm_np1_ba_goo_0/ 1 0

In you list file?

**Comment by fahimeh62** [comment]
@dutran Thanks for the solution. 
Yes, you are right, I forgot to update these lines in my comment.

**Comment by fahimeh62** [comment]
@dutran Hi
I tried to use a different size for input data rather than 128 by 171.
I computed the mean file myself based on new size, but the problem is: it returned me the "loss=nan" during training!
What should I do to fix it?
Thanks in advance.
