### ISSUE TITLE
Make Error with OpenCV

### ISSUE THREAD

**Issue by jcoreyes** [facebook/C3D#67]
I'm trying to train a model using .avi files so I need opencv, ffmpeg, and codecs. I've installed opencv 3.0 and the other packages. When I try running make for c3d, I get a undefined reference error with an open cv function. I'm running on Ubuntu 14.04 with CUDA 7.0. Do I need opencv 2.4 or should 3.0 work?
Here's my error log:
/usr/bin/g++ build/tools/compute_volume_mean.o build/lib/libcaffe.a -o build/tools/compute_volume_mean.bin -pthread -fPIC -DNDEBUG -O2 -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -Ibuild/src -I./src -I./include -I/usr/local/cuda/include -L/usr/local/lib -L/usr/local/lib -L/usr/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -lcudart -lcublas -lcurand -lpthread -lglog -lprotobuf -lleveldb -lsnappy -lboost_system -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs -lopencv_objdetect -lcblas -latlas -Wall
build/lib/libcaffe.a(image_io.o): In function `caffe::ReadVideoToVolumeDatum(char const*, int, int, int, int, int, int, caffe::VolumeDatum*)':
image_io.cpp:(.text+0x1905): undefined reference to `cv::VideoCapture::VideoCapture()'
image_io.cpp:(.text+0x1abe): undefined reference to `cv::VideoCapture::open(cv::String const&)'
image_io.cpp:(.text+0x1ace): undefined reference to `cv::VideoCapture::isOpened() const'
image_io.cpp:(.text+0x1c91): undefined reference to `cv::VideoCapture::~VideoCapture()'
image_io.cpp:(.text+0x1d22): undefined reference to `cv::VideoCapture::get(int) const'
image_io.cpp:(.text+0x1d6d): undefined reference to `cv::VideoCapture::set(int, double)'
image_io.cpp:(.text+0x1de1): undefined reference to `cv::VideoCapture::set(int, double)'
image_io.cpp:(.text+0x1e35): undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
image_io.cpp:(.text+0x1f7e): undefined reference to `cv::VideoCapture::release()'
image_io.cpp:(.text+0x1fc3): undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
image_io.cpp:(.text+0x22e9): undefined reference to `cv::VideoCapture::~VideoCapture()'
collect2: error: ld returned 1 exit status
make: *** [build/tools/blob_proto_to_blob_binary.bin] Error 1
make: *** Waiting for unfinished jobs....

**Comment by jcoreyes** [comment]
Was able to get it working by adding opencv_videoio to LIBRARIES in the Makefile.

**Comment by GilLevi** [comment]
@jcoreyes This bugged me for hours, thanks!

**Comment by deepaksharma36** [comment]
Thanks @jcoreyes for the suggestion it worked for me as well!
  LIBRARIES += opencv_core opencv_highgui opencv_imgproc opencv_videoio
