### ISSUE TITLE
Something wrong with create_volume_mean

### ISSUE THREAD

**Issue by SuperLee506** [facebook/C3D#68]
My input file are videos,like:
/home/superlee/Documents/C3D-master/data/videos/1.avi 0 70
/home/superlee/Documents/C3D-master/data/videos/2.avi 0 39
...
start from the first frame.Then I run:
GLOG_logtostderr=1 ../../build/tools/compute_volume_mean_from_list.bin video_iput.txt 16 128 171 1 example_mean.binaryproto

The results are:
I0122 09:56:57.322970  3717 compute_volume_mean_from_list.cpp:80] Starting Iteration
E0122 09:56:57.369540  3717 compute_volume_mean_from_list.cpp:112] Processed 4087 files.
I0122 09:56:57.369570  3717 compute_volume_mean_from_list.cpp:119] Write to example_mean.binaryproto

The issue:accutually,the input file has 4088 videos and it only processed 4087 files.What's whorse,the output mean file seems like an empty file.When I run train example to load it,the resuls are:

I0122 10:02:17.404588  3764 video_data_layer.cpp:387] Loading mean file from example_mean.binaryproto
F0122 10:02:17.404616  3764 blob.cpp:98] Check failed: data_ 
*** Check failure stack trace: ***
Aborted (core dumped)

My input file path is the full path,so,the path should be correct,and I'm sure opencv is correctly installed.
I'm confused with this matter,and I can't find any help .Any suggestion would be appreciate.
Thanks

**Comment by SuperLee506** [comment]
Oh,I find the matter,
refer https://github.com/facebook/C3D/issues/38

**Comment by Michael-Guo** [comment]
@SuperLee506  I encounter the same problem with you, could you please tell me how did you solve it? Thanks!

**Comment by SuperLee506** [comment]
@Michael-Guo Do you go through the #38 ,I refer to it.Does it help?

**Comment by Michael-Guo** [comment]
@SuperLee506 Yes, I have solved my problem, thanks a lot!
