### ISSUE TITLE
Question about C3D_finetuning:c3d_ucf101_finetuning_train.prototxt

### ISSUE THREAD

**Issue by SuperLee506** [facebook/C3D#69]
Hi,
my question is why the fc layers's names are different from "c3d_feature_extraction"'.
I think if the names are the same,it will copy the value from "conv3d_deepnetA_sport1m_iter_1900000",
It will do better than random initial,is it right?
thanks.

**Comment by dutran** [comment]
That should be different for fc layers, you only copy the conv layers' weights and initialize fc layers randomly. It worth to note that fc layers of the fine-tune model have different number of parameters.

**Comment by SuperLee506** [comment]
@dutran  Thank you for reply.I know just the fc8 layer have different number of parameters,but fc6 and fc7 both have 4096 output .Am I right?

**Comment by ardasnck** [comment]
Hello @dutran,
Thank you very much for your C3D contribution.

I was wondering do you keep the convolutional layers fixed and only train the fc layers? Or after randomly initializing the fc layers all network (conv layers are copied + fc layers are randomly initialized) is trained? 

Thank you very much.
