### ISSUE TITLE
Inconsistent behavior with high batch size

### ISSUE THREAD

**Issue by cagdasbas** [facebook/C3D#71]
Hi,
I'm running C3D feature extraction with the example script "examples/c3d_feature_extraction/c3d_sport1m_feature_extraction_frm.sh" for my own videos, for SumMe dataset in particular. I have an Asus TitanX GPU and I tought it could handle more a batch size of 100 but apparently it couldn't.

Strange thing is, It never gave me en error but instead said XX feature extracted successfully but I observed two different outcome.
One is for every two batch, 50 features extracted but 100 feature file is written to disk. It replicates extracted 50 feature as 100 and featureind.fc* == (featureind +50).fc*. This means %25 of the feature vectors for each video is identical to another %25 percent and %75 of the features are unique. It was the same for every 25 video. 

Second is almost the same as the first observation but instead of replicating 50 features for each batch and writing it to disk, code simply skip these 50 frame. This means %25 of the feature file does not appear on the disk at all. 

When I reduce the batch size to 50, There are no problems. The same input and output files are working perfectly and I assumed that code cannot determine if there was an error on gpu and behaves strangely. Am I missing something or is there a bug here?

I'm running the C3D code on a Debian Linux 7.9 x64 with a TitanX; cuda version is 7. 
Thanks

**Comment by dutran** [comment]
"When I reduce the batch size to 50, There are no problems. The same input and output files are working perfectly and I assumed that code cannot determine if there was an error on gpu and behaves strangely. Am I missing something or is there a bug here?"

I think you only changed the batchsize in command line, but not in the prototxt file. You need to change both.

**Comment by cagdasbas** [comment]
Actually I didn't. I will try this, thank you but as I've said It happens for one of every two batch. One batch is good and one batch is half corrupt. Code sends the whole batch and does not send ay more until all the batch is completed right? 
I've also checked the GPU memory usage and with a 50 batch size 6500MiB memory is allocated and my GPU has 12GB of memory. Is this suggest that batch size 100 will be large and does not fit into GPU memory?

**Comment by dutran** [comment]
What happened is: you network only extracts features of 50 clips, and the writer (independent from the net) write 100 files. The first 50 files are non-empty, then the second 50 files are empty. Then so the next round, the network extract another batch of 50 clips, while the writer writes 100 files.

You will see 50 non-empty/corrupted, followed by another corrupted files. Another issue is, the correspondences between clips and their extracted features are lost. So you only have the first 50 feature files are correct, the rest are miss-matched, even to non-corrupted files.

**Comment by cagdasbas** [comment]
Thank you for the answer. 
Is this serves a purpose? It is already written in the documentation that I need to do both but I tought it is omitted somehow, my bad. Maybe reducing the parameters into one might be more convenient to use. 
I'll extract all the features again. Thanks again.

**Comment by dutran** [comment]
I agree, the better way is to reduce it into a single argument, but i did not have time to do that (my bad :) ).

**Comment by cagdasbas** [comment]
Thanks again.
