### ISSUE TITLE
Use lmdb file for C3D

### ISSUE THREAD

**Issue by vignesh10** [facebook/C3D#72]
Hi,

For my analysis, I have created a k-channel lmdb file using the frames of UCF101 videos. 
I would like know if its possible to use this in C3D. 

If not, I would like to know if i can pass a list of frames(which are already extracted from the video) as input to the network.

Thanks in advance!!
Vignesh

**Comment by dutran** [comment]
@vignesh10 in the user guide, we have examples to use C3D with frames and videos (so the answer for your question is yes)

I did not try lmdb with C3D myself, but I did try leveldb, so I think it may work with lmdb.

**Comment by vignesh10** [comment]
Hi,

Excuse me for not being particular with my question, which is two-fold. I want to **train** the network with frames/ lmdb. 

1. With *frames*,  if i input a train.lst which contains:

* /path/to/frames/ frame_no label
* eg:/home/user/data/ 000001 1
*    /home/user/data/ 000017 1
* Error: Could not open or find file

if i change the  train.lst to contain 

* /path/to/frames/ frame_no label
* eg:/home/user/data/000001.png 1
*    /home/user/data/000017.png 1

* Then it reads a volume of **batch_size** x **channels**  x **width** x **height**, while I want it to read 
**batch_size** x **(channels x 16)**  x **width** x **height**. 
How can i make the network read a bunch of frames into a volume? 


2. If I use the LMDB file, 
* I change a few params in the conv3d_ucf101_train.prototxt.

* Error: Check failed: status.ok() Failed to open leveldb
* So, is it possible to define to the network somewhere that I will be passing lmdb ?
