### ISSUE TITLE
Error while using Leveldb file as input 

### ISSUE THREAD

**Issue by vignesh10** [facebook/C3D#73]
Hi,

I created a leveldb file with each input being k(16 here)-channel(bunch of images). I also compute the volume mean for it.

When I give the Leveldb file as input, i get these statements:
```
I0128 17:00:48.700945  9418 data_layer.cpp:145] Opening leveldb leveldb/leveldb_train/
I0128 17:00:48.842083  9418 data_layer.cpp:185] output data size: 30,48,1,112,112
```

the batch_size is `30`. The image size is `112x112`. But I do not understand `48 `and `1`. Ideally it should be `30x16x112x112`, right ?

I also get an error after the mean file is loaded:
`blob.cpp:98] Check failed: data_ `

Thanks in advance,

**Comment by dutran** [comment]
@vignesh10 the correct output of your data layer should be 30 x 3 x 16 x 112 x 112
