### ISSUE TITLE
CNN structure

### ISSUE THREAD

**Issue by MarcoSaku** [facebook/C3D#74]
Hi all! I noticed that the CNN implemented in file "examples/c3d_train_ucf101/conv3d_ucf101_train.prototxt" is  slighlty different from the CNN presented in the network: it has less convolutional layers and less output values in fc. Could you kindly explain me why did you use it in the example? Thank you.

**Comment by dutran** [comment]
@MarcoSaku UCF101 is a small dataset, to avoid overfiting we use a reasonable small network.

**Comment by MarcoSaku** [comment]
Thanks for the response. Any advice to create a network for YUPENN? With UCF101 network I have overfitting

**Comment by dutran** [comment]
@MarcoSaku YUPENN is even much smaller (~150 videos) compared to UCF101 (~13K videos). For this dataset, you even don't need to train or fine-tune. You just use C3D feature extractor and a linear classifier (e.g. SVM) is good enough.

**Comment by MarcoSaku** [comment]
Yes I know, but I have to train the C3D using average pooling and no biases for a project of mine. Using UCF101 structure it overfits, now I am trying to eliminate some layer and see if the overfitting is avoided
