### ISSUE TITLE
Frames time step extraction

### ISSUE THREAD

**Issue by MarcoSaku** [facebook/C3D#76]
Hi all. I would ask a question about the extraction of frames from videos to use with C3D. 
What time step are you using? Do you take a frame at each time step or do you save a frame every X? I use "ffmpeg" utility to do this process:
`ffmpeg -i 'video_name'   'frames_path'/%06d.jpg`

Is it correct? Thanks all

**Comment by dutran** [comment]
@MarcoSaku that is correct
