### ISSUE TITLE
unreasonable mean file of UCF101

### ISSUE THREAD

**Issue by antran89** [facebook/C3D#77]
Hi,
I have a double for [mean file](https://github.com/facebook/C3D/blob/master/examples/c3d_finetuning/train01_16_128_171_mean.binaryproto) of UCF 101 for finetuning. When I read the file, the value 
is unreasonable. 
```
[s, data] = read_binary_blob('c3d_finetuning_ucf101_foreground2/train01_16_128_171_mean.binaryproto');
```
The shape is
```
s =

   1.0e+09 *

    0.0514   -2.1454    0.0280   -2.1349    1.6529
```
The value of mean values is extremely negative and positive. Hope to receive your feedback about this error, whether it is the errors in mean values or the reading function is erroneous.

**Comment by dutran** [comment]
The mean file was not formatted as the feature, if you read the code (for compute_volumn_mean). Thus It cannot be read by that matlab script. It was formatted with single precision (float).
