### ISSUE TITLE
Split Layer does not work properly with 3D blobs

### ISSUE THREAD

**Issue by jonatasw** [facebook/C3D#78]
I was working on a new Conv3D architecture which demands splitting a layer into new layers. Using the split layer I noticed that the temporal dimension is dropped out. E.g. The split layer input is a 64 x 128 x 8 x 28 x 28 blob, the output is 64 x 128 x 1 x 28 x 28. I have tried (no success) merge some branches from original caffe repository.

**Comment by dutran** [comment]
@jonatasw try this https://github.com/facebook/C3D/commit/cf47bc9271fd30235e6db9a69ddbbfc13dc229e9

**Comment by jonatasw** [comment]
Now the error happens on the concat layer. Probably demands a minor change as well. 

I0223 09:11:47.195406 29183 net.cpp:76] Creating Layer split1
I0223 09:11:47.195423 29183 net.cpp:86] split1 <- pool2
I0223 09:11:47.195436 29183 net.cpp:112] split1 -> split1
I0223 09:11:47.195447 29183 net.cpp:112] split1 -> split2
I0223 09:11:47.195462 29183 net.cpp:127] Top shape: 64 128 8 28 28 (51380224)
I0223 09:11:47.195477 29183 net.cpp:127] Top shape: 64 128 8 28 28 (51380224)
I0223 09:11:47.195488 29183 net.cpp:159] split1 does not need backward computation.
I0223 09:11:47.195503 29183 net.cpp:76] Creating Layer concat1
I0223 09:11:47.195516 29183 net.cpp:86] concat1 <- split1
I0223 09:11:47.195529 29183 net.cpp:86] concat1 <- split2
I0223 09:11:47.195543 29183 net.cpp:112] concat1 -> concat1
F0223 09:11:47.195583 29183 concat_layer.cpp:44] Check failed: count_ == (*top)[0]->count() (102760448 vs. 12845056)

**Comment by dutran** [comment]
Yes, if you use concat. Simple fix is coming in few minutes

**Comment by dutran** [comment]
@jonatasw give it a try again.

**Comment by jonatasw** [comment]
Yes. It is working now. Thanks.

**Comment by dutran** [comment]
Glad to hear!
