### ISSUE TITLE
Continue training using snapshot

### ISSUE THREAD

**Issue by fahimeh62** [facebook/C3D#80]
@dutran Hi 
I want to know is it possible in C3D that we continue training using snapshot of the model that we already interrupted its training?
I know that it is possible in caffe for 2D models, what about C3D?
Thanks in advance.

**Comment by dutran** [comment]
@fahimeh62 you can always do that by train_net.bin solver_prototxt snapshot.solverstate

**Comment by fahimeh62** [comment]
@dutran If I finetuned the previous time (not training from scratch), instead of "train_net.bin solver_prototxt snapshot.solverstate"
I can use "finetune_net.bin solver_prototxt snapshot"
right?

**Comment by dutran** [comment]
Both cases should work for you. But train_net uses snapshot.solverstate and finetune_net uses snapshot

**Comment by fahimeh62** [comment]
@dutran Perfect. Thanks
