### ISSUE TITLE
 Check failed: error == cudaSuccess (8 vs. 0)

### ISSUE THREAD

**Issue by HaiminZhang** [facebook/C3D#81]
I have a problem when executing the following script:
 sh c3d_sport1m_feature_extraction_video.sh 
F0225 14:29:46.455771   743 vol2col.cu:75] Check failed: error == cudaSuccess (8 vs. 0)  invalid device function
CUDA version is 7.5  
GPU is GTX TITAN X
Could assistance be provided ?

**Comment by dutran** [comment]
@HaiminZhang you got this issue https://github.com/facebook/C3D/issues/33

**Comment by HaiminZhang** [comment]
@dutran Thanks a lot for your help. This issue has been resolved by setting:
CUDA_ARCH := -gencode=arch=compute_52,code=sm_52 \
		-gencode=arch=compute_52,code=compute_52

**Comment by dutran** [comment]
Glad to hear!
