### ISSUE TITLE
How to implement finetuning sucessfully?

### ISSUE THREAD

**Issue by tzczsq** [facebook/C3D#83]
I am a newer and  can not sucessfully implement your 3D-CNN code. I have some questions:
1) I can not dowload C3D User Guide from your site: http://vlg.cs.dartmouth.edu/c3d/.
2) I want to perform fine-tuning task with your examples.Maybe I can not prepare data well.
As you stated:
Prepare data
----------------------
* Download ucf101
* Extract frames (you can also use .avi by modifying list files and prototxt files, but this example uses frames)
* Modify train_01.lst and test_01.lst so that the paths point to the directories containing extracted frames. We note that this example uses the first public train/test splits provided by UCF101.
In the seond step of prepare data:
a. How to extract frames from .avi file? After extract frames, should they be compacted with .zip files?
b. I want to finetuning it with .avi files. How to modify it?
   I have modified the list files, but do not know modify which prototxt files.

**Comment by dutran** [comment]
@tzczsq 
a. How to extract frames from .avi file? After extract frames, should they be compacted with .zip files? 
You can use ffmpeg or any tool that you are most comfortable. For ffmpeg, can use e.g. 
ffmpeg -i your_video_file -q:v 1 path_to_your_sub_dir/%06.jpg

After extracted, you dont need to zip them

b. I want to finetuning it with .avi files. How to modify it? I have modified the list files, but do not know modify which prototxt files.
See the example in feature extraction e.g. https://github.com/facebook/C3D/blob/master/examples/c3d_feature_extraction/prototxt/input_list_video.txt

Good luck with your experiments
