### ISSUE TITLE
Could models trained on I380K and fine-tuned on Sports-1M be provided?

### ISSUE THREAD

**Issue by HaiminZhang** [facebook/C3D#84]
I am wondering could models trained on I380K and fine-tuned on Sports-1M be provided?
Any help will be much appreciated. 

Thanks a lot.

**Comment by dutran** [comment]
@HaiminZhang the model we provided at http://vlg.cs.dartmouth.edu/c3d/ in fact is the model trained on I380K, then fine-tuned on Sports-1M
