### ISSUE TITLE
could you publish a new version with the latest caffe？

### ISSUE THREAD

**Issue by attitudechunfeng** [facebook/C3D#87]
Hi，dutran. I'm very interested in your work on C3D and would like to follow the work. But your model is based the old version of caffe and it's not easy for me when try to do some surgery on the network. So could you publish a new version using the latest caffe?

**Comment by dutran** [comment]
This is what I want to do, but I'm so busy at the moment (in my final year at graduate school). I will keep this issue open until this code is rebased to the new caffe code.

**Comment by chuckcho** [comment]
I took a stab at porting C3D into latest Caffe -- https://github.com/chuckcho/video-caffe. The training seems to work now (./examples/c3d_train_ucf101), but some issues may be expected here and there. Feel free to use it. ;)

**Comment by attitudechunfeng** [comment]
3Q very much~ that really helps me.@chuckcho

**Comment by dutran** [comment]
@chuckcho thanks for sharing your code which I believe will be useful to many people.

**Comment by chuckcho** [comment]
@dutran no problem. good luck with your thesis! ;)

**Comment by rezaabbasi** [comment]
Thanks @chuckcho for sharing your code. Is it possible for you to also share your trained model?

**Comment by linbatman** [comment]
Thanks @chuckcho.  Good job! 
I got a problem. Can you give me some hints? 
nvcc fatal   : The version ('70300') of the host compiler ('Apple clang') is not supported. I try to  back to 6.2 Xcode, but still errors.

**Comment by haohao900618** [comment]
@dutran @chuckcho Could you please pre-train the c3d model on Sports-1M with the new version of caffe (https://github.com/chuckcho/video-caffe). I think it is very useful job because many people ask for the model pre-trained on Sports-1M. Thanks a lot for your contribution.

**Comment by bitwangdan** [comment]
@haohao900618 Hi ,do you hava a pre-train the c3d model on Sports-1M with the new version of caffe ?
I'm also want to use it

**Comment by haohao900618** [comment]
@bitwangdan I'am so sorry. I don't have the c3d model pre-trained on Sports-1M. If you have one please share it with us. Thanks for you.

**Comment by dutran** [comment]
I'm finally debt-free :)
