### ISSUE TITLE
make error for C3D

### ISSUE THREAD

**Issue by learntolearn11** [facebook/C3D#88]
when I make this files, it goes wrong, 

In file included from /home/tju/software/OpenBLAS/cblas.h:5:0,
                 from ./include/caffe/util/mkl_alternate.hpp:11,
                 from ./include/caffe/util/math_functions.hpp:11,
                 from ./include/caffe/filler.hpp:13,
                 from ./include/caffe/caffe.hpp:9,
                 from examples/cpp_classification/classification.cpp:1:
/home/tju/software/OpenBLAS/common.h:289:15: error: expected identifier before 'float' #define FLOAT float
               ^
/home/tju/software/OpenBLAS/common.h:289:15: error: expected '}' before 'float' 
/usr/include/opencv2/core/core.hpp:4127:14: error: expected unqualified-id before '=' token
         FLOAT=REAL, //!< synonym or REAL
....

other environment is ubuntu 14 opencv3.0 
could anyone give me a advice? Thanks

**Comment by dutran** [comment]
Seems problem from BLAS, but I am not sure.

**Comment by learntolearn11** [comment]
solved the problem replacing the openblas by atlas,I don't know the reason...
