### ISSUE TITLE
Error while running c3d_sport1m_feature_extraction_frm.sh 

### ISSUE THREAD

**Issue by preksha12** [facebook/C3D#91]
When I ran c3d_sport1m_feature_extraction_frm.sh file then it showed error that 
line 7: ../../build/tools/extract_image_features.bin:no such file or directory

**Comment by dutran** [comment]
@preksha12 have you compiled it successfully? The message indicates that extract_image_features.bin is not been compiled yet or you are in the wrong directory.

**Comment by preksha12** [comment]
This is the first file which I am running.
Which file should I run first?
And in my folder there is no bin directory.

**Comment by dutran** [comment]
You need to compile it by 'make' at the C3D_DIR (assuming that you have your Makefile.config is correctly setup)

**Comment by preksha12** [comment]
Can you please send me this  in detail as I am not able to understand this.

**Comment by dutran** [comment]
1. C3D_DIR is the directory you get when you do git clone. For example my /home/dutran/C3D.
2. Modify Makefile.config (such that it points to correct lib/dependencies)
3. make (to compile)

**Comment by preksha12** [comment]
I have copied Makefile.config.example to Makefile.config and then following problem is coming
preksha@preksha:~/C3D$ cp  Makefile.config.example Makefile.config
preksha@preksha:~/C3D$ make c3d_image_features_frm.sh
make: *** No rule to make target `c3d_image_features_frm.sh'.  Stop.

**Comment by dutran** [comment]
@preksha12 preksha@preksha:~/C3D$ make c3d_image_features_frm.sh
should be preksha@preksha:~/C3D$ make
It will work if you modify Makefile.config to correctly points to dependencies. It'd be much better for you to try to compile caffe first. When you can successfully compile caffe. You can go back to give C3D a try.

Are you using window?

**Comment by preksha12** [comment]
I am using ubuntu 14.04 
I have tried to compile using make command and then it now gives error in #include<cuda_runtime.h>
As cuda is not installed so will it work without GPU ?

**Comment by dutran** [comment]
Sorry, it requires CUDA.

**Comment by preksha12** [comment]
Ok but thanks for you reply.
