### ISSUE TITLE
Test score #0 and Test score #1

### ISSUE THREAD

**Issue by allgrom** [facebook/C3D#92]
Hi!
I have 3 questions.
1.I ran my own c3d network and it showed:
test score #0: 0.927917
test score #1: 0.199188

What is meaning of test score #0 and test score #1?
score #0 - accuracy
score #1 - loss
2.Is there any difference between testing on fly and running ../../build/tools/test_net.bin?
3. After 5 epochs loss became nan. Why did it happen?

**Comment by dutran** [comment]
@allgrom 
1. yes, that's right.
2. there is no much different except for if you define the number of iterations are equal in both cases and prototxt for test net is idetical.
3. Without more context, it is hard to know.

**Comment by allgrom** [comment]
Thank you for your reply!
