### ISSUE TITLE
the conv3d_ucf101_train.prototxt file is not same as you described in the paper

### ISSUE THREAD

**Issue by learntolearn11** [facebook/C3D#94]
Hi, I see the conv3d_ucf101_train.prototxt, there are only five layers named conv1a,conv2a,conv3a,conv4a,conv5a,while in your paper 'Learning Spatiotemporal Features with 3D Convolutional Networks', there are 8 layers,named conv1a,conv2a,conv2b,conv3a,conv3b,conv4a,conv4b,conv5a,conv5b. so which is better?

**Comment by dutran** [comment]
This is the experiments for smaller networks showed in Fig 2. Not the one in Fig 3.

**Comment by learntolearn11** [comment]
which is better?
