### ISSUE TITLE
Error in make run test 

### ISSUE THREAD

**Issue by Mahak-8** [facebook/C3D#96]
Hi, I am trying to install C3D without CUDA. I previously tried it on the master branch and it worked all fine But now it gives me this error : 

build/test/test_all.testbin 0 --gtest_shuffle
Cuda number of devices: 0
Setting to use device 0
Current device id: 0
Note: Randomizing tests' orders with a seed of 81446 .
[==========] Running 407 tests from 72 test cases.
[----------] Global test environment set-up.
[----------] 18 tests from RandomNumberGeneratorTest/1, where TypeParam = double
[ RUN      ] RandomNumberGeneratorTest/1.TestRngGaussian2GPU
E0326 02:34:25.348212 20804 common.cpp:31] Cannot create Cublas handle. Cublas won't be available.
E0326 02:34:25.374718 20804 common.cpp:38] Cannot create Curand generator. Curand won't be available.
E0326 02:34:25.374954 20804 common.cpp:60] Curand not available. Skipping setting the curand seed.
F0326 02:34:25.375125 20804 syncedmem.cpp:47] Check failed: error == cudaSuccess (38 vs. 0)  no CUDA-capable device is detected
*** Check failure stack trace: ***
    @     0x2b32dc903daa  (unknown)
    @     0x2b32dc903ce4  (unknown)
    @     0x2b32dc9036e6  (unknown)
    @     0x2b32dc906687  (unknown)
    @           0x57b2ff  caffe::SyncedMemory::mutable_gpu_data()
    @           0x4ae77d  caffe::RandomNumberGeneratorTest_TestRngGaussian2GPU_Test<>::TestBody()
    @           0x536e13  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x52d8f7  testing::Test::Run()
    @           0x52d99e  testing::TestInfo::Run()
    @           0x52daa5  testing::TestCase::Run()
    @           0x530de8  testing::internal::UnitTestImpl::RunAllTests()
    @           0x531077  testing::UnitTest::Run()
    @           0x412c60  main
    @     0x2b32decbaec5  (unknown)
    @           0x4183ce  (unknown)
    @              (nil)  (unknown)
make: *** [runtest] Aborted (core dumped)

Thanks

**Comment by dutran** [comment]
You can compile it without GPU, but still need CUDA driver. You may not want to test because some test use GPU. But you can run and using CPU only.
