### ISSUE TITLE
Compute Volume Mean

### ISSUE THREAD

**Issue by zorozy** [facebook/C3D#97]
Hi, I have encoutered a problem with compute volume mean. 

I0326 21:38:31.500324  6252 video_data_layer.cpp:387] Loading mean file from  altimore_train16_128_mean.binaryproto
F0326 21:38:31.500362  6252 blob.cpp:98] Check failed: data_ 

My create_volume_mean file is as follow:
GLOG_logtostderr=1 compute_volume_mean_from_list prototxt/input_list_video1.lst
16 128 128 1 baltimore_train16_128_mean.binaryproto

Could anyone give me some guidance on how to use this function?

**Comment by dutran** [comment]
The provided tool allows only input list (using frames), while you are using input list (of videos). You can either minor adapt the tool, e.g. similar to this: https://github.com/facebook/C3D/pull/95 (did not fully test this, but supposed to work).
