### ISSUE TITLE
How to test on the fly?

### ISSUE THREAD

**Issue by bryanyzhu** [facebook/C3D#98]
Hi Du,

Thanks for the great C3D. Could you show me how to do test on the fly? Because right now, in the solver.prototxt file, you say you don't do test while fine-tuning.

Thanks a lot.

**Comment by dutran** [comment]
Yes, you can do that, please refer to this: https://github.com/facebook/C3D/blob/master/examples/c3d_train_ucf101/conv3d_ucf101_solver.prototxt
For sports-1M, the train net consumes almost GPU memory, thus we had to disable testing.

**Comment by bryanyzhu** [comment]
Thanks, Du. I got it.
